### ISSUE TITLE
两个节点开启ssl验证后，节点间无法连接

### ISSUE THREAD

**Issue by tinglany** [FISCO-BCOS/FISCO-BCOS#1]
按说明自己生成ca和各自节点证书，ca.json配置如下：
----------节点0的ca.json---------
hash=D841FD6A257F2699
pubkey=
orgname=
notbefore=20171221
notafter=20181221
status=1
blocknumber=30
whitelist=
blacklist=
----------节点1的ca.json---------
hash=BFCED74F3974A8C3
pubkey=
orgname=
notbefore=20171221
notafter=20181221
status=1
blocknumber=31
whitelist=
blacklist=
----------ca证书---------
hash=C8621C1F29AE21CB
pubkey=
orgname=
notbefore=20171221
notafter=20271219
status=1
blocknumber=29
whitelist=
blacklist=

=============日志
节点0的日志：
[root@192 nodedata-1]# tail -f log/log_20171221.log 
DEBUG|2017-12-21 07:25:22:782|topics发送到:0个节点
ERROR|2017-12-21 07:25:22:782|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:23:784|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:23:784|topics发送到:0个节点
ERROR|2017-12-21 07:25:23:784|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:24:785|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:24:785|topics发送到:0个节点
ERROR|2017-12-21 07:25:24:785|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:25:786|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:25:786|topics发送到:0个节点
ERROR|2017-12-21 07:25:25:786|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:26:787|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:26:787|topics发送到:0个节点
ERROR|2017-12-21 07:25:26:787|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:27:788|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:27:788|topics发送到:0个节点
ERROR|2017-12-21 07:25:27:788|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:28:790|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:28:790|topics发送到:0个节点
ERROR|2017-12-21 07:25:28:790|发送失败，无可达节点:
DEBUG|2017-12-21 07:25:29:790|发送topic请求:0 type:0
DEBUG|2017-12-21 07:25:29:791|topics发送到:0个节点

节点1的日志：
01ada1a2a71de0a40cfef02dbed533ef584d58291132aa5669c4959dbef2aa4f292da3599290e0fe22,192.168.110.129:30303
INFO|2017-12-21 07:24:02:489|Noting active node:e785a40bcfc00abb9d01e3be4cebe10ba4a1bc4b35e54901ada1a2a71de0a40cfef02dbed533ef584d58291132aa5669c4959dbef2aa4f292da3599290e0fe22192.168.110.129:30303
DEBUG|2017-12-21 07:24:02:491|subjectName:/C=CN/ST=SH/L=ZJ/O=caorg/OU=cait/CN=testca/emailAddress=f
DEBUG|2017-12-21 07:24:02:491|serialNumber:C8621C1F29AE21CB

日志停在这里不动了；

但是不开起ssl验证，两节点可正常通信，请问是否我的ca.json配置仍有问题？

**Comment by WeWebsterchen** [comment]
证书生成缺少是否根证书标识，请使用最新使用说明文档生成证书即可。
