### ISSUE TITLE
关于权限模型ARPI_Model.js脚本问题

### ISSUE THREAD

**Issue by LevenSton** [FISCO-BCOS/FISCO-BCOS#100]
看权限模型文档，文档里说用上帝账号运行ARPI_Model.js脚本，我理解的运行脚本之前，是不是没有上帝账号，而是想运行脚本之后，把config.js里面的账号设置为上帝账号，
但是看ARPI_Model.js代码，设置了4个Group对应:
Group1:链超级管理者（上帝账号） Group2:链/Filter管理者 Group3: 运维管理人员 Group4:交易人员A、B
脚本运行后，config.js里面的accout变成了Group4的权限。之后，就在也不能进行合约的部署和系统合约的调用了。 所以我认为这个脚本是不是有问题，应该把accout设置为Group1上帝账号，然后在新生成几个账号，为这些账号在分配为Group2 3 4，的权限？

**Comment by artemis-my** [comment]
个人理解，上帝账号是部署的时候就配置的，用上帝账号的意图是保证脚本运行成功，因为上帝账号拥有所有权限，源码里在权限检查时会先判断是否是god，是的话检查直接通过。

**Comment by chaychen2005** [comment]
@LevenSton，在脚本最后的环节是启动权限控制，在权限控制启动之前，任何账号（包括非上帝账号）都可以发交易的，但启动权限控制后需要有特定权限的账号（上帝账号及授权过的账号）才能进行操作。
当配置的account不是上帝账号或授权过的账号（当时account只有Group4的权限，Group4没有响应的部署及调用系统合约的授权），执行脚本完毕后就不能进行相关操作。
如果使用上帝账号来运行ARPI_Model.js脚本，就相当于您描述的对生成的Group2 3 4分配对应的权限，注意这个脚本只是为了说明对Group分配权限的例子及管理模型，而不是给账号绑定对应权限。
