### ISSUE TITLE
MySQL数据库密码如果第一位是等号，启动出错

### ISSUE THREAD

**Issue by salahgao** [FISCO-BCOS/FISCO-BCOS#1017]
如：
db_passwd==xxxxx

无法启动node 日志报错如下

info|2019-09-06 03:30:36.115052|[NETWORK][Host]P2P StartAccept,Host=0.0.0.0:30700
info|2019-09-06 03:30:36.122125|[NETWORK][Host]P2P Recv Connect, From=127.0.0.1:53790
info|2019-09-06 03:30:36.122184|[NETWORK][Host]P2P StartAccept,Host=0.0.0.0:30700
info|2019-09-06 03:30:36.127668|[NETWORK][Host]startPeerSession, From=127.0.0.1:53778,nodeID=5e20a883...
info|2019-09-06 03:30:36.127849|[NETWORK][Host]startPeerSession, From=127.0.0.1:30700,nodeID=5e20a883...
info|2019-09-06 03:30:36.133143|[NETWORK][Host]startPeerSession, From=127.0.0.1:53784,nodeID=5f83cce2...
info|2019-09-06 03:30:36.137504|[P2P][Service] Connection established,nodeID=5f83cce2...,endpoint=127.0.0.1:53784
error|2019-09-06 03:30:36.137848|[g:1][SQLConnectionPool] init connection pool failed url:0.0.0.0:3306 please check
error|2019-09-06 03:30:36.137867|[g:1][SQLConnectionPool] init connection pool failed url:0.0.0.0:3306 please check
info|2019-09-06 03:30:36.150825|[NETWORK][Host]startPeerSession, From=127.0.0.1:53790,nodeID=7f739a48...
info|2019-09-06 03:30:36.151298|[P2P][Service] Connection established,nodeID=7f739a48...,endpoint=127.0.0.1:53790

**Comment by qwdarrenyin** [comment]
Hi salahgao
我用带等号的密码去验证了下，是ok的。
从“init connection pool failed url:0.0.0.0:3306 please check”这个错误日志上看，帮忙确认下db_ip是不是没有配置。将type配置为mysql之后，如下几个配置都需要配置。
    db_ip=
    db_port=
    db_username=
    db_passwd=
    db_name=
