### ISSUE TITLE
std::exception::what: remote_endpoint: Transport endpoint is not connected 问题

### ISSUE THREAD

**Issue by ackfin** [FISCO-BCOS/FISCO-BCOS#1034]
fisco-bcos 运行一段时间后，出现报错
`info|2019-09-18 11:52:10.790110|[g:1][CONSENSUS][PBFT]checkTimeout Succ,view=191,toView=192,nodeIdx=0,changeCycle=0,myNode=444a4d62...,timecost=0.313
info|2019-09-18 11:52:10.791409|[g:1][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=191,org_changeCycle=0,cur_changeCycle=0,to_view=192
error|2019-09-18 11:52:11.226911|[CHANNEL]IO thread error,what=Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: remote_endpoint: Transport endpoint is not connected
`
这个问题要怎么解决？

**Comment by bxq2011hust** [comment]
https://stackoverflow.com/questions/22425582/remote-endpoint-transport-endpoint-is-not-connected

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/blob/5286811961664385eddae2f28e702a63194b1fb7/libchannelserver/ChannelServer.cpp#L85

**Comment by ackfin** [comment]
@bxq2011hust 感谢，改了这两行代码，重新编译就恢复正常了。
```
        boost::system::error_code ec;
        auto remoteEndpoint = session->sslSocket()->lowest_layer().remote_endpoint(ec);
```
