### ISSUE TITLE
控制台console使用get_account.sh生成的账户无国密选项

### ISSUE THREAD

**Issue by a1753630314** [FISCO-BCOS/FISCO-BCOS#1044]
提个建议：控制台使用get_account.sh生成的账户的时候，建议get_account.sh 增加国密账户生成模式。

**Comment by bxq2011hust** [comment]
规划中，下个版本会提供

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/console/issues/192

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/console/pull/193
