### ISSUE TITLE
关于2.0.0-rc3版本自动化部署合约

### ISSUE THREAD

**Issue by DeYuZhao** [FISCO-BCOS/FISCO-BCOS#1060]
在实际应用过程中，每次部署合约都需要启动控制台，然后手动输入deploy [contract-name]才能部署合约，是否有可以直接在shell脚本中调用的部署合约命令，来达到自动化形式

**Comment by JimmyShi22** [comment]
**常规做法**
在实际应用中是通过java代码实现的，先将合约转换成java代码，java代码里有deploy函数，直接调用即可。
参考：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html
实现举例：https://github.com/FISCO-BCOS/web3sdk/blob/37988382ab2b4eda4a9688c4a121f98113e9a667/src/test/java/org/fisco/bcos/channel/test/contract/PerformanceOk.java#L80


**简单做法**
在脚本中启动控制台，并写入调用控制台的指令
``` shell
./start.sh <<EOF
getBlockNumber
deploy HelloWorld
EOF
