### ISSUE TITLE
关于：基于DAG的并行交易执行引擎

### ISSUE THREAD

**Issue by bglmmz** [FISCO-BCOS/FISCO-BCOS#1167]
看了”基于DAG的并行交易执行引擎“，有个问题，
其中讲到构建DAG，那么，如果有如下交易列表：
A->B
B->A
C->D
...
那么这个DAG图该如何表示？
即，如何解决有环情况下的并行执行？

**Comment by JimmyShi22** [comment]
A -> B 先
B -> A 后
原则：存在互斥的交易，保证其执行先后顺序与区块中的先后顺序一致。

**Comment by JimmyShi22** [comment]
一笔交易是DAG中的一个节点，即：
tx0: A -> B 是一个节点
tx1: B -> C 是另一个节点
DAG图：
tx0 -> tx1
