### ISSUE TITLE
编译错误：error: catching polymorphic type ‘class std::exception’ by value [-Werror=catch-value=]

### ISSUE THREAD

**Issue by zsz8586343** [FISCO-BCOS/FISCO-BCOS#1173]
你好，Ubuntu 18  下编译出错：

2019-11-15 编译源码出错，错误信息如下：

[[ 97%] Built target eventfilter
Scanning dependencies of target initializer
[ 98%] Building CXX object libinitializer/CMakeFiles/initializer.dir/BoostLogInitializer.cpp.o
[ 98%] Building CXX object libinitializer/CMakeFiles/initializer.dir/GlobalConfigureInitializer.cpp.o
[ 99%] Building CXX object libinitializer/CMakeFiles/initializer.dir/Initializer.cpp.o
[ 99%] Building CXX object libinitializer/CMakeFiles/initializer.dir/LedgerInitializer.cpp.o
[ 99%] Building CXX object libinitializer/CMakeFiles/initializer.dir/P2PInitializer.cpp.o
[100%] Building CXX object libinitializer/CMakeFiles/initializer.dir/RPCInitializer.cpp.o
[100%] Building CXX object libinitializer/CMakeFiles/initializer.dir/SecureInitializer.cpp.o
[100%] Linking CXX static library libinitializer.a
[100%] Built target initializer
Scanning dependencies of target fisco-bcos
[100%] Building CXX object fisco-bcos/main/CMakeFiles/fisco-bcos.dir/main.cpp.o
In file included from /~/~/app/FISCO-BCOS/FISCO-BCOS/fisco-bcos/main/main.cpp:25:
/~/~/app/FISCO-BCOS/FISCO-BCOS/libdevcore/FileSignal.h: In static member function ‘static void dev::FileSignal::callIfFileExist(const string&, std::function<void()>)’:
/~/~/app/FISCO-BCOS/FISCO-BCOS/libdevcore/FileSignal.h:51:31: error: catching polymorphic type ‘class std::exception’ by value [-Werror=catch-value=]
         catch (std::exception _e)
                               ^~
cc1plus: all warnings being treated as errors
make[2]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/build.make:63：fisco-bcos/main/CMakeFiles/fisco-bcos.dir/main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2417：fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] 错误 2
make: *** [Makefile:152：all] 错误 2

**Comment by JimmyShi22** [comment]
编译器把warning当成错误了。编译时设置一下参数，忽略告警

**Comment by zsz8586343** [comment]
OK 问题解决。
