### ISSUE TITLE
控制台始终连不上

### ISSUE THREAD

**Issue by zzzgd** [FISCO-BCOS/FISCO-BCOS#1175]
jdk是java8_231的, 联盟链也是按照文档https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html#fisco-bcos
来搭建的.就是卡在控制台这里了.是什么原因啊?本机127.0.0.0, 端口20200 , 都是按教程一步步来的..
![image](https://user-images.githubusercontent.com/35446203/68993364-32efd200-08b2-11ea-9af1-38cde1a85e58.png)
![image](https://user-images.githubusercontent.com/35446203/68993515-ef966300-08b3-11ea-9997-a1d44a5bf161.png)

**Comment by zzzgd** [comment]
![image](https://user-images.githubusercontent.com/35446203/68996108-9557cb00-08d0-11ea-92f1-843326701994.png)

**Comment by zzzgd** [comment]
我试了百度云,腾讯云,centos7都不行,结果在我国外的vps也是centos7倒是可以了.看了下openssl版本都是1.0.2以上

**Comment by JimmyShi22** [comment]
请参考此行修改一下start.sh脚本
https://github.com/FISCO-BCOS/console/blob/5f9f6c8d65abf658a1864535ece62cd6817079de/tools/start.sh#L69
``` shell
   java -Djdk.tls.namedGroups="secp256k1" -cp "apps/*:conf/:lib/*:classes/:accounts/" console.ConsoleClient $@
```

**Comment by zzzgd** [comment]
> 请参考此行修改一下start.sh脚本
> https://github.com/FISCO-BCOS/console/blob/5f9f6c8d65abf658a1864535ece62cd6817079de/tools/start.sh#L69
> 
> ```shell
>    java -Djdk.tls.namedGroups="secp256k1" -cp "apps/*:conf/:lib/*:classes/:accounts/" console.ConsoleClient $@
> ```

昨天是试了三台服务器,其中一个不知道为什么就可以,然后把可以的那台压缩拷贝到其他两台,其他两台解压也能正常运行了.
而且我看了下我的start.sh脚本就是这样子的啊

在昨天解压后能正常运行的服务器上删除console,重新用脚本从git下载,是正常运行的.
