### ISSUE TITLE
关于搭建第一个区块链应用的连接不到控制台节点

### ISSUE THREAD

**Issue by Songruixiang** [FISCO-BCOS/FISCO-BCOS#1200]
1、~/fisco/console 下执行bash start.sh是可以连到控制台的，教程中的端口也都没被占用，我用的默认配置
2、但是在~/asset-app/dist下去 bash asset_run.sh deploy时就提示我连接不到node，让我检查配置和节点状态，中间我第一步的控制台一直是开启的
我的xml中
<property name="connectionsStr">
    <list>
           <value>127.0.0.1:20200</value>
    </list>
</property>

**Comment by JimmyShi22** [comment]
尝试修改脚本里调用java的命令，加上` -Djdk.tls.namedGroups="secp256k1"`
如：
`java -Djdk.tls.namedGroups="secp256k1" -cp  XXXX XXXXXXX`

**Comment by Songruixiang** [comment]
repositories {
    maven {
        url "http://maven.aliyun.com/nexus/content/groups/public/"
    }
    maven { url "https://dl.bintray.com/ethereum/maven/" }
//    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    mavenCentral()
}
我找到问题了，我curl 下载下来的项目中的gradle中的配置多一个Maven的url，我把这个注释了，重新gradle了下，然后再上合约就成功了，虽然不知道为啥
