### ISSUE TITLE
机构节点证书管理问题

### ISSUE THREAD

**Issue by XiaoBinNumberOne** [FISCO-BCOS/FISCO-BCOS#1207]
假如现在有个机构D，我想发放的证书设置一个有效期半年，半年后证书将会失效，如何处理呢？

**Comment by HaoXuan40404** [comment]
可以参考一下文档进行证书续期操作
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/certificates.html#id10

**Comment by XiaoBinNumberOne** [comment]
> 可以参考一下文档进行证书续期操作
> https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/certificates.html#id10

这个是链证书过期以后的续签，我是想让某个机构有个证书过期怎么弄呢

**Comment by HaoXuan40404** [comment]
机构证书续期可以只按照续期机构证书的操作进行
