### ISSUE TITLE
异常用户和异常合约问题

### ISSUE THREAD

**Issue by TXZdream** [FISCO-BCOS/FISCO-BCOS#1210]
我在使用go的sdk做实验时，发现我在代码里面生成的用户都是异常用户，这个用户有什么办法变成合法用户呢？相关的说明在哪里可以看到呢？

**Comment by bxq2011hust** [comment]
请问是go-sdk的dev分支吗？你所说的异常用户是指什么呢？能提供一些报错信息吗

**Comment by TXZdream** [comment]
> 请问是go-sdk的dev分支吗？你所说的异常用户是指什么呢？能提供一些报错信息吗

是的，异常用户是在web界面看到的，报错信息我晚点给你回复

**Comment by TXZdream** [comment]
> 请问是go-sdk的dev分支吗？你所说的异常用户是指什么呢？能提供一些报错信息吗

异常用户指的是在web端看到的，我每次在代码里面新建用户，该用户都是异常用户

**Comment by bxq2011hust** [comment]
> > 请问是go-sdk的dev分支吗？你所说的异常用户是指什么呢？能提供一些报错信息吗
> 
> 异常用户指的是在web端看到的，我每次在代码里面新建用户，该用户都是异常用户

您所说的web界面是指什么呢？和go-sdk有什么关联吗？

**Comment by TaroYoVen** [comment]
异常用户其实是相对于webase web端来说的，本身只要是来源合法，只需要作为公钥用户导入到web就可以成为正常的用户了

**Comment by TaroYoVen** [comment]
> > 请问是go-sdk的dev分支吗？你所说的异常用户是指什么呢？能提供一些报错信息吗
> 
> 异常用户指的是在web端看到的，我每次在代码里面新建用户，该用户都是异常用户



> 异常用户其实是相对于webase web端来说的，本身只要是来源合法，只需要作为公钥用户导入到web就可以成为正常的用户了

异常合约也是相同的道理，建议去看下WeBASE的源码，可以知道他们是怎么处理异常合约，异常用户和异常交易的
