### ISSUE TITLE
gen_node_cert.sh 生成节点证书失败

### ISSUE THREAD

**Issue by sforce100** [FISCO-BCOS/FISCO-BCOS#1261]
FISCO-BCOS：版本2.1.0
平台：OSX 10.14.1
openssl：LibreSSL 2.6.4

按文档操作  https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/build_chain.html

运行命令： bash gen_node_cert.sh -c nodes/cert/agency -o newNode

unknown option -force_pubkey
usage: x509 args
 -inform arg     - input format - default PEM (one of DER, NET or PEM)
 -outform arg    - output format - default PEM (one of DER, NET or PEM)
 -keyform arg    - private key format - default PEM
 -CAform arg     - CA format - default PEM

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/tools/gen_node_cert.sh
之前没有支持macOS，现在已经支持了，再试一下

**Comment by sforce100** [comment]
跳过force_pubkey选项也是可以，证书正常生成force_pubkey可有可无。LibreSSL 2.6.4不支持force_pubkey参数。
