### ISSUE TITLE
web3sdk是否有接口支持权限的管理

### ISSUE THREAD

**Issue by sunduozhong** [FISCO-BCOS/FISCO-BCOS#127]
如题，目前的文档都是直接调用babel-node AuthorityManager.js 进行操作，请教一下，我们如何通过web3sdk来对权限的管理，而不是调用babel-node工具和js脚本。
盼复。。。。

**Comment by fisco-dev** [comment]
有的，可参考web3sdk的README   https://github.com/FISCO-BCOS/web3sdk/blob/master/README.md

**Comment by bxq2011hust** [comment]
很久没有回复，看起来问题解决了，先关闭issue，如果没有解决，欢迎再次打开
