### ISSUE TITLE
按照教程开发智能合约不能部署？

### ISSUE THREAD

**Issue by yt7589** [FISCO-BCOS/FISCO-BCOS#1291]
我按照官网上教程“构建第一个区块链应用”[官司网链接](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/sdk_application.html)，可以编译出Cbdc.java文件，证明sol文件语法没有问题。但是使用Asset-app示例工程时（我将该工程改为SpringBoot工程），编译源码也没有问题，运行SpringBoot程序，在运行部署合约代码时报如下错误：
deploy Cbdc contract failed, error message is  Transaction has failed with status: 0x16. Gas used: 282308. (not-enough gas?)
通过跟踪，是在运行下面代码时出错：
Cbdc cbdc = Cbdc.deploy(web3j, credentials, new StaticGasProvider(gasPrice, gasLimit)).send();
请问这个错误怎么解决？
另外，将Cbdc.sol放到console/contract/solidity目录下，在console命令行运行部署命令：
deploy Cbdc
会报如下错误：
revert instruction .gas used: 282308

**Comment by ywy2090** [comment]
这个错误说明构造函数执行有问题，看是否方便把合约贴出来。
