### ISSUE TITLE
启动console出现Input stream not contain valid certificates错误提示

### ISSUE THREAD

**Issue by halyhuang** [FISCO-BCOS/FISCO-BCOS#1299]
cd ~/fisco/console && bash start.sh
Failed to init the console！ Failed to initialize the client-side SSLContext: Input stream not contain valid certificates.

**Comment by brycecheung** [comment]
我也出现了这个问题，是用国密版搭建的吗

**Comment by ywy2090** [comment]
1. 参考文档，要确保拷贝的数据是搭建的对应区块链sdk目录下的证书 
2. CentOS下使用OpenJDK会有这个问题，将OpenJDK替换为OracleJDK，下载链接: https://www.oracle.com/technetwork/java/javase/downloads/index.html

**Comment by ywy2090** [comment]
@brycecheung @

> cd ~/fisco/console && bash start.sh
> Failed to init the console！ Failed to initialize the client-side SSLContext: Input stream not contain valid certificates.


> 我也出现了这个问题，是用国密版搭建的吗

参考下面的留言给出的解决方案。

**Comment by brycecheung** [comment]
> @brycecheung @
> 
> > cd ~/fisco/console && bash start.sh
> > Failed to init the console！ Failed to initialize the client-side SSLContext: Input stream not contain valid certificates.
> 
> > 我也出现了这个问题，是用国密版搭建的吗
> 
> 参考上面的留言给出的解决方案。

官方的openjdk和OracleJDK的几个版本我都试了，控制台还是启动报这个错误。我是企业版部署工具搭建的，节点搭建完毕后是没有SDK目录的。在下载控制台后，控制台自带了一份SDK证书，然后启动失败
