### ISSUE TITLE
there are no files below keystore/

### ISSUE THREAD

**Issue by rainysiu** [FISCO-BCOS/FISCO-BCOS#13]
mkdir -p /mydata/nodedata-1/
mkdir -p /mydata/nodedata-1/data/ #存放节点的各种文件
mkdir -p /mydata/nodedata-1/log/ #存放日志
mkdir -p /mydata/nodedata-1/keystore/ #存放账户秘钥

#拷贝相关文件
cd /mydata/FISCO-BCOS/ 
cp genesis.json config.json log.conf start.sh stop.sh /mydata/nodedata-1/

**Comment by JimmyShi22** [comment]
这里没问题，继续往下走吧
