### ISSUE TITLE
关于基于DAG的并行合约性能的建议

### ISSUE THREAD

**Issue by HachikoT** [FISCO-BCOS/FISCO-BCOS#1305]
在测试过程中，发现如果交易全部都是互斥的（可以并行执行），那么平均每条交易的执行时间会随着区块的大小增加，比如`setSystemConfigByKey tx_count_limit`设置为1000和5000，这时平均每条区块的平均执行时间executePerTx可能会增加几倍。
看了DAG的源码，发现如果连续所有的交易都是并行的，那么每次判断是否互斥都会花费logn的时间，那么总的复杂度就是nlogn了。
有没有可能限制一下最大连续的互斥交易数，比如1000，超过这个数就清空当前所有互斥条件，把它当作一个不能并行的合约，然后再继续判断新的互斥关系。
目前只是基于测试的结果来推测可能是连续互斥交易太多导致速度变慢，作为一个建议参考哈，如有错误希望得到指正。

**Comment by wheatli** [comment]
It's a good idea~
