### ISSUE TITLE
1.3.1版本 新加的节点nodeid需要添加在initMinerNodes中吗？

### ISSUE THREAD

**Issue by jiaolinfeng** [FISCO-BCOS/FISCO-BCOS#141]
按照[操作手册](https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/doc/manual)一步一步安装，在添加第二个节点的时候，把genesis.json直接从创世节点复制，其中的initMinerNodes中只有创世节点的nodeId。启动第二个节点时，无法连接创世节点，ERROR级别错误信息：resetConfig Fail: can't find myself id, stop sealing
我用[一键部署](https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/sample)双机四节点，发现能连接上，查看配置发现节点id都被添加在initMinerNodes中了。
请问是需要节点id是需要手动添加吗？

**Comment by zbj741** [comment]
不需要
