### ISSUE TITLE
Caliper压力测试指南中合约无法安装的问题

### ISSUE THREAD

**Issue by ZhangBobby** [FISCO-BCOS/FISCO-BCOS#1411]
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/caliper.html，指引中执行到2.3 快速体验FISCO BCOS基准测试时，报错如下：
![issue](https://user-images.githubusercontent.com/27805165/76405019-7a9aec00-63c2-11ea-9e56-7b2db3c8c686.jpg)
**### Depolying error: Error: Cannot convert string to buffer. toBuffer only supports 0x-prefixed hex strings and this string was given: 075e2a924b9e43919426589e55a0ec83**
不知道改如何解决，还望赐教！
caliper-cli 版本号：0.2.0

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1248

**Comment by ZhangBobby** [comment]
> 请参考一下 #1248

多谢，方法可行，问题已解决

**Comment by PureRaidenCloud** [comment]
现在好像出现了一个新问题，编译合约通过了，但是部署的时候卡主了。没有任何输出，试了好多次包括换了新服务器也这样
![issue1](https://user-images.githubusercontent.com/63286100/99476757-1a663c00-298c-11eb-9cd2-71086c224ffa.PNG)
![issue2](https://user-images.githubusercontent.com/63286100/99476765-1f2af000-298c-11eb-8119-6513aced7fdf.PNG)
我看了下代码好像是语句await deployPromise阻塞了执行不下去。请问下怎么解决呢？
