### ISSUE TITLE
cannot access ‘scripts/install_deps.sh’: No such file or directory

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/FISCO-BCOS#143]
cannot access ‘scripts/install_deps.sh’: No such file or directory

[10/15] lodash@^4.17.4 installed at node_modules/_lodash@4.17.10@lodash
[npminstall:get] retry GET https://registry.npm.taobao.org/core-js after 100ms, retry left 4, error: SyntaxError: Unexpected end of JSON input
fsevents@1.2.4 download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://cdn.npm.taobao.org/dist/fsevents"}
platform unsupported chokidar@1.7.0 ? fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)
[11/15] chokidar@^1.6.1 installed at node_modules/_chokidar@1.7.0@chokidar

**Comment by JimmyShi22** [comment]
把scripts/install_deps.sh脚本dos2unix转换成linux格式试试？

**Comment by JimmyShi22** [comment]
是这个文件夹
https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/scripts
确认一下拉取方式，若不行，可直接去release里下载对应版本的压缩包

**Comment by cristicmf** [comment]
所有的操作就是直接去release里下载对应版本的压缩包

**Comment by JimmyShi22** [comment]
1.3.1的tar包的MD5值：869948c6bc729b3ee15c078a84502a42
估计是包下载时没下全

**Comment by cristicmf** [comment]
thx

**Comment by bxq2011hust** [comment]
看起来问题解决了，关闭issue。如果还有问题，欢迎随时再次联系
