### ISSUE TITLE
I cannot find that(fisco-solc-centos) file  

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/FISCO-BCOS#145]
[app@VM_105_92_centos FISCO-BCOS]$ cp fisco-solc-centos  /usr/bin/fisco-solc
cp: cannot stat ‘fisco-solc-centos’: No such file or directory

[app@VM_105_92_centos FISCO-BCOS]$ cp fisco-solc-centos  /usr/bin/fisco-solc
cp: cannot stat ‘fisco-solc-centos’: No such file or directory
[app@VM_105_92_centos FISCO-BCOS]$ pwd
/home/app/workspace/cc-go/FISCO-BCOS
[app@VM_105_92_centos FISCO-BCOS]$

**Comment by JimmyShi22** [comment]
fisco-solc-centos在这里：https://github.com/FISCO-BCOS/fisco-solc/blob/master/fisco-solc-centos

**Comment by cristicmf** [comment]
thx

**Comment by bxq2011hust** [comment]
It seems problem is solved, I will close this issue. If there is any other question, fell free to reopen.
