### ISSUE TITLE
macOS部署FISCO链路径缺少config.ini和start.h的解决办法

### ISSUE THREAD

**Issue by lovelessbiu** [FISCO-BCOS/FISCO-BCOS#1466]
用macOS Catalina 10.15.3系统部署FISCO链，按照教程步骤做，发现fisco文件夹下缺少一些config.ini和start.h，并导致启动节点失败。
主要是因为macOS自带的是curl和libressl，libressl是openssl的一个安全分支，与openssl的指令还是有区别，需要通过homebrew再安装一个旧版的openssl，就可以成功布置啦。

**Comment by bxq2011hust** [comment]
是的，文档安装的第一步[准备环境](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/installation.html#id2)中就有提到
```bash
brew install openssl curl
```
