### ISSUE TITLE
部署架构里面DMZ区的前置系统是部署什么软件？

### ISSUE THREAD

**Issue by kixiong** [FISCO-BCOS/FISCO-BCOS#152]
部署架构里面DMZ区的前置系统是部署什么软件？
在代码中没有看到相关的模块。

**Comment by JimmyShi22** [comment]
目前开源的代码不涉及此部分内容

**Comment by kixiong** [comment]
区块链前置还没有开源么？那对于我们的部署该怎么办？

**Comment by wheatli** [comment]
@kixiong 前置不是每一个业务搭建的必须模块，如果没有数据隔离需求的话，可以由SDK直接连到区块链节点。我们提供SDK可以连接到区块链节点，SDK可以由业务模块调用。
