### ISSUE TITLE
非上帝节点，启动立马退出

### ISSUE THREAD

**Issue by liuyuanting1209** [FISCO-BCOS/FISCO-BCOS#156]
非上帝节点，启动立马退出。 error log 里面没有任何信息。  上帝节点没问题

**Comment by JimmyShi22** [comment]
是说的非创世节点吗？
检查一下config.json文件内容，看看是不是和创世节点的配置文件重复了

**Comment by HaoXuan40404** [comment]
是节点入网的时候出现的问题吗

**Comment by bxq2011hust** [comment]
长时间没有回复，先关闭。如果没有解决，欢迎随时联系
