### ISSUE TITLE
开源精神

### ISSUE THREAD

**Issue by huahuayu** [FISCO-BCOS/FISCO-BCOS#1609]
我刚接触bcos，但是看得出bcos明摆着是base on ethereum改的，那为什么上传源码的时候不fork ethereum再改呢，readme里面也没有提，仿佛是自己新写的代码一样，不厚道啊，有损开源精神

**Comment by huahuayu** [comment]
@cyjseagull @JimmyShi22 @bxq2011hust

**Comment by wheatli** [comment]
FISCO BCOS fork自BCOS，BCOS最初是从以太坊继承而来。FISCO BCOS有关以太坊的代码都保留了其copyright，但是大部分核心代码都是自研的，可以通过阅读源码进一步了解
