### ISSUE TITLE
文档错别字

### ISSUE THREAD

**Issue by huahuayu** [FISCO-BCOS/FISCO-BCOS#1618]
[此处文档](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.5.0/docs/manual/build_chain.html#id13)有错别字，应该为某`些`不是某`下`  

![image](https://user-images.githubusercontent.com/1725060/83841839-38204b80-a734-11ea-88c6-015991e972d4.png)

**Comment by wheatli** [comment]
感谢指出错误，欢迎提PR修复

**Comment by huahuayu** [comment]
提了pr了 https://github.com/FISCO-BCOS/FISCO-BCOS-DOC/pull/877
