### ISSUE TITLE
关于分布式存储的问题

### ISSUE THREAD

**Issue by dengchengH** [FISCO-BCOS/FISCO-BCOS#1621]
本人在使用ubuntu18.04版本借助mysql实现分布式存储过程时，总是提示access denied for user ‘root’@‘localhost’，过程是按照文档进行配置的，mysql设置为对本机所有用户开发权限。想请教大家一下，具体关于mysql分布式存储的实现过程有没有更加详细的步骤可以参考，谢谢大家

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1382
