### ISSUE TITLE
文档注释描述不准确

### ISSUE THREAD

**Issue by huahuayu** [FISCO-BCOS/FISCO-BCOS#1624]
[此处](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.4.0/docs/manual/group_use_cases.html#id6
)文档的代码注释似乎有点小问题，please check.

![image](https://user-images.githubusercontent.com/1725060/83986041-ff6bb680-a96d-11ea-8fc2-578d7c1d50f6.png)

**Comment by bxq2011hust** [comment]
这里描述应该是拷贝SDK证书到控制台目录，欢迎提PR修复

**Comment by huahuayu** [comment]
已提pr https://github.com/FISCO-BCOS/FISCO-BCOS-DOC/pull/878

**Comment by bxq2011hust** [comment]
> 已提pr [FISCO-BCOS/FISCO-BCOS-DOC#878](https://github.com/FISCO-BCOS/FISCO-BCOS-DOC/pull/878)

由于文档release-2.5.0的分支已经合入，导致这个PR被自动关闭了，我无法重新打开，需要您往[文档](https://github.com/FISCO-BCOS/FISCO-BCOS-DOC)的release-2分支提交修复的PR。非常抱歉
