### ISSUE TITLE
【优化建议】国密版配置简化

### ISSUE THREAD

**Issue by huahuayu** [FISCO-BCOS/FISCO-BCOS#1631]
根据文档[配置国密版控制台](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.4.0/docs/manual/console.html#id11) 国密版console目前需要两个步骤来配置：

1.  打开国密开关
```
<bean id="encryptType" class="org.fisco.bcos.web3j.crypto.EncryptType">
    <!-- encryptType值设置为1，打开国密开关 -->
    <constructor-arg value="1"/> <!-- 0:standard 1:guomi -->
</bean>
```
2. 替换国密编译包
```
# 下载solcJ-all-0.4.25-gm.jar放在console目录下
$ curl -LO https://github.com/FISCO-BCOS/LargeFiles/raw/master/tools/solcj/solcJ-all-0.4.25-gm.jar
# 替换Jar包
$ bash replace_solc_jar.sh solcJ-all-0.4.25-gm.jar
```

能不能把第二步优化掉。

将支持的`solcj-4.25.jar`、`solcj-5.2.jar`以及他们的国密版本都放在`console/lib`目录下，用户只需要在xml里面打开国密开关或选择版本即可。

为什么额外要用户去替换jar包这种操作呢，都放在lib里面会有什么影响呢，又没有重名。

只是建议，大佬们可以分析下是否可行。

我提这个建议因为在这个上面花费过不必要的时间，请参考 https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1626

**Comment by wheatli** [comment]
很好的建议，后续考虑升级支持编译同时支持 两种版本，用户无需在编译前选择，只需要在编译后选择结果
