### ISSUE TITLE
mysql启用表压缩功能

### ISSUE THREAD

**Issue by HachikoT** [FISCO-BCOS/FISCO-BCOS#1661]
问题：
rocksdb默认用snappy压缩数据
mysql没有压缩数据，而且存储16进制数据
导致mysql占用的存储资源是rocksdb的十多倍。这一点会使使用者感到困惑，并且hash2block表存储区块数据占用大量空间，而其数据又比较稀疏，是能进行很好的压缩的

方案：
innodb引擎也是支持压缩表数据的，建议创建mysql表时指定ROW_FORMAT=COMPRESSED ，对表数据进行压缩，因为使用mysql的节点一般都是观察者节点对共识效率也不影响

**Comment by bxq2011hust** [comment]
非常好的建议，我们会在下个版本中考虑这个优化

**Comment by cyjseagull** [comment]
FISCO BCOS v2.6.0版本已经启用了mysql压缩功能，可以升级到2.6.0版本。
