### ISSUE TITLE
The bug in the process of Make

### ISSUE THREAD

**Issue by SabakGaara** [FISCO-BCOS/FISCO-BCOS#1662]
FISCO-BCOS/deps/src/rocksdb/db/version_edit.h:55:19: note: because 'rocksdb::FileDescriptor' has user-provided 'rocksdb::FileDescriptor& rocksdb::FileDescriptor::operator=(const rocksdb::FileDescriptor&)'
   55 |   FileDescriptor& operator=(const FileDescriptor& fd) {
      |                   ^~~~~~~~
In file included from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/string:40,
                 from /home/liyue/concurrency/FISCO-2.2/FISCO-BCOS/deps/src/rocksdb/db/builder.h:9,
                 from /home/liyue/concurrency/FISCO-2.2/FISCO-BCOS/deps/src/rocksdb/db/builder.cc:10:
/usr/include/c++/9/bits/stl_pair.h:312:51: note: synthesized method 'rocksdb::FileMetaData::FileMetaData(const rocksdb::FileMetaData&)' first required here
  312 |        : first(std::forward<_U1>(__x)), second(__y) { }
      |                                                   ^
cc1plus: all warnings being treated as errors
make[5]: *** [CMakeFiles/rocksdb.dir/build.make:102: CMakeFiles/rocksdb.dir/db/builder.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:78: CMakeFiles/rocksdb.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2

**Environment**
 - Ubuntu 20.04
 - FISCO BCOS Version [e.g. 2.2.0]

**Comment by wheatli** [comment]
What's the version of GCC?

**Comment by bxq2011hust** [comment]
Ubuntu 20.04 is not supported yet. 
Thank you for the report! We are working on the issues and we will fix them in one of the future releases.
