### ISSUE TITLE
压测遇到 合约无法安装的问题 secp256k1.sign is not a function

### ISSUE THREAD

**Issue by linzh17** [FISCO-BCOS/FISCO-BCOS#1721]
**Describe the bug**
![2020-07-22 16-29-09 的屏幕截图](https://user-images.githubusercontent.com/26267025/88153947-b2e7ec00-cc38-11ea-852a-fa78fc4e2133.png)

**Comment by Xubin-source** [comment]
I also meet this problem.have you solved it ?

**Comment by linzh17** [comment]
> I also meet this problem.have you solved it ?

no ，I tried to change secp256k1.sign to secp256k1.ecdsaSign, but a new problem arose

**Comment by lastsongforu** [comment]
is it because of web3SDK problem ?

**Comment by linzh17** [comment]
> is it because of web3SDK problem ?

which version of web3sdk are you using?

**Comment by vita-dounai** [comment]
@linzh17 ，非常抱歉，这段时间事情较多所以对Issue区关注较少，没能及时答复你的问题。目前我这边着实没能复现你们描述的问题，需要进一步和你确认下复现的步骤和环境。能否加一下我们的技术微信群，这样沟通起来比较快，加入方式见我们文档底部的二维码。

**Comment by vita-dounai** [comment]
非常抱歉，这是一个愚蠢的bug，指定secp256k1依赖包时版本限制没写对，导致在绑定时时自动安装了4.0版本的secp256k1包，但是最新的4.0的包API全部变了，导致执行出错。

有一个临时的解决方案，进入node_modules/@hyperledger/caliper-fisco-bcos目录，编辑该目录下的package.json文件，在"dependencies"中添加一项"secp256k1": "^3.8.0"，随后在该目录下执行npm i，更新完成后测试程序就能启动了。

**Comment by wenlinlee** [comment]
![image](https://user-images.githubusercontent.com/28520306/105964005-9c758e00-60bc-11eb-8cc0-f44a9cf52b40.png)
所有caliper针对fisco-bco的修改都改了，之前也跑通了，但昨天开始出现了这个问题，请问是什么原因

**Comment by linzh17** [comment]
> ![image](https://user-images.githubusercontent.com/28520306/105964005-9c758e00-60bc-11eb-8cc0-f44a9cf52b40.png)
> 所有caliper针对fisco-bco的修改都改了，之前也跑通了，但昨天开始出现了这个问题，请问是什么原因
参考上述vita-dounai  的解决方案 但在最外层的目录的的package.json文件，在"dependencies"中添加一项"secp256k1": "^3.8.0"，随后在该目录下执行npm i，

**Comment by linzh17** [comment]
> ![image](https://user-images.githubusercontent.com/28520306/105964005-9c758e00-60bc-11eb-8cc0-f44a9cf52b40.png)
> 所有caliper针对fisco-bco的修改都改了，之前也跑通了，但昨天开始出现了这个问题，请问是什么原因

没有遇到过这个问题 错误里面有timeout 可能是区块链节点 没有正常搭建起来导致

**Comment by sixwenxin** [comment]
> > ![image](https://user-images.githubusercontent.com/28520306/105964005-9c758e00-60bc-11eb-8cc0-f44a9cf52b40.png)
> > 所有caliper针对fisco-bco的修改都改了，之前也跑通了，但昨天开始出现了这个问题，请问是什么原因
> 
> 没有遇到过这个问题 错误里面有timeout 可能是区块链节点 没有正常搭建起来导致

请问你这个问题解决了吗  我也遇到这个问题了 第一次运行卡了 重新启动了一下虚拟机 就出现这个情况了
