### ISSUE TITLE
Typererror:secp256.sign is not a function 

### ISSUE THREAD

**Issue by Xubin-source** [FISCO-BCOS/FISCO-BCOS#1723]
![图片](https://user-images.githubusercontent.com/56347756/88469349-4feda200-cf23-11ea-92ab-31f731e78310.png)

**Comment by vita-dounai** [comment]
好的，我们跟进一下这个问题

**Comment by vita-dounai** [comment]
这是一个bug，解决办法请参考https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1721
