### ISSUE TITLE
请问分布式存储和MPT比较，存储空间有上面改进吗？

### ISSUE THREAD

**Issue by syntrust** [FISCO-BCOS/FISCO-BCOS#1725]
StorageState性能大约是MPTState的两倍。那么存储空间呢？
相关的性能测试有没有具体的测试数据和报告呢？谢谢。

**Comment by Beyond-simplechain** [comment]
当然减小了，不存历史账户state了，每次交易更改都会直接更新StorageState中的账户table

**Comment by syntrust** [comment]
理论上的确如此。那么有没有实际的数据比较呢，大概是个什么数量级？
还有，去掉MPT的索引功能，在账户数很多的情况下，直接用地址去kv库里查询会不会更慢呢？

**Comment by bxq2011hust** [comment]
> 理论上的确如此。那么有没有实际的数据比较呢，大概是个什么数量级？
> 还有，去掉MPT的索引功能，在账户数很多的情况下，直接用地址去kv库里查询会不会更慢呢？

不会更慢的，StorageState性能是更高，去掉历史这个降低的量取决于历史的量的大小。之前简单测试从mpt改storagestate，保存历史存储的数据量就会降低不少，具体的数据有点不记得了，你可以自己测试。

**Comment by syntrust** [comment]
Thanks alot!
