### ISSUE TITLE
你好。请问bcos安装在k8s环境中。使用service相互联通。会有不间断连接报错问题

### ISSUE THREAD

**Issue by xricky** [FISCO-BCOS/FISCO-BCOS#1731]
bcos安装在k8s环境中。使用service相互联通。偶有连接报错。
再有请问p2p网络通信有没有端口范围

**Comment by bxq2011hust** [comment]
> bcos安装在k8s环境中。使用service相互联通。偶有连接报错。
> 再有请问p2p网络通信有没有端口范围

只要共识正常即可，连接断开会自动尝试重连。
p2p的端口是在节点config.ini中配置，请参考[这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/configuration.html#p2p)
