### ISSUE TITLE
Console maybe not be initialized correctly with specific version of java on macOS catalina

### ISSUE THREAD

**Issue by SeavantUUz** [FISCO-BCOS/FISCO-BCOS#1736]
**Describe the bug**
After the node has been started,  following tutorial until should input `bash start.sh` and then it failed, reported message like 

```
Failed to init the console！  Failed to connect to nodes: [ ssl handshake failed:/127.0.0.1:20201]
```

Below is what displayed in log:

```
[INFO] [2020-08-06 17:09:14] ChannelConnections.init(450) |  all connections: [ConnectionInfo{host='127.0.0.1', port=20201}]
[ERROR] [2020-08-06 17:09:15] ChannelConnections.startConnect(563) |  all connections have failed, [ ssl handshake failed:/127.0.0.1:20201]
[ERROR] [2020-08-06 17:09:15] Service.run(381) |  service init failed, error message:  Failed to connect to nodes: [ ssl handshake failed:/127.0.0.1:20201], error:
java.lang.RuntimeException:  Failed to connect to nodes: [ ssl handshake failed:/127.0.0.1:20201]
	at org.fisco.bcos.channel.handler.ChannelConnections.startConnect(ChannelConnections.java:565)
	at org.fisco.bcos.channel.client.Service.run(Service.java:327)
	at console.ConsoleInitializer.init(ConsoleInitializer.java:121)
	at console.ConsoleClient.main(ConsoleClient.java:45)
[ERROR] [2020-08-06 17:09:15] ChannelHandler.userEventTriggered(66) |  handshake failed, host: 127.0.0.1, port: 20201, message: null, cause: {}
```

Finally, I realized that my Java version causes this problem, it is 14.0.2. Unfortunately, this version is the default and latest version of java for macOS users who install java by homebrew.

To fix this problem, you have to degrade to java9, by run

```
brew tap adoptopenjdk/openjdk
brew cask install adoptopenjdk9
```

And it looks good for me.

I hope you could investigate this compatibility problem, it makes confusion.

Thx.

**Expected behavior**
Console can be initialized successful.

**Environment (please complete the following information):**
 - OS: [macOS Catalina 10.15.6 (19G73)]
 - FISCO BCOS Version [2.5.0]
 - Java Version [14.0.2]

**Comment by bxq2011hust** [comment]
It seems Java 14 is not supported yet @ywy2090

**Comment by ywy2090** [comment]
https://github.com/FISCO-BCOS/web3sdk/tree/dev
