### ISSUE TITLE
TypeError: Configuration.setConfig is not a function

### ISSUE THREAD

**Issue by Gavin1216** [FISCO-BCOS/FISCO-BCOS#1746]
我在根据官网教程，使用nodejs sdk 开发时，文档说第一步是：
<<<使用服务之前，首先需要初始化全局的Configuration对象，用以为各个服务提供必要的配置信息。Configuration对象位于nodejs-sdk/packages/api/common/configuration.js>>>
具体操作即：
const Configuration = require('./nodejs-sdk/packages/api/common/configuration').Configuration;
Configuration.setConfig(path.join(__dirname, args.config));
但我遇到了：
TypeError: Configuration.setConfig is not a function的报错。

检查了configuration.js文件，发现Configuration这个类确实没有setConfig的function，请问，怎么解决？

**Comment by vita-dounai** [comment]
请参考最新的项目README，你上面引用的描述是0.9.0版本node.js SDK的使用方式。另外，Node.js SDK相关的issue请提交至Node.js SDK项目的issue区。
