### ISSUE TITLE
make出现问题

### ISSUE THREAD

**Issue by Julyuan** [FISCO-BCOS/FISCO-BCOS#175]
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:72: error: undefined reference to 'CRYPTO_set_locking_callback'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:73: error: undefined reference to 'ERR_free_strings'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:74: error: undefined reference to 'EVP_cleanup'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:75: error: undefined reference to 'CRYPTO_cleanup_all_ex_data'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:84: error: undefined reference to 'SSL_COMP_free_compression_methods'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:92: error: undefined reference to 'ENGINE_cleanup'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:72: error: undefined reference to 'CRYPTO_set_locking_callback'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:73: error: undefined reference to 'ERR_free_strings'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:74: error: undefined reference to 'EVP_cleanup'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:75: error: undefined reference to 'CRYPTO_cleanup_all_ex_data'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:84: error: undefined reference to 'SSL_COMP_free_compression_methods'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:92: error: undefined reference to 'ENGINE_cleanup'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:39: error: undefined reference to 'SSL_library_init'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:40: error: undefined reference to 'SSL_load_error_strings'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:41: error: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:44: error: undefined reference to 'CRYPTO_num_locks'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/detail/impl/openssl_init.ipp:47: error: undefined reference to 'CRYPTO_set_locking_callback'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/impl/context.ipp:125: error: undefined reference to 'SSLv23_method'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/impl/context.ipp:128: error: undefined reference to 'SSLv23_client_method'
/mydata/FISCO-BCOS/deps/src/boost/boost/asio/ssl/impl/context.ipp:131: error: undefined reference to 'SSLv23_server_method'
/mydata/FISCO-BCOS/libdevcrypto/Rsa.cpp:66: error: undefined reference to 'CRYPTO_cleanup_all_ex_data'
/mydata/FISCO-BCOS/libdevcrypto/Rsa.cpp:103: error: undefined reference to 'CRYPTO_cleanup_all_ex_data'
collect2: error: ld returned 1 exit status
eth/CMakeFiles/fisco-bcos.dir/build.make:176: recipe for target 'eth/fisco-bcos' failed
make[2]: *** [eth/fisco-bcos] Error 1
CMakeFiles/Makefile2:324: recipe for target 'eth/CMakeFiles/fisco-bcos.dir/all' failed
make[1]: *** [eth/CMakeFiles/fisco-bcos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

make时出现了如下问题
电脑操作系统：Ubuntu 16.04

**Comment by cyjseagull** [comment]
可能是openssl版本不对，也有可能是没清理编译缓存，执行以下脚本试试：
```bash
$ cd FISCO-BCOS
$ sudo rm -rf deps/src/boost
$ sudo rm -rf deps/src/*build && sudo rm -rf deps/src/*stamp
$ chmod a+x build.sh && sudo ./build.sh

```

**Comment by Julyuan** [comment]
执行上述命令出现了同样的报错，这个软件和系统中openssl有关系吗？之前在电脑里还装了gmssl，不知道是不是这个原因

**Comment by cyjseagull** [comment]
那应该是openssl的问题~现在解决了么

**Comment by Julyuan** [comment]
把一些出错的代码段注释掉之后安装没有问题，不过在节点配置的时候有新的问题出现。正在处理

**Comment by pingping1122** [comment]
请问这个问题解决了吗？？？
Ubuntu18.04   make时出错
=========================
Scanning dependencies of target fisco-bcos
[ 99%] Building CXX object fisco-bcos/main/CMakeFiles/fisco-bcos.dir/main.cpp.o
[100%] Linking CXX executable ../../bin/fisco-bcos
/usr/bin/ld.gold: error: cannot find -l...
collect2: error: ld returned 1 exit status
fisco-bcos/main/CMakeFiles/fisco-bcos.dir/build.make:149: recipe for target 'bin/fisco-bcos' failed
make[2]: *** [bin/fisco-bcos] Error 1
CMakeFiles/Makefile2:2224: recipe for target 'fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all' failed
make[1]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pingping1122** [comment]
哦哦   我的问题已解决：
是<working_dir>/FISCO-BCOS/libprecompiled/CMakeLists.txt  添加目标库时填写错误

# 在target_link_libraries命令中增加nlohmann_json目标链接库，其中“...”代表其他目标链接库
target_link_libraries(precompiled PRIVATE ... nlohmann_json)    

# nlohmann_json放置在其他目标链接库后边 ，而不是另起一行target_link_libraries
