### ISSUE TITLE
源码编译错误

### ISSUE THREAD

**Issue by happy-zhangbo** [FISCO-BCOS/FISCO-BCOS#1754]
Ubuntu 18.04
g++ 7.5.0

/root/CLionProjects/fiscobcos/libconsensus/raft/RaftSealer.h:44: 错误: 对‘vtable for dev::consensus::RaftSealer’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
/root/CLionProjects/fiscobcos/libconsensus/rotating_pbft/RotatingPBFTEngine.cpp:517: 错误: 对‘dev::consensus::RPBFTReqCache::selectNodeToRequestTxs(dev::FixedHash<64u> const&, std::shared_ptr<dev::consensus::PBFTMsg>)’未定义的引用
/root/CLionProjects/fiscobcos/libconsensus/rotating_pbft/RotatingPBFTEngine.cpp:633: 错误: 对‘dev::consensus::RPBFTReqCache::updateRawPrepareStatusCache(dev::FixedHash<64u> const&, std::shared_ptr<dev::consensus::PBFTMsg>)’未定义的引用
/root/CLionProjects/fiscobcos/libconsensus/rotating_pbft/RPBFTReqCache.h:37: 错误: 对‘vtable for dev::consensus::RPBFTReqCache’未定义的引用
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function

**Comment by bxq2011hust** [comment]
1. 检查下是否使用了master最新的代码
```bash
git reset --hard && git fetch && git checkout master
```
2. 如果使用WSL子系统，那么使用make编译，子系统并行实现有问题

**Comment by happy-zhangbo** [comment]
> 1. 检查下是否使用了master最新的代码
> 
> ```shell
> git reset --hard && git fetch && git checkout master
> ```
> 
> 1. 如果使用WSL子系统，那么使用make编译，子系统并行实现有问题

已经解决了。 未定义引用的地方因为有几个空格，我删除之后就编译通过了。不确定是master自带的还是在CLion中编码的问题

**Comment by bxq2011hust** [comment]
> > 1. 检查下是否使用了master最新的代码
> > 
> > ```shell
> > git reset --hard && git fetch && git checkout master
> > ```
> > 
> > 
> > 
> > 1. 如果使用WSL子系统，那么使用make编译，子系统并行实现有问题
> 
> 已经解决了。 未定义引用的地方因为有几个空格，我删除之后就编译通过了。不确定是master自带的还是在CLion中编码的问题

源码没问题的，源码都是经过CI编译。那我关闭issue了。
