### ISSUE TITLE
caliper测试自建链问题

### ISSUE THREAD

**Issue by codefish520** [FISCO-BCOS/FISCO-BCOS#1761]
在使用build_chain.sh脚本创建一个4节点1群组的链后，使用gen_node_cert.sh新增节点后，将节点网络配置添加到fisco-bcos.json和docker-compose.yaml后重新启动测试，报了一个这样的错误，求解答。
![1304de155542b46646090a4a07aab9f](https://user-images.githubusercontent.com/54941005/94508904-9cb46880-0245-11eb-97dd-b1e00fd77a06.png)

**Comment by bxq2011hust** [comment]
新增的节点没有加入原有链的群组1，请调用控制台把这个节点加入群组。请详细阅读文档搜索增删节点相关内容

**Comment by MX-A** [comment]
> 在使用build_chain.sh脚本创建一个4节点1群组的链后，使用gen_node_cert.sh新增节点后，将节点网络配置添加到fisco-bcos.json和docker-compose.yaml后重新启动测试，报了一个这样的错误，求解答。
> ![1304de155542b46646090a4a07aab9f](https://user-images.githubusercontent.com/54941005/94508904-9cb46880-0245-11eb-97dd-b1e00fd77a06.png)

老哥，你是咋做的4节点测试啊，官方文档看蒙了

**Comment by Jay1213811** [comment]
有没有大佬能够指导一下啊

**Comment by cyjseagull** [comment]
关于`caliper`的问题，统一参考[这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/stress_testing.html)

**Comment by cyjseagull** [comment]
请参考 #1248
