### ISSUE TITLE
2.6.0部署异常

### ISSUE THREAD

**Issue by leeduckgo** [FISCO-BCOS/FISCO-BCOS#1763]
**Describe the bug:**
解压异常

**To Reproduce**

1. `cd ~/ && git clone https://github.com/FISCO-BCOS/generator.git·

2. `cd ~/generator && bash ./scripts/install.sh`

3. `./generator --download_fisco ./meta --cdn`

**Expected behavior**
```
➜  generator git:(master) ✗ ./generator --download_fisco ./meta --cdn
INFO | ======= USE_CDN ============= ON =======
INFO | Downloading fisco-bcos binary from https://www.fisco.com.cn/cdn/fisco-bcos/releases/download/v2.6.0/fisco-bcos.tar.gz
ERROR |    Decompress fisco-bcos failed, result is
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - FISCO BCOS Version: 2.6.0

**Comment by bxq2011hust** [comment]
看起来是你用的generator是旧版本，旧版本中的链接已经失效，请更新到最新版本
