### ISSUE TITLE
增加无状态的Condition用于查询Table

### ISSUE THREAD

**Issue by eldereal** [FISCO-BCOS/FISCO-BCOS#1775]
使用下面的片段查询Table内容：

Table table = tableFactory.openTable(TABLE_NAME);
Condition condition = table.newCondition();
condition.EQ(FIELD, VALUE);
Entries entries = table.select(name, condition);

由于condition.EQ(FIELD, VALUE)这个语句不是view方法，所以整体查询片段无法放在view方法内。

是否有办法增加无状态的查询条件，用于在view方法内执行查询。

**Comment by bxq2011hust** [comment]
你可以直接修改Table.sol中的condition的声明修改为const

我们会在下个版本更新Table.sol
