### ISSUE TITLE
源代码libprecomplied文件夹下的table.sol，getUInt返回值为int256是否有意为之

### ISSUE THREAD

**Issue by saberdance** [FISCO-BCOS/FISCO-BCOS#1783]
[table.sol](https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/libprecompiled/solidity/Table.sol)
```
27  contract Entry {
28    function getInt(string) public view returns (int256);
29    function getUInt(string) public view returns (int256);
```
如题，table.sol的Entry结构下，接口：
 function getUInt(string) public view returns (int256);
返回值为int256

而console所提供的上层table.sol中，同样的接口：
function getUInt(string memory) public view returns (uint256) {}
返回为uint256

无法理解设计思路，所以斗胆请问是否是笔误

**Comment by bxq2011hust** [comment]
> [table.sol](https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/libprecompiled/solidity/Table.sol)
> 
> ```
> 27  contract Entry {
> 28    function getInt(string) public view returns (int256);
> 29    function getUInt(string) public view returns (int256);
> ```
> 
> 如题，table.sol的Entry结构下，接口：
> function getUInt(string) public view returns (int256);
> 返回值为int256
> 
> 而console所提供的上层table.sol中，同样的接口：
> function getUInt(string memory) public view returns (uint256) {}
> 返回为uint256
> 
> 无法理解设计思路，所以斗胆请问是否是笔误

是笔误，欢迎PR到dev分支修复

**Comment by saberdance** [comment]
> > [table.sol](https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/libprecompiled/solidity/Table.sol)
> > ```
> > 27  contract Entry {
> > 28    function getInt(string) public view returns (int256);
> > 29    function getUInt(string) public view returns (int256);
> > ```
> > 
> > 
> > 如题，table.sol的Entry结构下，接口：
> > function getUInt(string) public view returns (int256);
> > 返回值为int256
> > 而console所提供的上层table.sol中，同样的接口：
> > function getUInt(string memory) public view returns (uint256) {}
> > 返回为uint256
> > 无法理解设计思路，所以斗胆请问是否是笔误
> 
> 是笔误，欢迎PR到dev分支修复

好的，谢谢回复
