### ISSUE TITLE
智能合约语言

### ISSUE THREAD

**Issue by LuffySmile** [FISCO-BCOS/FISCO-BCOS#1787]
通过脚本可以把solidity智能合约转化为java语言的智能合约，但是这样做的原因是什么呢，在文档里也没有看到支持java语言的智能合约，也没有看到使用java语言编写智能合约的教程，而通过java SDK部署智能合约的时候部署的也是abi类型的合约而不是java类型的。

**Comment by bxq2011hust** [comment]
因为需要在你业务系统开发所使用的语言中，调用solidity的合约接口，为了方便调用，所以转换为对应语言的接口
