### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by LuffySmile** [FISCO-BCOS/FISCO-BCOS#1788]
此处描述部分**_被view修饰符修饰的方法一般称为“交易”，而未被修饰的才会称为“查询”_**与图中的描述不一致
![image](https://user-images.githubusercontent.com/34114979/97833771-1e018e00-1d11-11eb-9d7f-7641f59bf484.png)

**Comment by LuffySmile** [comment]
文档地址：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk/assemble_transaction.html#id2

**Comment by dalaocu** [comment]
> 文档地址：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk/assemble_transaction.html#id2

此处笔误。
