### ISSUE TITLE
部署智能合约的权限的设置用msg.sender而不是tx.origin

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/FISCO-BCOS#1792]
我最近在使用FISCO BCOS的时候遇到一个问题。如果我用外部账号A去调用智能合约B的函数C。函数C会创建另一个智能合约D。这个时候FISCO BCOS会有一个限制要求，要求外部账号A必须有部署智能合约的权限。这样一个限制会让我写的智能合约B的易用性大大降低——也就是所有想要调用智能合约B的C函数的外部账号都必须首先授权具有部署智能合约的权限！！！

我觉得这样的设计是不合理的。按照规则，应该是限制智能合约B必须具有部署智能合约的权限而不是限制调用B的C函数的外部账号。外部账号去调用B的C函数其实只是一个使用智能合约的行为，使用智能合约却要求有部署智能合约的权限，这其实是说不过去的。

solidity文档中建议Never use tx.origin for authorization. 会有安全问题。 还是用msg.sender比较好。

**Comment by lilianwen** [comment]
solidity文档中建议Never use tx.origin for authorization.   会有安全问题。  还是用msg.sender比较好。

**Comment by bxq2011hust** [comment]
> 我最近在使用FISCO BCOS的时候遇到一个问题。如果我用外部账号A去调用智能合约B的函数C。函数C会创建另一个智能合约D。这个时候FISCO BCOS会有一个限制要求，要求外部账号A必须有部署智能合约的权限。这样一个限制会让我写的智能合约B的易用性大大降低——也就是所有想要调用智能合约B的C函数的外部账号都必须首先授权具有部署智能合约的权限！！！
> 
> 我觉得这样的设计是不合理的。按照规则，应该是限制智能合约B必须具有部署智能合约的权限而不是限制调用B的C函数的外部账号。外部账号去调用B的C函数其实只是一个使用智能合约的行为，使用智能合约却要求有部署智能合约的权限，这其实是说不过去的。
> 
> solidity文档中建议Never use tx.origin for authorization. 会有安全问题。 还是用msg.sender比较好。

感谢反馈！我个人认为
1. 如果你希望所有人都调用函数C去创建合约，那么你就不应该控制创建合约的权限
2. 如果你不希望所有人调用函数C去创建合约，那么你应该使用有部署合约权限的账号来调用函数C
3. solidity文档中的问题是针对转账ether的问题，和FISCO BCOS的权限控制不相关，参考https://solidity.readthedocs.io/en/v0.6.2/security-considerations.html

**Comment by lideying** [comment]
提问者的问题我也遇到。简单的需求是，我希望用户只能创建指定合约，而非任意合约，实际场景是：调用合约函数C部署合约（如工厂合约）。我觉得解决思路，可以将地址分为合约账户和用户账户，用户账户部署合约的权限是受控的，但合约账户不应受限。

**Comment by lilianwen** [comment]
> > 我最近在使用FISCO BCOS的时候遇到一个问题。如果我用外部账号A去调用智能合约B的函数C。函数C会创建另一个智能合约D。这个时候FISCO BCOS会有一个限制要求，要求外部账号A必须有部署智能合约的权限。这样一个限制会让我写的智能合约B的易用性大大降低——也就是所有想要调用智能合约B的C函数的外部账号都必须首先授权具有部署智能合约的权限！！！
> > 我觉得这样的设计是不合理的。按照规则，应该是限制智能合约B必须具有部署智能合约的权限而不是限制调用B的C函数的外部账号。外部账号去调用B的C函数其实只是一个使用智能合约的行为，使用智能合约却要求有部署智能合约的权限，这其实是说不过去的。
> > solidity文档中建议Never use tx.origin for authorization. 会有安全问题。 还是用msg.sender比较好。
> 
> 感谢反馈！我个人认为
> 
> 1. 如果你希望所有人都调用函数C去创建合约，那么你就不应该控制创建合约的权限
> 2. 如果你不希望所有人调用函数C去创建合约，那么你应该使用有部署合约权限的账号来调用函数C
> 3. solidity文档中的问题是针对转账ether的问题，和FISCO BCOS的权限控制不相关，参考https://solidity.readthedocs.io/en/v0.6.2/security-considerations.html

我的需求就是任何人都能够调用函数C去创建合约（因为这个被创建的合约是固定的，单纯用来存储数据的合约，所以不会有安全性问题，可以放心去创建）。所以上述第一条“那么你就不应该控制创建合约的权限”我是不敢苟同的，如果不启用FISCO BCOS的链权限管理（基于角色的权限管理）,那么这个链的安全性是有问题的（任何接入到链的外部账号都可以声明自己是首个委员会委员从而控制整个链），这种有安全隐患的平台怎么可以用在生产环境中？

**Comment by bxq2011hust** [comment]
> 提问者的问题我也遇到。简单的需求是，我希望用户只能创建指定合约，而非任意合约，实际场景是：调用合约函数C部署合约（如工厂合约）。我觉得解决思路，可以将地址分为合约账户和用户账户，用户账户部署合约的权限是受控的，但合约账户不应受限。或者，如果用msg.sender部署，然后配置合约地址有权限部署合约也可以。
> 另外，fiscobcos的用户表的写权限控制也有类似的问题，有个需求是，我希望所有人都可以写表，但写的内容要过滤。若用智能合约过滤数据并插入表，表的写权限就没法设置，若不设置，数据的插入就没法过滤。

是的，所有人写表，用合约过滤，一旦限制了表的写权限确实是有你说的这个问题的。

**Comment by bxq2011hust** [comment]
> > > 我最近在使用FISCO BCOS的时候遇到一个问题。如果我用外部账号A去调用智能合约B的函数C。函数C会创建另一个智能合约D。这个时候FISCO BCOS会有一个限制要求，要求外部账号A必须有部署智能合约的权限。这样一个限制会让我写的智能合约B的易用性大大降低——也就是所有想要调用智能合约B的C函数的外部账号都必须首先授权具有部署智能合约的权限！！！
> > > 我觉得这样的设计是不合理的。按照规则，应该是限制智能合约B必须具有部署智能合约的权限而不是限制调用B的C函数的外部账号。外部账号去调用B的C函数其实只是一个使用智能合约的行为，使用智能合约却要求有部署智能合约的权限，这其实是说不过去的。
> > > solidity文档中建议Never use tx.origin for authorization. 会有安全问题。 还是用msg.sender比较好。
> > 
> > 
> > 感谢反馈！我个人认为
> > 
> > 1. 如果你希望所有人都调用函数C去创建合约，那么你就不应该控制创建合约的权限
> > 2. 如果你不希望所有人调用函数C去创建合约，那么你应该使用有部署合约权限的账号来调用函数C
> > 3. solidity文档中的问题是针对转账ether的问题，和FISCO BCOS的权限控制不相关，参考https://solidity.readthedocs.io/en/v0.6.2/security-considerations.html
> 
> 我的需求就是任何人都能够调用函数C去创建合约（因为这个被创建的合约是固定的，单纯用来存储数据的合约，所以不会有安全性问题，可以放心去创建）。所以上述第一条“那么你就不应该控制创建合约的权限”我是不敢苟同的，如果不启用FISCO BCOS的链权限管理（基于角色的权限管理）,那么这个链的安全性是有问题的（任何接入到链的外部账号都可以声明自己是首个委员会委员从而控制整个链），这种有安全隐患的平台怎么可以用在生产环境中？

链的治理权限和部署合约的权限是分离的，你可以控制治理，放开部署合约的权限。
