### ISSUE TITLE
关于出块的问题

### ISSUE THREAD

**Issue by shark1212** [FISCO-BCOS/FISCO-BCOS#18]
这与BCOS的出块机制是否不一样了，没有交易就不会再出新的块了？

**Comment by xiaonan778** [comment]
是的，fisco-bcos做了优化，没有交易不出块

**Comment by haiki** [comment]
请问怎么发交易呢？有说明的步骤之类的吗？

**Comment by fisco-dev** [comment]
参考说明文档：https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/doc/manual
