### ISSUE TITLE
如何配置更高版本的Solidity

### ISSUE THREAD

**Issue by gaby89757** [FISCO-BCOS/FISCO-BCOS#1831]
**Is your feature request related to a problem? Please describe.**
在 BCOSv2.7.0 上部署我已有的一个合约的时候，出现了Solidity版本不支持的信息。
![image](https://user-images.githubusercontent.com/75602216/101316783-1f861f00-3898-11eb-8656-f7ddc85841c8.png)
但是我在文档中看到是可以最高支持 solidity 0.6.10的，请问这个是需要有额外的配置吗，在官方文档中并没有看到这一块的解释文档。
![image](https://user-images.githubusercontent.com/75602216/101316979-902d3b80-3898-11eb-9357-234d6afc31e4.png)

**Describe the solution you'd like**
能够减少我们改造合约的成本，能够直接将已有合约迁移到BCOS上。

**Comment by bxq2011hust** [comment]
控制台有提供内置0.6的solc编译器的版本，直接下载使用即可

**Comment by gaby89757** [comment]
感谢回答，但是我这边下载支持0.5版本的控制台之后，部署的时候出现了如下的错误，没有提示具体的信息。
![image](https://user-images.githubusercontent.com/75602216/101451709-90e0d300-3967-11eb-880e-7b02366f91b1.png)

经过排查之后，发现是以下部分存在问题：
```solidity
contract Test {
    address anotherContractAddr = 0x274266CeC25d89B9eB6e0c5917cCa95046aE562F;
    ....
}
```
如果将改行注释便能部署成功，但是我用本地 0.5.2 版本的Solc编译是能成功的。

**Comment by bxq2011hust** [comment]
能否把出问题的合约发出来看看？或者有没有更详细的报错信息？
