### ISSUE TITLE
考虑对于新节点加入到已存在的链，只同步之前区块的区块头

### ISSUE THREAD

**Issue by codeAndxv** [FISCO-BCOS/FISCO-BCOS#1835]
对于已经存在的链，如果对于新加入的节点来说，之前的区块与它并无关联，没有必要同步之前区块的全部内容，是否考虑在配置文件中增加新的配置项来指定某个区块数之前的区块只同步区块头。

**Comment by bxq2011hust** [comment]
> 对于已经存在的链，如果对于新加入的节点来说，之前的区块与它并无关联，没有必要同步之前区块的全部内容，是否考虑在配置文件中增加新的配置项来指定某个区块数之前的区块只同步区块头。

新加入的节点需要同步完整区块，然后验证区块并执行区块中的交易来构建自身的状态数据，只同步区块头的话，需要通过其他安全合理的方式构建出自身的状态数据才可以。或许可以考虑了解这个组件https://github.com/WeBankBlockchain/Data-Stash
