### ISSUE TITLE
没有使用 0x5002合约的文档，也没有 0x5002合约的sol 加入到版本中

### ISSUE THREAD

**Issue by lialvin** [FISCO-BCOS/FISCO-BCOS#1841]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bxq2011hust** [comment]
这个合约用于压测，请参考这里https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/app_dev/transaction_parallel.html#id6
