### ISSUE TITLE
build_chain和generator 生成的节点证书样式不一致，无法复用

### ISSUE THREAD

**Issue by linbin524** [FISCO-BCOS/FISCO-BCOS#1845]
还有就是2.7版本，build_chain（拼接 ca+agency+node） 和generator（ageny+node） 生产节点证书 有差异，建议统一 一下
buildchain 生成节点证书 无法在generator 里面生成对应的节点，原因如上，生成节点时候，会去格式，generator是两级，buildchain  的三级无法通过。

**Comment by bxq2011hust** [comment]
这个拼接并不影响建立SSL连接，build_chain做全部的拼接是因为支持用户指定ca来签发下面的证书，所以需要做这个逻辑。
generator或许考虑放开这种检查，欢迎提个PR到generator

**Comment by HaoXuan40404** [comment]
fix at https://github.com/FISCO-BCOS/generator/pull/147/files
