### ISSUE TITLE
预编译合约如何参与到节点管理中

### ISSUE THREAD

**Issue by lyh168** [FISCO-BCOS/FISCO-BCOS#1848]
（1）预编译合约实现系统级别合约后，比如节点管理，请问当前节点是如何实时获取到节点管理合约共识之后的数据，进而参与到管理中，比如节点的黑白名单，或者区块链有些参数的更新等？
（2）我看源码中c++实现的系统预编译合约放入到libprecomplied中，如CNSPrecompiled.cpp，然后还在libprecomplied/solidity下面定义了一个相应的抽象接口如CNSPrecompiled.sol，这两者有什么调用或者依赖关系吗？

**Comment by bxq2011hust** [comment]
1. 在底层相关的逻辑中，会从预编译合约写入的表中读取数据，然后检查。一般我们会在写入时设定下个区块生效，当这笔交易被打包到区块，区块落盘后，执行下个区块的时候会从存储中读取。
2. cpp中是具体的逻辑的实现，solidity文件夹中的抽象是提供的接口的描述，方便开发者了解预编译合约提供的接口，甚至于开发者可以在solidity中调用预编译合约提供的接口


如果有兴趣一起参与FISCO BCOS开发优化，欢迎联系小助手加入FISCO BCOS 节点架构兴趣小组一起讨论！

**Comment by lyh168** [comment]
> 1. 在底层相关的逻辑中，会从预编译合约写入的表中读取数据，然后检查。一般我们会在写入时设定下个区块生效，当这笔交易被打包到区块，区块落盘后，执行下个区块的时候会从存储中读取。
> 2. cpp中是具体的逻辑的实现，solidity文件夹中的抽象是提供的接口的描述，方便开发者了解预编译合约提供的接口，甚至于开发者可以在solidity中调用预编译合约提供的接口
> 
> 如果有兴趣一起参与FISCO BCOS开发优化，欢迎联系小助手加入FISCO BCOS 节点架构兴趣小组一起讨论！

谢谢解答。
