### ISSUE TITLE
关于预编译合约中数据表功能欠缺问题

### ISSUE THREAD

**Issue by lialvin** [FISCO-BCOS/FISCO-BCOS#1851]
现在 提供的select 只能根据key 条件相等获取数据，而不能使用字典序的 条件 大于小于  获取数据。 
表建立后没发现建自动索引，不能使用自动索引分批获取数据。 
表打开后不能获取到表中记录的总数。

**Comment by bxq2011hust** [comment]
> 现在 提供的select 只能根据key 条件相等获取数据，而不能使用字典序的 条件 大于小于 获取数据。
> 表建立后没发现建自动索引，不能使用自动索引分批获取数据。
> 表打开后不能获取到表中记录的总数。

> 使用字典序的 条件 大于小于 获取数据

目前是不支持的，因为需要同时支持关系型和KV的数据库，所以需要屏蔽掉一部分KV不支持的功能。

> 表打开后不能获取到表中记录的总数。

这个也是存储在KV的时候，能拿到某个Key下的条数，但没法拿到表中所有key的总条数，除非遍历一遍。mysql中倒是可以直接拿到。

你有什么更好的想法么？如果有兴趣一起优化，欢迎联系小助手加入FISCO BCOS 3.0节点架构兴趣小组一起讨论！
