### ISSUE TITLE
请问官方有考虑过以后将paillier的C++库完善，让预编译合约不止有同态加，还可以做加密解密等操作吗？或者我应该如何将Java的paillier库翻译成C++上

### ISSUE THREAD

**Issue by wwe1428103707** [FISCO-BCOS/FISCO-BCOS#1865]
目前我看到C++的paillier库只实现了同态加这个功能，我想获得一些思路，即如何用C++实现其他功能，并且能够作为预编译合约放到bcos链上。

**Comment by Shareong** [comment]
我们是这样考虑的，加解密都是很特殊的接口，如果实现在预编译合约上，那么意味着交易（在所有区块链节点上）执行的时候，加密会暴露明文，解密会暴露私钥，这样就没有加解密的意义。。。 所以但凡涉及到敏感信息的接口，最好都是在应用层完成调用，然后再把结果写到区块链上。

**Comment by wwe1428103707** [comment]
> 我们是这样考虑的，加解密都是很特殊的接口，如果实现在预编译合约上，那么意味着交易（在所有区块链节点上）执行的时候，加密会暴露明文，解密会暴露私钥，这样就没有加解密的意义。。。 所以但凡涉及到敏感信息的接口，最好都是在应用层完成调用，然后再把结果写到区块链上。

是的，当时是我考虑得太片面了，感谢解答
