### ISSUE TITLE
手动生成的agency.crt解析有误

### ISSUE THREAD

**Issue by leeduckgo** [FISCO-BCOS/FISCO-BCOS#1894]
用openssl 手动生成csr文件后：
```
openssl req -new -sha256 -key agency.key -out req.csr -config cert.cnf
```

Subject信息如下：
```
 Subject: C = CN, ST = suibe, L = Shanghai, OU = suibe, CN = suibe
```

在控制台里getPeers得到的结果是`agency=CN`，应该是`agency=suibe`

**Comment by cyjseagull** [comment]
原因是解析机构、节点信息时，节点根据`CN`去匹配，并返回匹配到的字符串的`=`分割的第二个字段，这里就匹配到了`C=CN`，并返回了`CN`


已经通过PR #1893 修复~

**Comment by cyjseagull** [comment]
修复版本会在`2.8.0`版本发布。
