### ISSUE TITLE
通过树状交易同步，在关键路径上出现拜占庭节点

### ISSUE THREAD

**Issue by bugaolengdeyuxiaoer** [FISCO-BCOS/FISCO-BCOS#1900]
看了关于带宽优化的文章[https://my.oschina.net/fiscobcos/blog/4384038](url)

在以树形广播交易时，假设场景：node1是主节点，如果node2是拜占庭节点将tx_status中交易接收节点改为自己。这样在其他节点收到node1的pqc后拉取交易时会直接找node2拉取，而此时node2拒绝提供给交易导致本轮共识超时。

**Comment by cyjseagull** [comment]
1.  在交易树状广播的过程中，如果中间节点是拜占庭节点，故意不转发交易，但是由于有【基于状态包的交易转发策略】，主节点会从其他节点获取到最新的交易列表，并向其他节点拉取最新交易
2. 若主节点选择拉取交易的节点恰好也是拜占庭节点，一段时间后，其会选择其他节点继续拉取交易
3. 应该区分同步与共识，即使主节点没有任何交易，也不会共识超时，只会出空块；且PBFT采用了leader轮换规则，最终所有交易均可被处理。
