### ISSUE TITLE
webase-node-manager，ContractService的updateContract方法，部署状态比较有误

### ISSUE THREAD

**Issue by hongfish** [FISCO-BCOS/FISCO-BCOS#1930]
ContractService类的227行，部署状态比较使用了合约类型字段。
`if (tbContract.getContractType() == ContractStatus.DEPLOYED.getValue()`

**Comment by cyjseagull** [comment]
webase的问题，建议提交到[这里](https://github.com/WeBankFinTech/WeBASE-Node-Manager)

**Comment by mingzhenliu** [comment]
已修复
