### ISSUE TITLE
合约部署后显示地址为0x00000000000...00

### ISSUE THREAD

**Issue by mgjrr** [FISCO-BCOS/FISCO-BCOS#1939]
试图在链上部署自己的合约,采用和教程类似的方式.在Client中进行deploy时没有报错,然而输出的合约地址为0x000,在控制台上也自然看不到该地址的合约.
上面为教程部分Asset合约部署的输出,下面为自己的合约部署后的输出
`                                         
deploy Asset success, contract address is 0xc02f5962e31f3a51b24ce30f64ad1e265fbd811a
`
`
deploy Ev1 success, contract address is 0x0000000000000000000000000000000000000000
`

Client.java代码如下
`
public void deployAssetAndRecordAddr() {

    try {
      Asset asset = Asset.deploy(client, cryptoKeyPair);
      System.out.println(
              " deploy As success, contract address is " + asset.getContractAddress());

      Evidence evidence = Evidence.deploy(client, cryptoKeyPair);
      System.out.println(
          " deploy Ev1 success, contract address is " + evidence.getContractAddress());

      recordAssetAddr(evidence.getContractAddress());
    } catch (Exception e) {
      // TODO Auto-generated catch block
      // e.printStackTrace();
      System.out.println(" deploy Asset contract failed, error message is  " + e.getMessage());
    }
  }
`
期待您的帮助!

**Comment by cyjseagull** [comment]
您可以检查下`Evidence合约`构造函数的代码逻辑，有可能是合约代码处理异常，导致交易回滚了，进而导致合约部署失败。
