### ISSUE TITLE
关于C++预编译合约优化的问题

### ISSUE THREAD

**Issue by fengqiao** [FISCO-BCOS/FISCO-BCOS#1944]
看了一下C++预编译合约， 代码很是繁琐， 能不能优化一下，让C++预编译合约与Solidity合约一样的简洁，如
class HelloWorld : public ContratBase
{
public:
	using ContratBase::ContratBase;
	//预处理合约接口函数，由编译器自动发现调用
	static void ContractInit()
	{
		//注册合约及地址
		auto pContainer = ContractContainer<HelloWorld, 0x5001>::GetInstance();
		//注册
		pContainer->GetContractPtr()->RegisterFunc("get()", &HelloWorld::get);
		pContainer->GetContractPtr()->RegisterFunc("set(string)", &HelloWorld::set);
	}
	std::string get()
	{
		return "hello world";
	}
	void set(const std::string& str)
	{
	}
};
如果考虑优化的话，我也可以提供实现方案。

**Comment by morebtcg** [comment]
这个想法很不错
