### ISSUE TITLE
编译错误，提示 -DMYSQL_TCP_PORT=3305

### ISSUE THREAD

**Issue by HiBo001** [FISCO-BCOS/FISCO-BCOS#1962]
macOS 平台，cmake 3.20.3

提示错误 '/usr/local/Cellar/cmake/3.20.3/bin/cmake' '-DMYSQL_TCP_PORT=3305' '-DCMAKE_INSTALL_PREFIX=...

FISCO-BCOS/deps/src/mysqlclient-stamp/mysqlclient-configure-*.log中提示：

getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
CMake Error at cmake/install_macros.cmake:365 (ENDIF):
  Flow control statements are not properly nested.
Call Stack (most recent call first):
  CMakeLists.txt:199 (INCLUDE)

**Comment by cyjseagull** [comment]
目前master分支的最新代码没有适配cmake 3.20，可以拉取release-2.8分支的代码尝试编译，如果仍然有编译错误，欢迎反馈。

**Comment by cyjseagull** [comment]
> macOS 平台，cmake 3.20.3
> 
> 提示错误 '/usr/local/Cellar/cmake/3.20.3/bin/cmake' '-DMYSQL_TCP_PORT=3305' '-DCMAKE_INSTALL_PREFIX=...
> 
> FISCO-BCOS/deps/src/mysqlclient-stamp/mysqlclient-configure-*.log中提示：
> 
> getconf: no such configuration parameter `LEVEL1_DCACHE_LINESIZE'
> CMake Error at cmake/install_macros.cmake:365 (ENDIF):
> Flow control statements are not properly nested.
> Call Stack (most recent call first):
> CMakeLists.txt:199 (INCLUDE)

目前master分支的最新代码没有适配cmake 3.20，可以拉取release-2.8分支的代码尝试编译，如果仍然有编译错误，欢迎反馈。
