### ISSUE TITLE
哪里查看预编译合约的gas消耗

### ISSUE THREAD

**Issue by HL2222** [FISCO-BCOS/FISCO-BCOS#1965]
我实现了一个预编译合约到fisco，已经可以正常调用。
我用node0调用后，去node0的日志文件中并没有找到相关 gasused 信息；但是我如果调用正常 helloworld 合约时却可以看到gasused，请问这是怎么回事。
或者我应该去哪里查看预编译合约的gas花费

**Comment by cyjseagull** [comment]
交易的回执里会记录`gasUsed`信息
