### ISSUE TITLE
java对接ficos联盟链，本地可以访问conf下的证书并链接成功 。部署到服务器访问不到conf下面的证书

### ISSUE THREAD

**Issue by liangjiej** [FISCO-BCOS/FISCO-BCOS#1972]
**Describe the bug** 服务器通过jar包运行报错证书不存在。 本地是可以的正常对接节点。可以创建内部账号等调用接口是可以正常调用的，
springboot 项目对接联盟链 ，已经搭建节点。本地通过idea打包运行，可以访问到resource下的conf证书信息并成功访问，
但是通过打成jar包形式通过服务器运行，报错java.io.FileNotFoundException: conf/gm/gmca.crt      Load config from conf/gm/gmca.crt failed, trying to load from the classpath, e: {}
但是我配置的非国密登录  encryptType: 0，  在本地可以正常链接节点 。 但是通过linux部署到服务通过jar包方式启动就链接不到联  ，一直报读取不到证书，我fisco-bcos-java-sdk  ，2.7.2和2.8.0版本都试过了都是本地可以服务器jar包方式不行。  以上错误是2.8.0报出来的。 推测可能是jar包提供读取证书的方式（ File file = new File(configFilePath);），导致服务器通过jar包方式启动，访问不到证书。

**To Reproduce**
1. Go to '...'   服务器通过jar包启动项目。读取不到证书报错。 本地是可以正常链接。 已经排除网络问题
2. Deploy Contract '....'
3. Call interface '....'

**Expected behavior**

希望解决一下。通过jar方式启动。支持获取证书路径并成功访问节点
**Screenshots**

本地运行![image](https://user-images.githubusercontent.com/88539693/128505305-b567d4a1-94fb-4cbb-982a-122e4ab6209c.png)
![image](https://user-images.githubusercontent.com/88539693/128505452-ed50b57d-b2b1-455e-9292-2972c94018fb.png)
![image](https://user-images.githubusercontent.com/88539693/128505491-a8890f6b-12e3-45ae-a06c-42510d9962b0.png)

服务器
![image](https://user-images.githubusercontent.com/88539693/128505626-73fe5f2c-3134-4d44-bd83-397a9d64cf2d.png)
![image](https://user-images.githubusercontent.com/88539693/128505751-d46ca258-fa7c-4ad3-a39f-58d4aa5f393a.png)
jar包对应的证书路径实际已经变了
![image](https://user-images.githubusercontent.com/88539693/128505835-c408730f-3ee1-43a3-ab84-779821c5762c.png)

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.2]
 - Linux version 5.8.0-63-generic (buildd@lgw01-amd64-035) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021

 - FISCO BCOS Version [e.g. 2.4.0]    2.8.0
**Additional context**

**Comment by 15168326318** [comment]
你有解决吗？  我也一直报conf/gm/gmca.crt 这个错。

**Comment by liangjiej** [comment]
解决办法，在jar包同级目录 新建一个conf目录 ，然后把证书放进去



***@***.***
 
发件人： chengchungen
发送时间： 2021-11-09 11:22
收件人： FISCO-BCOS/FISCO-BCOS
抄送： liangjiej; Author
主题： Re: [FISCO-BCOS/FISCO-BCOS] java对接ficos联盟链，本地可以访问conf下的证书并链接成功 。部署到服务器访问不到conf下面的证书 (#1972)
你有解决吗？ 我也一直报conf/gm/gmca.crt 这个错。
―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
