### ISSUE TITLE
编译时mysqlclient报错DMYSQL_TCP_PORT=3305

### ISSUE THREAD

**Issue by jsuoflc** [FISCO-BCOS/FISCO-BCOS#1975]
系统：ubuntu，cmake版本3.20.5
编译时mysqlclient报错，错误如下：
CMake Error at /home/usr/桌面/FISCO-BCOS/deps/src/mysqlclient-stamp/mysqlclient-configure-RelWithDebInfo.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DMYSQL_TCP_PORT=3305' '-DCMAKE_INSTALL_PREFIX=/home/usr/桌面/FISCO-BCOS/deps/' '-GUnix Makefiles' '/home/usr/桌面/FISCO-BCOS/deps/src/mysqlclient'

  See also

    /home/usr/桌面/FISCO-BCOS/deps/src/mysqlclient-stamp/mysqlclient-configure-*.log

**Comment by wheatli** [comment]
请进入/home/usr/桌面/FISCO-BCOS/deps/src/mysqlclient-stamp/mysqlclient-configure-*.log查看详细错误

**Comment by cyjseagull** [comment]
请尝试拉取`master-2.0`分支最新代码，2.8.0做了对cmake 3.20的支持。
