### ISSUE TITLE
编译源码问题

### ISSUE THREAD

**Issue by dengzq186** [FISCO-BCOS/FISCO-BCOS#1988]
**----- 环境 centos7, 编译选项 -DTOOL=on.**
![9290be9f81ce71767682a3c91382e91](https://user-images.githubusercontent.com/51815588/135059317-f90756ce-77bb-4156-88d7-31cf1a6ed97a.png)

**------- 修改源代码，按原始的办法初始化结构体，如下图**
![image](https://user-images.githubusercontent.com/51815588/135059714-826310ee-05c3-431f-93f8-21bb7dc8b304.png)

**----- 按上图修改源代码，继续编译后，后面又有新的问题，如下图：**
![image](https://user-images.githubusercontent.com/51815588/135060169-8e34d809-f727-4f71-b7eb-9d704ae3b471.png)

**Comment by bxq2011hust** [comment]
可以先注释下面这行，然后cmake，重新make

https://github.com/FISCO-BCOS/FISCO-BCOS/blob/30fb38ac5692468058abf6aa12869d2ae776c275/cmake/CompilerSettings.cmake#L36

**Comment by dengzq186** [comment]
谢谢
