### ISSUE TITLE
没有授权的用户通过合约创建table响应成功

### ISSUE THREAD

**Issue by zqge** [FISCO-BCOS/FISCO-BCOS#1992]
**Describe the bug**
我用合约创建 table表。但是链我设置的权限，只有有相关权限的用户才能创建表。
但是经过测试，用没有权限的用户创建的时候同样会返回成功，而且区块链浏览器上可以查的到
但实际上是没有创建成功的，而且用控制台查询也是没有查到。

**To Reproduce**

1. 创建用户创建表的合约。

   ```solidity
   contract TableController {
   
   
       constructor () public {
           _tableFactory = TableFactory(0x1001);
       }
       
       function createTable(string memory tableName,string memory keyField,string memory valueFields) public {
           _tableFactory.createTable(tableName,keyField,valueFields);
       }
    }
   ```

   

2. 部署合约，并设置链用户A（A没有创建表的权限）

3. 用A调用createTable函数，创建表。

4. 这时会提示创建成功，而且区块链浏览器上同样能看到成功的响应数据。

5. 但是通过控制台去查刚创建的表，提示表不存在。

6. 实际上表并没有创建成功，插入查询操作也都进行不了。

**Environment (please complete the following information):**

 - OS: *ubuntu18.04*
 - FISCO BCOS Version ：2.7.2

**Comment by mingzhenliu** [comment]
function createTable(string, string, string) public returns (int256);    createTable需要去校验返回值，交易成功和建表成功是两回事

**Comment by mingzhenliu** [comment]
function createTable(string, string, string) public returns (int256);    createTable需要去校验返回值，交易成功和建表成功是两回事

**Comment by cyjseagull** [comment]
请确认`transaction receipt.status`返回值是否为`0`，如果非0，说明建表是失败的
