### ISSUE TITLE
DNS for P2P network

### ISSUE THREAD

**Issue by conquerorAlex** [FISCO-BCOS/FISCO-BCOS#1994]
**Is your feature request related to a problem? Please describe.**
To start bcos network, for now, an static IP must be set in config file. However, in some scenarios, an elastic IP is much more convenience, such as, dns used to instead of static IP.

**Describe the solution you'd like**
Bcos should support both IP and dns for its network

**Additional context**
Especially, in docker overlay network, such as kubernetes, bcos node started as a pod and service. In this case, service IP and pod IP are allocated dynamically. Therefor, a dns that should be configured is better than a static IP.

**Comment by wheatli** [comment]
BCOS has supported DNS, please have a try~
