### ISSUE TITLE
how to Compile the libinterpreter

### ISSUE THREAD

**Issue by rebel-ly** [FISCO-BCOS/FISCO-BCOS#1995]
since i have seen that the file libinterpreter had been commented out in the top level Cmakelist.txt. But i want to do some modify for the handling of operators, what should i do ?

I have tried to de-comment and the compile will report an error，where i need to change? the cmake file? or the dependence EVMC ,EVMone?

I really need your help !! thanks!
![image](https://user-images.githubusercontent.com/56351033/142805205-c5c22ad8-c5d1-438e-b310-85dd158cb48e.png)

**Comment by wheatli** [comment]
the libinterpreter module is out of date, we use the alternative evmone instead

**Comment by rebel-ly** [comment]
您好，我是刘钰。您的邮件我已收到，我会尽快回复。谢谢！

**Comment by cyjseagull** [comment]
请参考：https://github.com/FISCO-BCOS/FISCO-BCOS/blob/v2.4.1/CMakeLists.txt
