### ISSUE TITLE
控制台版本问题

### ISSUE THREAD

**Issue by rebel-ly** [FISCO-BCOS/FISCO-BCOS#1996]
您好 ， 请问控制台console的哪个版本 可以支持Tsinghua-2.0.1 分支编译的fisco-bcos呢

**Comment by cyjseagull** [comment]
`Tsinghua-2.0.1`分支没有经过完整的测试，暂时不推荐使用`Tsinghua-2.0.1`分支，如果这个分支有您在业务上需要使用的特性，欢迎提出来。

**Comment by rebel-ly** [comment]
您好，我是刘钰。您的邮件我已收到，我会尽快回复。谢谢！

**Comment by rebel-ly** [comment]
您好，我是刘钰。您的邮件我已收到，我会尽快回复。谢谢！
