### ISSUE TITLE
写一些遇到的坑，希望有所帮助：

### ISSUE THREAD

**Issue by 574009097** [FISCO-BCOS/FISCO-BCOS#2032]
写一些遇到的坑，希望有所帮助：
1、按照开始的方法修改node_modules的代码是可以解决编译问题的，后续如果遇到部署问题，我这里是部署超时，也就是节点彼此是没连接上的。判断方法如下：1）在caliper/networks/fisco-bcos/ 4node1group/ 下又docker-compose.yaml，使用docker-compose -f docker-compose.yaml up -d （也可以在文档中找到）可以单独启动节点。2）从api文档中找到获取节点状态或节点数量的curl 接口，看一下连接的节点数量。
2、解决上述问题可以通过docker network ls查看当前的网卡设备，一般是一个叫4node1group的。通过docker network inspect [ 4n1g 的ID ]，查看具体容器内部的ip地址。将node0-4里的ip修改成对应的ip。docker 重启会重新初始化4n1g，ip可能会不一样。
3、也可以选择直接将该docker-compose.yaml文件添加一个network，每个节点内部的ip都可以写死，当然也要和node0/config.ini里的保持一致。这样节点启动时就可以互连了

_Originally posted by @bugaolengdeyuxiaoer in https://github.com/FISCO-BCOS/FISCO-BCOS/issues/1248#issuecomment-808336783_

**Comment by wheatli** [comment]
🙏
