### ISSUE TITLE
build过程中遇到Undefined symbols for architecture arm64的问题

### ISSUE THREAD

**Issue by JohannaXiao** [FISCO-BCOS/FISCO-BCOS#2036]
**Describe the bug**
`Undefined symbols for architecture arm64:

  "SM3_Update(SM3state_st*, void const*, unsigned long)", referenced from:
      SM2::sign(char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned char*, unsigned char*) in libdevcrypto.a(sm2.cpp.o)
      SM2::verify(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*) in libdevcrypto.a(sm2.cpp.o)
      SM3Hash::update(SM3state_st*, void const*, unsigned long) in libdevcrypto.a(sm3.cpp.o)
  "SM4_decrypt(unsigned char const*, unsigned char*, SM4_KEY_st const*)", referenced from:
      SM4::decrypt(unsigned char const*, unsigned char*) in libdevcrypto.a(sm4.cpp.o)
  "SM4_encrypt(unsigned char const*, unsigned char*, SM4_KEY_st const*)", referenced from:
      SM4::encrypt(unsigned char const*, unsigned char*) in libdevcrypto.a(sm4.cpp.o)
  "SM4_set_key(unsigned char const*, unsigned long, SM4_KEY_st*)", referenced from:
      SM4::setKey(unsigned char const*, unsigned long) in libdevcrypto.a(sm4.cpp.o)
  "SM3_Transform(SM3state_st*, unsigned char const*)", referenced from:
      SM3Hash::transForm(SM3state_st*, unsigned char const*) in libdevcrypto.a(sm3.cpp.o)
  "SM4_cbc_encrypt(unsigned char const*, unsigned char*, unsigned long, SM4_KEY_st const*, unsigned char*, int)", referenced from:
      SM4::cbcEncrypt(unsigned char const*, unsigned char*, unsigned long, unsigned char*, int) in libdevcrypto.a(sm4.cpp.o)
  "SM3(unsigned char const*, unsigned long, unsigned char*)", referenced from:
      SM3Hash::sm3(unsigned char const*, unsigned long, unsigned char*) in libdevcrypto.a(sm3.cpp.o)
  "SM3_Init(SM3state_st*)", referenced from:
      SM2::sign(char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned char*, unsigned char*) in libdevcrypto.a(sm2.cpp.o)
      SM2::verify(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*) in libdevcrypto.a(sm2.cpp.o)
      SM3Hash::init(SM3state_st*) in libdevcrypto.a(sm3.cpp.o)
  "SM3_Final(unsigned char*, SM3state_st*)", referenced from:
      SM2::sign(char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned char*, unsigned char*) in libdevcrypto.a(sm2.cpp.o)
      SM2::verify(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char const*) in libdevcrypto.a(sm2.cpp.o)
      SM3Hash::final(unsigned char*, SM3state_st*) in libdevcrypto.a(sm3.cpp.o)
  "_curve25519_vrf_generate_key_pair", referenced from:
      dev::consensus::VRFBasedrPBFTSealer::initConsensusEngine() in libconsensus.a(VRFBasedrPBFTSealer.cpp.o)
  "_curve25519_vrf_is_valid_pubkey", referenced from:
      dev::precompiled::CryptoPrecompiled::curve25519VRFVerify(dev::vector_ref<unsigned char const>, std::__1::shared_ptr<dev::precompiled::PrecompiledExecResult>) in libprecompiled.a(CryptoPrecompiled.cpp.o)
      dev::precompiled::VRFInfo::isValidVRFPublicKey() in libprecompiled.a(WorkingSealerManagerImpl.cpp.o)
  "_curve25519_vrf_proof", referenced from:
      dev::consensus::VRFBasedrPBFTSealer::generateTransactionForRotating() in libconsensus.a(VRFBasedrPBFTSealer.cpp.o)
  "_curve25519_vrf_proof_to_hash", referenced from:
      dev::precompiled::CryptoPrecompiled::curve25519VRFVerify(dev::vector_ref<unsigned char const>, std::__1::shared_ptr<dev::precompiled::PrecompiledExecResult>) in libprecompiled.a(CryptoPrecompiled.cpp.o)
      dev::precompiled::VRFInfo::getHashFromProof() in libprecompiled.a(WorkingSealerManagerImpl.cpp.o)
  "_curve25519_vrf_verify", referenced from:
      dev::precompiled::CryptoPrecompiled::curve25519VRFVerify(dev::vector_ref<unsigned char const>, std::__1::shared_ptr<dev::precompiled::PrecompiledExecResult>) in libprecompiled.a(CryptoPrecompiled.cpp.o)
      dev::precompiled::VRFInfo::verifyProof() in libprecompiled.a(WorkingSealerManagerImpl.cpp.o)

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/fisco-bcos] Error 1
make[2]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] Error 2
make[1]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/rule] Error 2
make: *** [fisco-bcos] Error 2
`

**To Reproduce**
$ cd FISCO-BCOS
$ git checkout master
$ mkdir -p build && cd build
$ cmake ..
$ make
然后出现如上bug

**Expected behavior**
make成功

**Screenshots**
![image](https://user-images.githubusercontent.com/62994240/144788075-4c217b94-0e5a-4592-89e8-44c43aa04147.png)

**Environment (please complete the following information):**
 - OS: MacOS M1
 - FISCO BCOS Version 2.0

**Comment by wheatli** [comment]
目前2.0不支持M1，如果您已解决这个平台的编译，欢迎PR贡献给社区

**Comment by exgphe** [comment]
@wheatli 我们现在正在尝试解决M1编译的问题。目前遇到的一个主要的障碍是libvrf的编译。我发现项目里libffi_vrf.a是直接下载下来的，而且只编译了Linux x64/arm64和macOS x64的版本。这一部分似乎没有开放源代码。你们可以提供libvrf的源代码吗？或者提供macOS arm64的静态库？

**Comment by bxq2011hust** [comment]
>
[libffi_vrf_macOS_aarch64.a.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/7710302/libffi_vrf_macOS_aarch64.a.zip)
 

> @wheatli 我们现在正在尝试解决M1编译的问题。目前遇到的一个主要的障碍是libvrf的编译。我发现项目里libffi_vrf.a是直接下载下来的，而且只编译了Linux x64/arm64和macOS x64的版本。这一部分似乎没有开放源代码。你们可以提供libvrf的源代码吗？或者提供macOS arm64的静态库？

**Comment by bxq2011hust** [comment]
> @wheatli 我们现在正在尝试解决M1编译的问题。目前遇到的一个主要的障碍是libvrf的编译。我发现项目里libffi_vrf.a是直接下载下来的，而且只编译了Linux x64/arm64和macOS x64的版本。这一部分似乎没有开放源代码。你们可以提供libvrf的源代码吗？或者提供macOS arm64的静态库？

另外，3.0版本已经原生支持macOS m1

**Comment by JohannaXiao** [comment]
> > @wheatli 我们现在正在尝试解决M1编译的问题。目前遇到的一个主要的障碍是libvrf的编译。我发现项目里libffi_vrf.a是直接下载下来的，而且只编译了Linux x64/arm64和macOS x64的版本。这一部分似乎没有开放源代码。你们可以提供libvrf的源代码吗？或者提供macOS arm64的静态库？
> 
> 另外，3.0版本已经原生支持macOS m1

使用您提供的libvrf文件解决了部分bug，换回旧版tassl后参考https://gist.github.com/felixbuenemann/5f4dcb30ebb3b86e1302e2ec305bac89
这个链接解决了在macOS m1上的兼容问题
