### ISSUE TITLE
Segmentation fault when try to start a node

### ISSUE THREAD

**Issue by fCorleone** [FISCO-BCOS/FISCO-BCOS#2132]
**Describe the bug**
I use the official build_chain.sh file to construct a group of 4 nodes. The shell download the binary file of fisco bcos from: [https://github.com/FISCO-BCOS/FISCO-BCOS/releases/download/v3.0.0-rc1/fisco-bcos-linux-x86_64.tar.gz](https://github.com/FISCO-BCOS/FISCO-BCOS/releases/download/v3.0.0-rc1/fisco-bcos-linux-x86_64.tar.gz)
I first ran the start_all.sh file to start this group and produced some data. After that, I use the latest code (commit hash: 1f0dd3e9de3984db26eee37d4183bedfff8e408b) to compile a new binary. However, the third node cannot start successfully.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/22519865/149464740-f5514403-c7af-4a11-ba95-e4a63e0bfd41.png">

**To Reproduce**
1. Use 3.0-rc1 binary to start the chain
2. replace the binary with the rc2 one.
3. restart the group's nodes

**Expected behavior**
The node should start successfully

**Screenshots**
Screenshots when using gdb to debug:
![企业微信截图_a66c4339-4835-4aa6-bfcc-163f1809049a](https://user-images.githubusercontent.com/22519865/149464585-06887874-a542-4444-b4da-2b32c9b38b0f.png)
![企业微信截图_6e663040-1d27-4ded-9683-b3b3d296178f](https://user-images.githubusercontent.com/22519865/149464601-9f85db0d-6d29-4bec-879a-6edd9cad7001.png)
![企业微信截图_16b2c514-7e4b-48fb-b628-61037be7cad7](https://user-images.githubusercontent.com/22519865/149464612-7e29fef9-33eb-46e2-aaa6-217f1ac29ad2.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - FISCO BCOS release-3.0.0-rc2 (commit hash: 1f0dd3e9de3984db26eee37d4183bedfff8e408b)

**Comment by cyjseagull** [comment]
The previous implementation method was to construct a temporary lock first, then std::move the temporary lock as a shared_ptr lock, and pass the lock into the lamda expression. 

When the lock is reconstructed, it will be thread insecure, causing the same block to enter the execution twice. 

In the process, it is now changed to directly construct the lock of shared_ptr

**Comment by cyjseagull** [comment]
This problem is finally located when the scheduler is initialized, and the `executor` in the `executorManager` is empty. If the synchronization and consensus modules **execute the block** before the `executorManager addExecutor`, the block will not be executed while the block has already been put into the cache,  and the corresponding callback will not be called. 

When the block is executed next time, it will hit the cache and **return an empty execution result**, causing the node to coredump,
