### ISSUE TITLE
build fail on MacBook Pro M1 max

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [FISCO-BCOS/FISCO-BCOS#2135]
2021最新版MacBook Pro M1 max， MacOS Monteray 12.1
这样拉的代码：
git clone https://github.com/FISCO-BCOS/FISCO-BCOS.git -b master-2.0

依赖按照官方文档也装了：
brew install openssl git flex bison gmp

最后make的时候：
cd FISCO-BCOS
mkdir -p build && cd build
cmake -DARCH_NATIVE=on ..
make

[  0%] Built target BuildInfo.h
[  1%] Performing build step for 'tbb'
CMake Error at /Users/hh/fisco/FISCO-BCOS/deps/src/tbb-stamp/tbb-build-RelWithDebInfo.cmake:49 (message):
  Command failed: 2

   'make' 'extra_inc=big_iron.inc' 'stdlib=libc++'

  See also

    /Users/hh/fisco/FISCO-BCOS/deps/src/tbb-stamp/tbb-build-*.log

make[2]: *** [../deps/src/tbb-stamp/tbb-build] Error 1
make[1]: *** [CMakeFiles/tbb.dir/all] Error 2
make: *** [all] Error 2

然后去查看这个 tbb-build-err.log:
../../build/Makefile.tbb:28: CONFIG: cfg=release arch=ia32 compiler=clang target=macos runtime=cc13.0.0_os12.1
clang: warning: argument unused during compilation: '-mrtm' [-Wunused-command-line-argument]
../../src/tbbmalloc/frontend.cpp:779:8: error: invalid instruction, any one of the following would fix this:
       "clz %0, %1\n"
       ^
<inline asm>:1:2: note: instantiated into assembly here
        clz r2, r1
        ^
../../src/tbbmalloc/frontend.cpp:779:8: note: instruction requires: armv5t
       "clz %0, %1\n"
       ^
<inline asm>:1:2: note: instantiated into assembly here
        clz r2, r1
        ^

基本看出来这个tbb的源代码里含有汇编代码，这个是不是不支持arm ？？
请问我要如何解决？

**Comment by cyjseagull** [comment]
We will do the adaptation of m1 in the next version

**Comment by Aoengo** [comment]
官方文档里面讲到，3.0.0支持M1，并且我确实编译通过了，不过有大把警告，后面也在测试。

**Comment by hh-in-zhuzhou** [comment]
@Aoengo 谢谢你的提示，我拉取了最新的3.0的代码，按照3.0的文档编译，还是没有编译通过：

**Comment by hh-in-zhuzhou** [comment]
@Aoengo 谢谢你的提示，我拉取了最新的3.0的代码，按照3.0的文档编译，还是没有编译通过
cargo:warning=depend/secp256k1/contrib/lax_der_parsing.c:7:10: fatal error: 'string.h' file not found

不知道是不是因为最新的Monterey没有/usr/include的缘故，请问有没有别的办法解决呢？

**Comment by cyjseagull** [comment]
> @Aoengo 谢谢你的提示，我拉取了最新的3.0的代码，按照3.0的文档编译，还是没有编译通过 cargo:warning=depend/secp256k1/contrib/lax_der_parsing.c:7:10: fatal error: 'string.h' file not found
> 
> 不知道是不是因为最新的Monterey没有/usr/include的缘故，请问有没有别的办法解决呢？



尝试如下命令：
```shell
cd build && rm -rf CMakeCache.txt
# 指定sdkroot
export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ..
make
```
