### ISSUE TITLE
启动节点提示DatabaseAlreadyOpen

### ISSUE THREAD

**Issue by veuvelee** [FISCO-BCOS/FISCO-BCOS#218]
测试环境服务器断电一次后重启就提示terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::eth::DatabaseAlreadyOpen>' 一直起不起来，请问下有知道是什么原因的吗？具体的启动输出日志：
[xxx@localhost nodedata-1]$ fisco-bcos   --genesis genesis.json --config config.json
---------------FISCO BCOS--------------
RPCPORT:8545
SSLRPCPORT:6790
CHANNELPORT:30304
LISTENIP:192.168.0.18
P2PPORT:30303
SSL:2
WALLET:./data/keys.info
KEYSTOREDIR:./data/keystore/
DATADIR:./data/
VM:interpreter
SEALENGINE:PBFT
NETWORKID:12345
SYSTEMPROXYADDRESS:23df89a2893120f686a4aa03b41acf6836d11e5d
GOD:06e853c692216f5c5eea72f9ece7c042510a1ea5
LOGVERBOSITY:4
EVENTLOG:ON
COVERLOG:OFF
---------------------------------------------------------------
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::eth::DatabaseAlreadyOpen>'
  what():  DatabaseAlreadyOpen
Aborted

**Comment by veuvelee** [comment]
看了下好像是磁盘满了

**Comment by JimmyShi22** [comment]
好像是节点重复启动了

**Comment by bxq2011hust** [comment]
磁盘满导致数据写坏
