### ISSUE TITLE
Transactions fail to commit when testing the rc2 version, 2 nodes crashed.

### ISSUE THREAD

**Issue by fCorleone** [FISCO-BCOS/FISCO-BCOS#2204]
**Describe the bug**
I start a chain with 4 nodes and 1 of them is a malicious one that will send messages with maliciously constructed fields. The stress testing command stuck and 2 nodes crash down. Maybe it is some bug related to libgomp.

**To Reproduce**
1. Set up a 4-node chain.
2. Start the stress testing with
```
java -cp 'conf/:lib/*:apps/*' org.fisco.bcos.sdk.demo.perf.PerformanceDMC group 32 500000 10000
```
3. The error will occur

**Expected behavior**
Nodes should not crash down.

**Screenshots**
<img width="1280" alt="屏幕快照 2022-02-28 下午5 17 51" src="https://user-images.githubusercontent.com/22519865/155983244-1c7bc8f1-2139-4b37-80c9-4c19977fc4cc.png">
The terminal reports this:
<img width="636" alt="屏幕快照 2022-02-28 下午5 56 59" src="https://user-images.githubusercontent.com/22519865/155983280-738bab12-2fd0-439b-8a7a-833150f7be32.png">

**Environment (please complete the following information):**
 - OS:Ubuntu 20.04
 - FISCO BCOS Version 3.0.0-rc2

** The log of the nodes**
[node_logs.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/8153267/node_logs.zip)

**Comment by cyjseagull** [comment]
Pls set `OMP_NUM_THREADS=1`
