### ISSUE TITLE
Nodes kept view changing when there is a malicious node.

### ISSUE THREAD

**Issue by fCorleone** [FISCO-BCOS/FISCO-BCOS#2206]
**Describe the bug**
I start a chain of 4 nodes. One of the nodes is the malicious node which will send maliciously constructed messages to other nodes. Then I start the stress testing. All the nodes stop producing new blocks and keep view changing after a while.
**To Reproduce**
1. Start a chain with 3 normal nodes and 1 malicious node.
2. Start stress testing
3. The bug occurs

**Expected behavior**
Nodes should produce blocks constantly.

**Screenshots**
The stress testing program stuck here:
<img width="1230" alt="wecom-temp-9d1a6cbef23ea821b1afe2592df162c4" src="https://user-images.githubusercontent.com/22519865/155991565-9426f815-254e-4aaf-9c4b-3cbe144ba76a.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - FISCO BCOS release 3.0.0-rc2

**Additional context**
Maybe this situation happens when a malicious node sends an invalid transaction to other nodes when they send a proposal to the malicious node.

The log file:
[node_logs_viewchange.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/8153655/node_logs_viewchange.zip)

**Comment by cyjseagull** [comment]
This should be a bug in the development process, please pull the master branch code to verify.
