### ISSUE TITLE
编译+部署合约 HelloWorld 错误

### ISSUE THREAD

**Issue by 4593645** [FISCO-BCOS/FISCO-BCOS#221]
lizf@lizf-VirtualBox:/mydata/fisco-bcos/tool$ babel-node deploy.js HelloWorld
deploy.js  ........................Start........................
Soc File :HelloWorld
/bin/sh: 1: fisco-solc: not found
HelloWorldcomplie failed!Error: Command failed: fisco-solc --overwrite --abi  --bin -o ./output/  HelloWorld.sol
/bin/sh: 1: fisco-solc: not found

(node:12022) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './output/./HelloWorld.abi'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/mydata/fisco-bcos/web3lib/web3sync.js:735:31)
    at Generator.next (<anonymous>)
    at step (/mydata/fisco-bcos/web3lib/web3sync.js:293:191)
    at /mydata/fisco-bcos/web3lib/web3sync.js:293:437
    at new Promise (<anonymous>)
    at Object.<anonymous> (/mydata/fisco-bcos/web3lib/web3sync.js:293:99)
    at Object.rawDeploy (/mydata/fisco-bcos/web3lib/web3sync.js:156:18)
    at /mydata/fisco-bcos/tool/deploy.js:39:32
(node:12022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

请教如何排解，创世节点已经启动

**Comment by JimmyShi22** [comment]
装下合约编译器：fisco-solc

下载对应平台的solidity编译器, 直接下载后放入系统目录下。
[ubuntu]：
``` shell
    wget https://github.com/FISCO-BCOS/fisco-solc/raw/master/fisco-solc-ubuntu
    sudo cp fisco-solc-ubuntu  /usr/bin/fisco-solc
    sudo chmod +x /usr/bin/fisco-solc
```    
    
[centos]：
``` shell
    wget https://github.com/FISCO-BCOS/fisco-solc/raw/master/fisco-solc-centos
    sudo cp fisco-solc-centos  /usr/bin/fisco-solc
    sudo chmod +x /usr/bin/fisco-solc
```
