### ISSUE TITLE
单机4节点网络下新建群组问题

### ISSUE THREAD

**Issue by Virgeo** [FISCO-BCOS/FISCO-BCOS#2210]
**Describe the bug**
单机四节点网络下新建群组问题：
调用javasdk所提供的接口或者curl命令发送新建、启动群组请求时，返回success信息，但实际上群组无效，查看了每个节点目录文件，只有处理请求的那个节点目录下生成了对应的group.ini与group.genesis文件，但请求发送时只能指定一个节点的ip:port

这样设计是需要四个节点分别单独发送新建群组请求，群组才能创建成功吗
**Environment :**
 - OS: [CentOS 7.2]
 - FISCO BCOS Version [2.7.2]

**Comment by cyjseagull** [comment]
动态群组是通过rpc接口管理的，因此群组创建、删除等也都是节点维度的，如果需要为每个节点新增群组，必须将请求发送到所有节点。
