### ISSUE TITLE
The nodes change view frequently and stop generating blocks.

### ISSUE THREAD

**Issue by fCorleone** [FISCO-BCOS/FISCO-BCOS#2211]
**Describe the bug**
I start a chain with 4 nodes, one of the nodes is a malicious one. It will change the value of some fields of a message. After starting the group, I started the stress testing program. And the program stuck. The log shows that the nodes stop producing new blocks and keep view changing.

**To Reproduce**
1. Start a chain with 4 nodes;
2. Start the stress testing program;
3. The error occurs

**Expected behavior**
Nodes produce the blocks normally.

**Screenshots**
The stress testing program stuck here (2% of the transactions are received)
<img width="1280" alt="wecom-temp-2116cfbcd90990732c059a3c3ed262b3" src="https://user-images.githubusercontent.com/22519865/156157229-3f03a637-215e-4806-9695-190555532b49.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - FISCO BCOS Version 3.0.0-rc2 (master branch)

**Additional context**
The log files:
[nodes_logs_0301.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/8161037/nodes_logs_0301.zip)

**Comment by cyjseagull** [comment]
There is a bug in the logic of PBFT 3.0 fastViewChange, which causes if a malicious node deliberately sends a viewchange packet with a large view, other nodes will frequently trigger fast view switching and try to catch up with the malicious node's view
