### ISSUE TITLE
generateGroup接口 可能会改变sdk传入的sealers集合元素的顺序 导致该节点创世块和其他节点不一致

### ISSUE THREAD

**Issue by JyFangYang** [FISCO-BCOS/FISCO-BCOS#2213]
Describe the bug
generateGroup接口可能会改变java-sdk传入的sealers集合元素的顺序，导致该节点生成创世块和其他节点不一致，后续节点startGroup、addSearler失败

fisco底层C++代码应该用的是set集合改变了上层sealers集合元素的顺序

Environment :
OS: [CentOS 7.2]
FISCO BCOS Version [2.7.2]

**Comment by HelloAldis** [comment]
这个问题应该修复为：多个不同节点对比创始块hash时，应该忽略创始块文件中的共识节点顺序，也就是先统一的排序后在比对Hash值
