### ISSUE TITLE
部署bcos网络

### ISSUE THREAD

**Issue by Blackcatfish** [FISCO-BCOS/FISCO-BCOS#229]
两台机器每个机器有两个节点 怎么能够生成一条链

**Comment by liangyongfu** [comment]
同一台机器中两个节的rpc端口和channel端口设置成不一样，在配置节点的文件中就可以区分了。

**Comment by Rcvisual** [comment]
先生成一条主链，生成创世节点，之后使用脚本生成不同机器安装包，上传不同机器进行安装

**Comment by bxq2011hust** [comment]
长时间无回复，先关闭，如果问题没有解决，欢迎随时联系！
