### ISSUE TITLE
client.keystore生成问题

### ISSUE THREAD

**Issue by Tes99t01** [FISCO-BCOS/FISCO-BCOS#23]
可否 详细说明下SDK中提到的client.keystore文件生成过程？

**Comment by mingzhenliu** [comment]
keytool -import -trustcacerts -alias ca -file ca.crt -keystore client.keystore

**Comment by mingzhenliu** [comment]
keytool -import -trustcacerts -alias ca -file ca.crt -keystore client.keystore

**Comment by mingzhenliu** [comment]
https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html

**Comment by fisco-dev** [comment]
1、openssl pkcs12 -export -name client -in server.crt -inkey server.key -out keystore.p12
2、keytool -importkeystore -destkeystore client.keystore -srckeystore keystore.p12 -srcstoretype pkcs12 -alias client
3、Attention！ Password must be ”123456”
