### ISSUE TITLE
receiptProof为空的问题

### ISSUE THREAD

**Issue by chaunsin** [FISCO-BCOS/FISCO-BCOS#2329]
**Describe the bug**
请教个问题,我想做区块的有效应验证，验证默克尔树。但是查询出的的receiptProof中的left和right都为空,请问什么情况下为空什么情况下不为空？

**To Reproduce**
2. Deploy Contract '....'
3. Call interface '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.2]
 - FISCO BCOS Version [e.g. 2.4.0]

**Additional context**

**Comment by cyjseagull** [comment]
如果一个区块中仅有1笔交易，left和right会是空的。

**Comment by chaunsin** [comment]
> 如果一个区块中仅有1笔交易，left和right会是空的。
非常感谢
