### ISSUE TITLE
节点读取系统参数合约value值出现乱码

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/FISCO-BCOS#234]
采用babel-node tool.js ConfigAction set 【参数名】 【参数值】方式修改系统参数，但是节点log显示读取参数值出错，具体为Client.cpp中Client::updateConfig()函数调用函数SystemContract::getValue(const string _key, string & _value)读取合约数值出现乱码。具体读取value位置以及对应乱码与非乱码数值如下图，还请帮忙分析下是何种原因导致。
![image](https://user-images.githubusercontent.com/25951395/45990428-d1b7de80-c0b2-11e8-9d4d-d97b0f542163.png)

![image](https://user-images.githubusercontent.com/25951395/45990478-117ec600-c0b3-11e8-9191-1af17e72b8d7.png)

![image](https://user-images.githubusercontent.com/25951395/45990507-3115ee80-c0b3-11e8-8e34-96397014ba54.png)

**Comment by JimmyShi22** [comment]
是个bug：系统合约参数设置失败，系统合约内的参数需要未同步
