### ISSUE TITLE
龙芯 loongarch64  因libvrf无法编译

### ISSUE THREAD

**Issue by kumakichi** [FISCO-BCOS/FISCO-BCOS#2348]
```
# cat /proc/cpuinfo 
system type             : generic-loongson-machine
processor               : 0
package                 : 0
core                    : 0
cpu family              : Loongson-64bit
model name              : Loongson-3A5000HV
```

```
# uname -a
Linux localhost 4.19.190-2.lns8.loongarch64 #1 SMP Sat Sep 18 06:47:40 UTC 2021 loongarch64 loongarch64 loongarch64 GNU/Linux
```

我们尝试在龙芯3a 5000上面编译，遇到的一些问题都尽力解决了，最后链接的时候出了问题:
![link error](https://s01.geekpic.net/di-4L7RLM.png)

预编译的 libffi_vrf只看到arm64,x86-64和m1的，龙芯的可否提供一份，如果源码不能提供的话？谢谢

**Comment by cyjseagull** [comment]
libffi_vrf的源码可参考这里： https://github.com/WeBankBlockchain/WeDPR-Lab-Crypto/tree/wedpr-tools

**Comment by kumakichi** [comment]
[libffi_vrf_split.a.zip.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/8698263/libffi_vrf_split.a.zip.zip)
[libffi_vrf_split.a.z01.zip](https://github.com/FISCO-BCOS/FISCO-BCOS/files/8698264/libffi_vrf_split.a.z01.zip)

因为Loongnix 8.3 系统自带的rust是1.41的，这里贴一个我们编译好的

因github文件大小限制，做了分卷，下载后去掉文件末尾的.zip解压即可

**Comment by channingduan** [comment]
@kumakichi 请问下你在龙芯上面编译完成了吗?

**Comment by channingduan** [comment]
> target

cpu family: Loongson-64bit
model name: Loongson-3C5000L

我在 3C5000L 上编译的时候,很多依赖都异常,我再尝试下.
