### ISSUE TITLE
BCOS部署问题 一键部署和创世节点部署有区别？

### ISSUE THREAD

**Issue by Blackcatfish** [FISCO-BCOS/FISCO-BCOS#238]
https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/sample 这个文档部署的链和创世节点那个一样吗  线上使用有没有什么问题

**Comment by JimmyShi22** [comment]
部署节点，看这里，比较全：
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/index.html

**Comment by JimmyShi22** [comment]
你提到的那个文档是个举例，不能用在线上使用

**Comment by wheatli** [comment]
@Blackcatfish Sample中的例子主要是为了给用户快速部署出一条测试链，如果需要在生产环境部署请参考https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tools/index.html的“企业搭链工具（物料包）”章节
