### ISSUE TITLE
Mac M1架构 启动console报错

### ISSUE THREAD

**Issue by littleha233** [FISCO-BCOS/FISCO-BCOS#2405]
前面安装过程一切顺利，安装完成后，节点可以正常启动；
然后准备启动控制台，使用启动指令`bash start.sh`后提示如下信息

<img width="1300" alt="截屏2022-04-29 上午11 06 58" src="https://user-images.githubusercontent.com/27888033/165879525-2444e8cf-1964-4312-bd8c-3466e209efb4.png">
；
按照错误提示尝试更换/console/lib中的netty相关的文件，具体是netty-all-4.1.53.Final.jar更新成了netty-all-4.1.75.Final，虽然依然不能启动，但是错误信息更改为如下

<img width="825" alt="截屏2022-04-29 上午11 10 27" src="https://user-images.githubusercontent.com/27888033/165879765-acb27806-ec71-49e9-a179-86767e7574ac.png">

网上的做法是使用netty-tcnative-boringssl-static.2.0.42.Final及以上的版本，但是我看Bcos中没有引用到这个库。

所以想请教下Mac M1架构如何解决这个问题，谢谢。
注：在Intel x86架构下正常运行的文件迁移到M1下，就会出现上述问题。

**Comment by cyjseagull** [comment]
- 在M1中安装x86_64的java可以正常使用console
- 即将发布的2.9.0会全面支持M1
