### ISSUE TITLE
按参考文档中快速开始部署出现“非法指令（核心已转储）”

### ISSUE THREAD

**Issue by YuxinLi1** [FISCO-BCOS/FISCO-BCOS#2442]
![2](https://user-images.githubusercontent.com/34358935/168479409-9d4f83ab-4594-4e1c-af7e-6c78f85322c0.png)

**Comment by YuxinLi1** [comment]
改为release-2.7.0后可以正常运行，是否v2.9.0版本二进制文件存在错误或者需要安装其他的依赖吗？

**Comment by ywy2090** [comment]
这个问题已经解决，可以重新搭建2.9.0的链即可

**Comment by ywy2090** [comment]
如果还有问题的话可以及时反馈
