### ISSUE TITLE
使用webase部署，提示缺少bin，如何排除解决？

### ISSUE THREAD

**Issue by zdfhub** [FISCO-BCOS/FISCO-BCOS#2471]
#描述
使用webase的合约IDE编写合约，编译合约后，bytecodeBin为空，点击部署，提示缺少bin

#环境
solidity 0.6.10
webase 2.8.0

#问题
请问出现这个问题的原因是什么，如何排除解决，感谢

**Comment by xiaoniaoyou0325** [comment]
大佬，这些方法和变量都是必须的，除了减少外还有别的办法吗，我和你症状一摸一样
