### ISSUE TITLE
BCOS可以使用metamask和remix吗

### ISSUE THREAD

**Issue by ohyemybaby** [FISCO-BCOS/FISCO-BCOS#25]
我可以通过remix编译智能合约，通过metamask连接测试网络，通过水龙头账户获取eth，然后部署合约，BCOS可以这样吗？

**Comment by toxotguo** [comment]
@ohyemybaby 
eth是以太坊公有链的原生代币。而bcos是去币化的联盟区块链平台，虽然支持账户模型，但没有原生代币，所以使用bcos平台搭建出来的区块链网络并不存在任何类似eth的原生代币。
metamask是连接以太坊网络的第三方钱包工具。并不能直接对接到bcos区块链。
bcos目前的虚拟机与以太坊一样，都是evm，智能合约语言都是solidity，所以remix编译的智能合约可以应用到bcos平台上面。

**Comment by ohyemybaby** [comment]
@toxotguo 关于代币和remix的答复，非常感谢。
这里metamask也是一个rpc工具，不能直接对接bcos的原理能否更细介绍一下，谢谢。

**Comment by toxotguo** [comment]
@ohyemybaby 
metamask与以太坊的对接遵循的是以太坊的RPC接口。BCOS的交易结构设计与以太坊不完全相同，因此BCOS的RPC接口规范与以太坊也不完全相同，所以当前的metamask不能直接对接BCOS。

**Comment by ohyemybaby** [comment]
我的理解，在BCOS上部署一个满足ERC20的Token的合约应该就可以使用metamask，只是由于某种原因，这个token不被提倡，谢谢@toxotguo的解答，谢谢

**Comment by evsward** [comment]
@ohyemybaby 您好，请问尝试成功了FISCO与metamask的打通吗？突然发现这个帖子已经四年之久了。我也同样遇到了这个问题，今天做web3的话，以太坊的生态以及技术栈例如metamask便捷的操作（发布合约、查看余额等），以及truffle集成编译工具等等，都是不可缺少的一环。
