### ISSUE TITLE
使用3.0版本建链，部署并启动RPC服务时，未创建ca证书

### ISSUE THREAD

**Issue by rabbitheng** [FISCO-BCOS/FISCO-BCOS#2547]
服务器：鲲鹏 4c 8G
操作系统：openEuler20.03
问题：使用3.0 Pro版本建链，Mysql数据库换成8.0，tar搭建正常并生成了token，部署并启动RPC服务时，ca证书创建失败，查询命令发现是执行生成ca.key时未生成该文件，但命令显示success，请问，我该如何继续下去？

**Comment by cyjseagull** [comment]
`build_chain.sh`依赖`tassl`生成证书，rc3版本没有上传`aarch64`的`tassl`，导致证书生成失败。

现在已经上传了`aarch64`的`tassl`，可以再尝试是否可以正常生成证书。

另外，fisco目前没有提供arm版本的二进制，如果在arm平台上运行fisco，需要手动编译二进制。

**Comment by rabbitheng** [comment]
十分感谢您的回复，明白了
