### ISSUE TITLE
调用合约方法使用extcodesize(addr)没有效果

### ISSUE THREAD

**Issue by cjo123** [FISCO-BCOS/FISCO-BCOS#2598]
**描述错误**
使用extcodesize(addr)判断是否为合约地址，传入外部地址size也返回大于0
**复制**
<img width="493" alt="微信6b3b7d4a80586a5363943ec2ae02c7a" src="https://user-images.githubusercontent.com/56211402/177707524-f6eb6c07-92f2-4714-b516-c2a6d283fad1.png">
<img width="648" alt="微信0e24cf423e9732b8a0270132bd99b942" src="https://user-images.githubusercontent.com/56211402/177707619-56f34216-b134-4a27-9aad-978747a9ff0b.png">

**Comment by morebtcg** [comment]
这是由于3.0版本在分布式架构下，单个EVM很难查询其他机器上EVM的合约代码大小，这个opcode会一直返回1，这个问题我们正在研究解决，也欢迎提出好的建议

**Comment by JimmyShi22** [comment]
Fixed in v3.1.0
