### ISSUE TITLE
按照文档指引，在5.5 启动节点出现错误  ERROR|2018-03-19 17:45:15:221|reloadMsg failed, return NotFound:  ERROR|2018-03-19 17:45:16:742|dfs init param invalid, null param exists ! ERROR|2018-03-19 17:45:16:742|init DfsFileServer failed !

### ISSUE THREAD

**Issue by langio** [FISCO-BCOS/FISCO-BCOS#26]

**Comment by juzix-kelvin** [comment]
这个错误是dfs模块没有配置， 这个不影响使用区块链系统核心功能， 如果你需要dfs能力， 可以在配置文件对应加上， 详细指导文档里面可以参考

**Comment by langio** [comment]
但这步节点启动不成功，系统中只有在nodedata-1目录中启动的进程，nodedata-2中启动的没有

**Comment by juzix-kelvin** [comment]
@langio 那需要具体提供一些启动不成功的日志信息， 另外你应该是两个节点， 是节点1还是节点2没启动呢 ？

**Comment by langio** [comment]
节点2启动失败，有如下的warn日志
WARNING|2018-03-19 17:45:15:191|open m_blocksDB result:OK
WARNING|2018-03-19 17:45:15:199|open m_extrasDB result:OK
WARNING|2018-03-19 17:45:15:214|SystemContract::getNodeFromContract No NodeAction!!!!!!!!!!!!
WARNING|2018-03-19 17:45:15:214|SystemContract::updateCa No CAAction!!!!!!!!!!!!
WARNING|2018-03-19 17:45:15:214|[SystemContract::updateContractAbiInfo] update contract abi info ,but contract mgr address is zero
WARNING|2018-03-19 17:45:16:724|Disconnect (reason: Unexpected identity given.)
WARNING|2018-03-19 17:45:16:724|Closing 0.0.0.0:0(Disconnect was requested.)
WARNING|2018-03-19 17:45:16:724|EthereumPeer::~EthereumPeer
WARNING|2018-03-19 17:45:16:833|Exception in Network Thread:boost::random_device: error while reading random-number pseudo-device : Resource temporarily unavailable
WARNING|2018-03-19 17:45:16:833|Network Restart is Recommended.

trace日志
TRACE|2018-03-19 17:45:15:199|Opened blockchain DB. Latest: 4e5c606d31a73f93c2d1fbbb91256dccc6df1e7486cb19bf4fd743ffd44a519d(rebuild not needed)
TRACE|2018-03-19 17:45:15:199|NonceCheck::updateCache m_startblk=0,m_endblk=0,prestartblk=0,preendblk=0,_rebuild=1
TRACE|2018-03-19 17:45:15:199|NonceCheck::updateCache cache size=0,cost0.014
TRACE|2018-03-19 17:45:15:199|BlockQueue::verifierBody
TRACE|2018-03-19 17:45:15:206|Opened state DB.
TRACE|2018-03-19 17:45:15:207|startedWorking()
TRACE|2018-03-19 17:45:15:214|SystemContract::updateSystemContract m_systemproxyaddress=919868496524eedc26dbb81915fa1547a20f8998,number=0,9378f0d715da28e06a81c8233f8d5320d35371d9c1e1a35f305cbc6ed7a72197 0000000000000000000000000000000000000000000000000000000000000000 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347 540a1ef64dfdc3aeb26a53774dec73aacfe0d55a 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0 0 5497558138880000 0 0
TRACE|2018-03-19 17:45:15:214|SystemContract::updateSystemContract blocknumber=1
TRACE|2018-03-19 17:45:15:214|SystemContract::call gas=2000000000,gasPrice=100000000,nonce=1562978464
TRACE|2018-03-19 17:45:15:214|Block::execute 49ec761d30c0deb014dcd643c8cf5bab6a080cb210d2d9d944cd24651db9dd7f
TRACE|2018-03-19 17:45:15:214|State::execute 
TRACE|2018-03-19 17:45:15:214|SystemContract::updateRoute RouteSize0
TRACE|2018-03-19 17:45:15:214|SystemContract::updateNode  m_nodelist.size=0
TRACE|2018-03-19 17:45:15:214|SystemContract::updateSystemContract took:247
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|SystemContract::getValue NO ConfigAction!
TRACE|2018-03-19 17:45:15:214|Client::Client m_maxBlockTranscations：1000
TRACE|2018-03-19 17:45:15:214|Client::Client sealEngine() m_intervalBlockTime：1000
TRACE|2018-03-19 17:45:15:214|Client::Client BlockHeader::maxBlockHeadGas：2000000000
TRACE|2018-03-19 17:45:15:214|Client::Client TransactionBase::maxTranscationGas:30000000
TRACE|2018-03-19 17:45:15:214|Client::Client NonceCheck::maxNonceCheckBlock:1000
TRACE|2018-03-19 17:45:15:214|Client::Client BlockChain::maxBlockLimit:1000
TRACE|2018-03-19 17:45:15:214|Client::Client BlockChain::CAVerify:0
TRACE|2018-03-19 17:45:15:214|SystemContract::getAllNode _blocknumber=-1,m_tempblock.info().number()=1,m_nodelist.size()=0
TRACE|2018-03-19 17:45:15:215|NodeConnParamsManager::getAllNodeConnInfo=-1
TRACE|2018-03-19 17:45:16:716|NodeTable::addNode ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6,1
TRACE|2018-03-19 17:45:16:716|NodeTable::noteActiveNode ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6,127.0.0.1:30303
TRACE|2018-03-19 17:45:16:717|NodeConnParamsManager::connNodeenode://ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6@127.0.0.1:30303 Valid=1
TRACE|2018-03-19 17:45:16:717|NodeConnParamsManager::connNode startenode://ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6@127.0.0.1:30303 Valid=1
TRACE|2018-03-19 17:45:16:717|Host::addPeerenode://ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6@127.0.0.1:30303
TRACE|2018-03-19 17:45:16:717|Host::addPeer Required
TRACE|2018-03-19 17:45:16:717|Host::requirePeeree2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6
TRACE|2018-03-19 17:45:16:717|NodeTable::addNode ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6,1
TRACE|2018-03-19 17:45:16:717|NodeTable::noteActiveNode ee2b3ec7312743796183c0d376ba5e6171763c32dc1803d3f41ad69577bd8cd5c0e244f593d6f85914f2c3fd623e9da918a55ae934a8f15cf075de7a8e82a6e6,127.0.0.1:30303
TRACE|2018-03-19 17:45:16:724|EthereumHost::newPeerCapability totalDifficulty=0,number=0

debug日志
DEBUG|2018-03-19 17:45:15:221|Try to delete not-exist, hash=9378f0d715da28e06a81c8233f8d5320d35371d9c1e1a35f305cbc6ed7a72197
DEBUG|2018-03-19 17:45:15:221|Try to delete not-exist, hash=9378f0d715da28e06a81c8233f8d5320d35371d9c1e1a35f305cbc6ed7a72197
DEBUG|2018-03-19 17:45:16:716|RLPXSocket::m_socketType:0
DEBUG|2018-03-19 17:45:16:717|RLPXSocket::m_socketType:0
DEBUG|2018-03-19 17:45:16:717|WebThreeDirect::addPeer 
DEBUG|2018-03-19 17:45:16:817|RLPXSocket::m_socketType:0

**Comment by JimmyShi22** [comment]
先把两个的系统合约改成0x0，让两个都能正常出块，再配置上系统合约。试试看能不能往下继续？

**Comment by mfcui** [comment]
node1的改为0x0直接报 发送失败，找不到节点错误了

**Comment by JimmyShi22** [comment]
两个nodedata下的fisco-bcos.log看看启动报什么错？
