### ISSUE TITLE
tikv的client-c链接问题

### ISSUE THREAD

**Issue by zzl133** [FISCO-BCOS/FISCO-BCOS#2600]
**Describe the bug**
用FISCO仓库里的client-c编译生成的libkv_client.a在我测试程序里链接编译出现很多未定义错误
![image](https://user-images.githubusercontent.com/9711474/177733893-d4b9b5b3-17b8-4242-8717-b6ee96360520.png)
这种如何解决呢，其中grpc是编译的动态库，我这边查看头文件和库目录都在cmakelist包含了。

**Comment by bxq2011hust** [comment]
看起来是没有链接它依赖的kvproto
你用这个client是做什么呢？

**Comment by zzl133** [comment]
用这个client-c的静态库集成到我这边的项目呢 也是c++写的联盟链，要兼容tikv，我看咱们这已经兼容了，但是不知道怎么用的 编译相关的也没文档 只有看makefile里编译选项有链接kv_client库

**Comment by bxq2011hust** [comment]
> 

他这个c-sdk不太完善，有坑在里面，你往我邮箱发个微信，我们加个微信聊吧

**Comment by JimmyShi22** [comment]
v3.1.0 已更换为rust client，相对来说更稳定了
