### ISSUE TITLE
FISCO-BCOS 支持以 websocket 方式观察区块链更动吗

### ISSUE THREAD

**Issue by ShawTim** [FISCO-BCOS/FISCO-BCOS#262]
在 `web3.js` 中我们是可以使用 [subscribe](https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html)  去观察区块链更改
但 FISCO-BCOS 并没有提供 websocket 接口
像 [go-eth](https://github.com/ethereum/go-ethereum) 它們是有提供的

我看到 FISCO-BCOS 提供了一个叫 [AMOP](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/features/AMOP/README.html) 的协议，但文档不足，只有一个类似 HelloWorld 的例子
我试着用 tcpdump 去监听 AMOP 的接口 `channelPort` (顺便也看下 `p2pport`)，但基本上该接口没有任何通讯来往

想问下我可以用甚麽方法每当区块链有更动的时候可以接收到相关的讯息？

**Comment by wheatli** [comment]
提供了RPC接口和Channel接口，分别用RPC访问的方式或者用web3sdk的AMOP协议，都可以获取链上的变动信息

**Comment by codeAndxv** [comment]
> 提供了RPC接口和Channel接口，分别用RPC访问的方式或者用web3sdk的AMOP协议，都可以获取链上的变动信息

这种方式是指使用一个定时任务不停的查询区块高度吗？ 和想要达到的监听目的不同

**Comment by bxq2011hust** [comment]
> > 提供了RPC接口和Channel接口，分别用RPC访问的方式或者用web3sdk的AMOP协议，都可以获取链上的变动信息
> 
> 这种方式是指使用一个定时任务不停的查询区块高度吗？ 和想要达到的监听目的不同

可以轮询获取导块高，如果使用FISCO BCOS 2.0的话，节点会使用channel的协议向SDK推送区块上链的消息

**Comment by TXZdream** [comment]
我在使用正在开发的go的sdk时，有没有办法使用这个AMOP协议呢？

**Comment by bxq2011hust** [comment]
> 我在使用正在开发的go的sdk时，有没有办法使用这个AMOP协议呢？

go-sdk暂不支持channel协议，所以也无法支持AMOP协议。
