### ISSUE TITLE
rc3版本多群组部署，其中节点服务都起来了，但是其中一个节点连接client的时候报错说不在group中

### ISSUE THREAD

**Issue by jiangwenfei** [FISCO-BCOS/FISCO-BCOS#2712]
**Describe the bug**
92节点在group0中，92节点的rpc、gateway、node三个服务都起来了，端口也是能正常连接的，但是getGroupPeers查看，发现92没有在当前group中.92节点的连接创建client报错
![241660129204_ pic](https://user-images.githubusercontent.com/13798938/183885960-1e4be560-4c35-4d4b-81c1-2d5f2ead2bed.jpg)
![251660129220_ pic](https://user-images.githubusercontent.com/13798938/183885959-317517c0-c33f-4bca-925f-3cbb5ae8aa00.jpg)
![261660129488_ pic](https://user-images.githubusercontent.com/13798938/183886244-0e52bf3b-0c68-4a97-9fd1-5495501e5a0c.jpg)

**Comment by cyjseagull** [comment]
通过`getSealerList`/`getObserverList`确认92节点是否是观察节点或共识节点；若其不在观察节点和共识节点列表，可通过连接其他机构的rpc服务，将其先加入为观察节点。

**Comment by jiangwenfei** [comment]
> 通过`getSealerList`/`getObserverList`确认92节点是否是观察节点或共识节点；若其不在观察节点和共识节点列表，可通过连接其他机构的rpc服务，将其先加入为观察节点。

![image](https://user-images.githubusercontent.com/13798938/184269435-aa5989d8-c488-422a-b1c9-eee2e2882e64.png)
通过getSealerList查看到92节点在共识列表中，接下来应该怎么排查呢

**Comment by jiangwenfei** [comment]
经过bcos大佬解答，重启tars容器，节点恢复正常
