### ISSUE TITLE
在3.0.0 air中如何使用JSON RPC

### ISSUE THREAD

**Issue by saiwg** [FISCO-BCOS/FISCO-BCOS#2718]
在2.0中有jsonRpc(默认8545)的配置，在3.0 air中是没有了，那么在3.0 air中如何使用json rpc
比如：
`
curl -X POST --data '{"jsonrpc":"2.0","method":"getClientVersion","params":[],"id":1}' http://127.0.0.1:8545
`
3.0.0-rc4 air的配置
[p2p]
    listen_ip=0.0.0.0
    listen_port=30300
    ; ssl or sm ssl
    sm_ssl=true
    nodes_path=./
    nodes_file=nodes.json
[rpc]
    listen_ip=0.0.0.0
    listen_port=20200
    thread_count=16
    ; ssl or sm ssl
    sm_ssl=true
    ;ssl connection switch, if disable the ssl connection, default: false
    ;disable_ssl=true

2.0的配置

[rpc]
    channel_listen_ip=0.0.0.0
    jsonrpc_listen_ip=0.0.0.0
    channel_listen_port=20200
    jsonrpc_listen_port=8545
[p2p]
    listen_ip=0.0.0.0
    listen_port=30300
    ; nodes to connect
    node.0=127.0.0.1:30300
    node.1=127.0.0.1:30301
    node.2=127.0.0.1:30302
    node.3=127.0.0.1:30303

**Comment by chuwen95** [comment]
3.0的RPC端口就是Channel端口，另外3.0的HTTP Server默认开启SSL，按照你的配置文件，可以按如下发送命令：
```
curl -k --cert sdk/sdk.crt --key sdk/sdk.key -X POST --data '{"jsonrpc":"2.0","method":"getBlockNumber","params":["group0","node0"],"id":1}' https://127.0.0.1:20200 | jq
```
或者直接关闭rpc的ssl功能，方法为取消注释节点配置文件config.ini中[rpc]域下的;disable_ssl=true注释
然后使用如下命令发送请求：
```
curl -X POST --data '{"jsonrpc":"2.0","method":"getBlockNumber","params":["group0","node0"],"id":1}' http://127.0.0.1:20200 | jq
```

**Comment by saiwg** [comment]
好的，谢谢
