### ISSUE TITLE
关于SystemProxy.sol和CNS

### ISSUE THREAD

**Issue by helllyf** [FISCO-BCOS/FISCO-BCOS#281]
当使用CNS时，系统从SystemProxy找到ContractAbiMgr的地址，再从ContractAbiMgr里面找到需要执行的合约的所有信息。那为什么不把SystemProxy.sol设计成ContractAbiMgr.sol这样的合约？

**Comment by ywy2090** [comment]
CNS模块只是系统合约的一个模块，所以是系统合约SystemProxy的一个部分。

**Comment by bxq2011hust** [comment]
很久没有回复啦，先关闭issue，如果问题没有解决欢迎随时联系
