### ISSUE TITLE
v2.9.1编译错误

### ISSUE THREAD

**Issue by mskzj** [FISCO-BCOS/FISCO-BCOS#2816]
**Describe the bug**
编译错误
```
[100%] Linking CXX executable ../../bin/fisco-bcos
/home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/vrf_rpbft/VRFBasedrPBFTEngine.h:47: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
/home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/vrf_rpbft/VRFBasedrPBFTEngine.h:47: error: undefined reference to 'vtable for dev::consensus::VRFBasedrPBFTEngine'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
/home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
/home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
/home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
/usr/include/c++/9/bits/shared_ptr.h:510: error: undefined reference to 'typeinfo for dev::consensus::VRFBasedrPBFTEngine'
collect2: error: ld returned 1 exit status
make[2]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/build.make:150: bin/fisco-bcos] Error 1
make[1]: *** [CMakeFiles/Makefile2:2204: fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Environment (please complete the following information):**
 - OS: Ubuntu20.04.4
 - FISCO BCOS Version 2.9.1

**Additional context**

**Comment by ywy2090** [comment]
> **Describe the bug** 编译错误
> 
> ```
> [100%] Linking CXX executable ../../bin/fisco-bcos
> /home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/vrf_rpbft/VRFBasedrPBFTEngine.h:47: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
> /home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/vrf_rpbft/VRFBasedrPBFTEngine.h:47: error: undefined reference to 'vtable for dev::consensus::VRFBasedrPBFTEngine'
> /usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
> /home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
> /home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
> /home/bc/fisco2.9/FISCO-BCOS-2.9.1/libconsensus/rotating_pbft/RotatingPBFTEngine.h:34: error: undefined reference to 'VTT for dev::consensus::VRFBasedrPBFTEngine'
> /usr/include/c++/9/bits/shared_ptr.h:510: error: undefined reference to 'typeinfo for dev::consensus::VRFBasedrPBFTEngine'
> collect2: error: ld returned 1 exit status
> make[2]: *** [fisco-bcos/main/CMakeFiles/fisco-bcos.dir/build.make:150: bin/fisco-bcos] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2204: fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```
> 
> **Environment (please complete the following information):**
> 
> * OS: Ubuntu20.04.4
> * FISCO BCOS Version 2.9.1
> 
> **Additional context** Add any other context about the problem here.

这几个类没有虚析构函数，编译器版本比较高，检测比较严格，已经修复，可以使用master-2.0的代码
