### ISSUE TITLE
关于build.sh 执行脚本权限问题。

### ISSUE THREAD

**Issue by johnpangc** [FISCO-BCOS/FISCO-BCOS#282]
你们好，我在手工搭链的时候，遇到了权限问题，提示无法继续之后，文件为 build.sh ,系统：ubuntu 16.04. 代码位置为：“chmod +x scripts/install_deps.sh && sudo ./scripts/install_deps.sh"，加了 sudo 提权后可以继续运行，不知道其他朋友有没遇到类似问题。其实解决的办法也有：就是在实行 sh build.sh 之前先执行一次 sudo su 的提权操作。入ubuntu坑不久，多多指教

**Comment by JimmyShi22** [comment]
请提供一下错误状态

**Comment by bxq2011hust** [comment]
认为问题已经解决，关闭issue。如果还是有问题，欢迎随时再次打开
