### ISSUE TITLE
curd合约编写查询个数一直都是0

### ISSUE THREAD

**Issue by JueWei0208** [FISCO-BCOS/FISCO-BCOS#2910]
//如下两种方式都试了不行
function selectcount() public view returns (uint32) {
          Condition[] memory conditions=new Condition[](1);
          conditions[0].value="1";
          conditions[0].op=ConditionOP.GE;
          uint32 result=table.count(conditions);
          return result;
    }
  function selectcount() public view returns (uint32) {
          Condition[] memory conditions=new Condition[](1);
          uint32 result=table.count(conditions);
          return result;
    }

**Comment by kyonRay** [comment]
Hi @JueWei0208 ,
感谢提出issue，目前已经确认CRUD count接口存在bug，这个问题将在3.1.0版本解决。

**Comment by JimmyShi22** [comment]
3.1.0 已修复
