### ISSUE TITLE
对源码编译cmake时出问题

### ISSUE THREAD

**Issue by Dyson-c** [FISCO-BCOS/FISCO-BCOS#2917]
获取fisco时，进行cmake  ..一直会出现如下问题（hosts有配置github）
请问该如何解决这个问题呢
Error: Failed to download from mirror set:
https://github.com/boostorg/predef/archive/boost-1.79.0.tar.gz:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(788):
[DEBUG] Time in subprocesses: 120531653 us
[DEBUG] Time in parsing JSON: 2 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 114 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 2.009 min (120530410 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:24 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:249 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/boost-predef/c17a7256c1f86eab749e10b451dbf53d317afaf9/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:146 (include)

error: building boost-predef:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-predef
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-predef]+Build+error
Include '[boost-predef] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: b0ea874c7 2022-06-22 (3 months ago)

You can also use the prefilled template from /home/lab312/Dyson/FISCO_BFLC_DEMO/FISCO-BCOS/build/vcpkg_installed/vcpkg/issue_body.md.

-- Running vcpkg install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  /home/lab312/Dyson/FISCO_BFLC_DEMO/FISCO-BCOS/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /opt/cmake-3.21.4/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:21 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by chuwen95** [comment]
国内与github连通性比较差，又下载超时时间比较短，所以bcos依赖的boost下载很难成功，可以挂个科学上网再编译，或在win上挂个科学上网将https://github.com/boostorg/predef/archive/boost-1.79.0.tar.gz下载好再放到vcpkg/downloads下继续编译
