### ISSUE TITLE
节点没有退出网络的情况下，直接注销了证书。导致无法恢复节点证书

### ISSUE THREAD

**Issue by voizhou** [FISCO-BCOS/FISCO-BCOS#294]
第八章 证书注销
(5) 该节点已通过（7.3 节点退出网络）操作方法退出网络。
节点没有退出网络的情况下，直接注销了证书。导致无法恢复节点证书

**Comment by JimmyShi22** [comment]
是的！在当前版本下，在注销节点证书前，没有判断节点是否在共识列表中。所以目前在注销证书前，请先注销节点。之后更新的版本会解决这个问题。
