### ISSUE TITLE
the contract in 'FISCO-BCOS/tool/' have a interger overflow

### ISSUE THREAD

**Issue by thereksfour** [FISCO-BCOS/FISCO-BCOS#296]
The function `trans` in the file `FISCO-BCOS/tool/Ok.sol` which code look like fellow:
```
    function trans(uint num){
    	from.balance=from.balance-num;
    	to.balance+=num;
    	log.push(Translog("20170413",from.account,to.account,num));
    }
```
when setting  the num to a big number,it will cause a interger overflow. 
Does it matter?
THX :)

**Comment by JimmyShi22** [comment]
It doesn't matter. ```uint``` and ```int``` are aliases for ```uint256``` and ```int256```. See here: https://solidity.readthedocs.io/en/latest/types.html

**Comment by JimmyShi22** [comment]
That's true! It is a demo for testing. But we will fix it. Thanks!

**Comment by JimmyShi22** [comment]
Fixed
