### ISSUE TITLE
已连接但是无法共识问题

### ISSUE THREAD

**Issue by Tocalmdown** [FISCO-BCOS/FISCO-BCOS#299]
创建了四个节点。
执行/mydata/node1/log/* | grep "topics Send to"，部分日志如下：
TRACE|2018-10-31 14:26:38:104|topics Send tofd878a27…@127.0.0.1:30303
TRACE|2018-10-31 14:26:38:105|topics Send to41221c77…@127.0.0.1:30305
TRACE|2018-10-31 14:26:38:105|topics Send to6d0a367c…@127.0.0.1:30306
TRACE|2018-10-31 14:26:38:105|topics Send to:3 nodes
TRACE|2018-10-31 14:26:39:106|topics Send tofd878a27…@127.0.0.1:30303
TRACE|2018-10-31 14:26:39:106|topics Send to41221c77…@127.0.0.1:30305
TRACE|2018-10-31 14:26:39:106|topics Send to6d0a367c…@127.0.0.1:30306
TRACE|2018-10-31 14:26:39:106|topics Send to:3 nodes
TRACE|2018-10-31 14:26:40:107|topics Send tofd878a27…@127.0.0.1:30303
TRACE|2018-10-31 14:26:40:107|topics Send to41221c77…@127.0.0.1:30305
TRACE|2018-10-31 14:26:40:107|topics Send to6d0a367c…@127.0.0.1:30306
TRACE|2018-10-31 14:26:40:107|topics Send to:3 nodes
TRACE|2018-10-31 14:26:41:107|topics Send tofd878a27…@127.0.0.1:30303
TRACE|2018-10-31 14:26:41:107|topics Send to41221c77…@127.0.0.1:30305
TRACE|2018-10-31 14:26:41:107|topics Send to6d0a367c…@127.0.0.1:30306
TRACE|2018-10-31 14:26:41:107|topics Send to:3 nodes

执行tail -f /mydata/node1/log/* |grep +++
无任何输出

刚入坑不久，请多多指教，谢谢！

**Comment by Tocalmdown** [comment]
补充：最新的info_log_2018103114.log

INFO|2018-10-31 14:48:56:869|Recv GetAnnouncementHashPacket From 41221c77…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:48:56:869| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:49:00:412|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30303:30303
INFO|2018-10-31 14:49:00:412|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30304:30304
INFO|2018-10-31 14:49:00:412|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30305:30305
INFO|2018-10-31 14:49:00:412|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30306:30306
INFO|2018-10-31 14:49:00:414|updateBootstrapnodes:  {"nodes":[{"host":"127.0.0.1","p2pport":"30303"},{"host":"127.0.0.1","p2pport":"30304"},{"host":"127.0.0.1","p2pport":"30305"},{"host":"127.0.0.1","p2pport":"30306"}]}

INFO|2018-10-31 14:49:00:414|Send Announcement To 41221c77…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:00:414|Send Announcement To fd878a27…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:00:415|Send Announcement To bebe5467…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:29:636|Recv GetAnnouncementHashPacket From fd878a27…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:29:636| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:49:48:760|Recv GetAnnouncementHashPacket From bebe5467…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:48:760| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:49:56:953|Recv GetAnnouncementHashPacket From 41221c77…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:49:56:953| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:50:00:503|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30303:30303
INFO|2018-10-31 14:50:00:503|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30304:30304
INFO|2018-10-31 14:50:00:503|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30305:30305
INFO|2018-10-31 14:50:00:503|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30306:30306
INFO|2018-10-31 14:50:00:504|updateBootstrapnodes:  {"nodes":[{"host":"127.0.0.1","p2pport":"30303"},{"host":"127.0.0.1","p2pport":"30304"},{"host":"127.0.0.1","p2pport":"30305"},{"host":"127.0.0.1","p2pport":"30306"}]}

INFO|2018-10-31 14:50:00:504|Send Announcement To 41221c77…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:00:504|Send Announcement To fd878a27…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:00:504|Send Announcement To bebe5467…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:29:728|Recv GetAnnouncementHashPacket From fd878a27…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:29:728| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:50:48:854|Recv GetAnnouncementHashPacket From bebe5467…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:48:855| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:50:57:033|Recv GetAnnouncementHashPacket From 41221c77…,hash=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5,Our=b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:50:57:033| AnnouncementHash Is Same.Don't Need Send AnnouncementPacket
INFO|2018-10-31 14:51:00:575|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30303:30303
INFO|2018-10-31 14:51:00:575|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30304:30304
INFO|2018-10-31 14:51:00:575|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30305:30305
INFO|2018-10-31 14:51:00:575|NodeConnParamsManagerSSL::updateAllConnect name=127.0.0.1:30306:30306
INFO|2018-10-31 14:51:00:576|updateBootstrapnodes:  {"nodes":[{"host":"127.0.0.1","p2pport":"30303"},{"host":"127.0.0.1","p2pport":"30304"},{"host":"127.0.0.1","p2pport":"30305"},{"host":"127.0.0.1","p2pport":"30306"}]}

INFO|2018-10-31 14:51:00:576|Send Announcement To 41221c77…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:51:00:576|Send Announcement To fd878a27…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5
INFO|2018-10-31 14:51:00:576|Send Announcement To bebe5467…,Our= b9ff52fbca4ecbce79d277d3ac5edf727d51e7624eac62a028ee0948779a3bf5

**Comment by Tocalmdown** [comment]
error日志无错误

**Comment by Tocalmdown** [comment]
启动节点时报错：
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/errors.js:35:16)
    at HttpProvider.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/httpprovider.js:83:22)
    at RequestManager.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/requestmanager.js:58:32)
    at Eth.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/method.js:145:58)
    at SolidityFunction.call (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/function.js:112:32)
    at SolidityFunction.execute (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/function.js:223:22)
    at getAction (/mydata/FISCO-BCOS/tools/systemcontract/tool.js:54:29)
    at Object.<anonymous> (/mydata/FISCO-BCOS/tools/systemcontract/tool.js:194:22)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at loader (/usr/lib/node_modules/babel-cli/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)

**Comment by Tocalmdown** [comment]
启动节点时报错：

Error: Invalid JSON RPC response: undefined
at Object.InvalidResponse (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/errors.js:35:16)
at HttpProvider.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/httpprovider.js:83:22)
at RequestManager.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/requestmanager.js:58:32)
at Eth.send (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/method.js:145:58)
at SolidityFunction.call (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/function.js:112:32)
at SolidityFunction.execute (/mydata/FISCO-BCOS/tools/systemcontract/node_modules/_web3@0.17.0-beta@web3/lib/web3/function.js:223:22)
at getAction (/mydata/FISCO-BCOS/tools/systemcontract/tool.js:54:29)
at Object. (/mydata/FISCO-BCOS/tools/systemcontract/tool.js:194:22)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at loader (/usr/lib/node_modules/babel-cli/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)

error_log_2018103115.log日志报错：

ERROR|2018-10-31 15:09:06:423|dfs init param invalid, null param exists !
ERROR|2018-10-31 15:09:06:437|getAccountType error......

**Comment by JimmyShi22** [comment]
Error: Invalid JSON RPC response: undefined
节点RPC的URL没指定正确，默认是127.0.0.1:8545
这样操作进行设置：
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/usage/tools.html#id11

**Comment by bxq2011hust** [comment]
长时间没有回复，关闭issue。如果问题没有解决，欢迎再次打开。
