### ISSUE TITLE
build_chain.sh用docker方式部署报错

### ISSUE THREAD

**Issue by Asongguo** [FISCO-BCOS/FISCO-BCOS#3051]
使用的镜像是fiscoorg/fiscobcos:v3.0.1

报错日志：

{"log":"/usr/local/bin/fisco-bcos: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory\n","stream":"stderr","time":"2022-10-28T01:44:39.540576646Z"}

看样子是镜像少依赖了

**Comment by idefa** [comment]
version: '3'
services:
  chain-node0:
    image: fiscoorg/fiscobcos:v3.0.1
    container_name: chain-node0
    working_dir: /data
    command:  -c config.ini -g config.genesis
    volumes:
      - ./nodes/172.25.0.2/node0:/data
      - ./nodes/172.25.0.2/fisco-bcos:/usr/local/bin/fisco-bcos
    ports:
      - "30300:30300"
      - "8545:8545"
      - "20200:20200"

**Comment by idefa** [comment]
少挂载了二进制文件

**Comment by JimmyShi22** [comment]
3.1.0 修复

**Comment by JimmyShi22** [comment]
已修复
