### ISSUE TITLE
FISCO BCOS v3.0.1验证不出address地址是EOA还是合约地址，即将address地址均验证为合约地址

### ISSUE THREAD

**Issue by hongfish** [FISCO-BCOS/FISCO-BCOS#3118]
- Address合约

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/docs-v3.x/contracts/utils/Address.sol
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Address.sol

- VerifyAddr 合约

VerifyAddr.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.10;
import "./utils/Address.sol";

contract VerifyAddr {

    using Address for address;

    function verify(address addr) public view returns(bool) {
        return addr.isContract();
    }

}
```
VerifyAddr2.sol
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.1;
import "./utils/Address.sol";

contract VerifyAddr2 {

    using Address for address;

    function verify(address addr) public view returns(bool) {
        return addr.isContract();
    }

}
```

- Remix验证

0.6.10版验证

<img width="415" alt="image" src="https://user-images.githubusercontent.com/10834073/201914230-4ef50f26-10fc-4f13-92d3-3b0cc1d55ff7.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10834073/201914375-37ea8683-6841-4a8d-9271-4a5b9edc9eb9.png">

0.8.1版验证
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10834073/201914511-f4bceb61-316c-44d8-b0f3-4e85ab564522.png">
<img width="415" alt="image" src="https://user-images.githubusercontent.com/10834073/201914593-df520bc7-44fd-4115-b0b3-f68992839cdb.png">

- FISCO BCOS v2.8.0验证

**0.6.10版验证**

使用合约VerifyAddr.sol部署后的合约地址进行验证，应该返回true，交易回执返回true
使用私钥用户的地址进行验证，应该返回false，交易回执返回false

结论：Fisco bcos v2.8.0验证address是EOA还是合约地址，验证正确。

- FISCO BCOS V3.0.1验证

**0.6.10版验证**

使用合约VerifyAddr.sol部署后的合约地址进行验证，应该返回true，交易回执返回true
使用私钥用户的地址进行验证，应该返回false，交易回执返回true

结论：Fisco bcos v3.0.1验证address是EOA还是合约地址，验证错误。

**0.8.1版验证**

使用合约VerifyAddr2.sol部署后的合约地址进行验证，应该返回true，交易回执返回true
使用私钥用户的地址进行验证，应该返回false，交易回执返回true

结论：Fisco bcos v3.0.1验证address是EOA还是合约地址，验证错误。

**Comment by wheatli** [comment]
谢谢反馈，3.1版本将修复

**Comment by JimmyShi22** [comment]
3.1.0 已修复

**Comment by hongfish** [comment]
用FISCO BCOS v3.1.0进行验证：
1、验证合约地址，返回空值
![image](https://user-images.githubusercontent.com/10834073/203733368-c3015523-5427-4ff6-88b3-dc85448c7410.png)

2、验证EOA，返回error
![image](https://user-images.githubusercontent.com/10834073/203733676-d8064730-6fa3-4790-8156-fa22fb1143f7.png)
