### ISSUE TITLE
How to sort Transactions in one Block in v3.0 ？

### ISSUE THREAD

**Issue by toby1991** [FISCO-BCOS/FISCO-BCOS#3141]
Which key should I rely on to `sort` all the `Transaction`s in one `Block` in `v3.0` ?

As we all known, In `v2.x`, We have a key named `TransactionIndex`, which we could use to sort the txs in one block, BUT I CAN'T  GET IT IN 3.0 !!!

**Comment by JimmyShi22** [comment]
Thanks for issue! 
May I ask where to use TransactionIndex in your scnario ?

**Comment by toby1991** [comment]
> Thanks for issue! May I ask where to use TransactionIndex in your scnario ?

There are two TXs change the same variable's value in one contract in a single block, which TX's value should be the final state after this block?

**Comment by JimmyShi22** [comment]
Because FISCO BCOS use DMC algorithm, some txs may not be executed as the orders in the block.
If we just want to debug, we can update config.ini log to `trace` level and see how txs in block executed !
``` bash
cat log_xxxx.log |grep -iaE "scheduler|report" 
```
