### ISSUE TITLE
按照官方教程，bash contract2java.sh solidity -p org.fisco.bcos.asset.contract失败

### ISSUE THREAD

**Issue by zhangtalent** [FISCO-BCOS/FISCO-BCOS#3145]
**Describe the bug**
按照官方教程，bash contract2java.sh solidity -p org.fisco.bcos.asset.contract失败

ERROR stack: 
console.contract.exceptions.CompileContractException: *** Analysis evm bytecode TableTest.sol failed *** 
 error: base64: invalid argument -
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)

	at console.contract.utils.ContractCompiler.compileSolToBinAndAbi(ContractCompiler.java:246)
	at console.contract.utils.ContractCompiler.compileSolToBinAndAbi(ContractCompiler.java:151)
	at console.common.ConsoleUtils.compileSolToJava(ConsoleUtils.java:321)
	at console.common.ConsoleUtils.compileAllSolToJava(ConsoleUtils.java:367)
	at console.common.ConsoleUtils.main(ConsoleUtils.java:780)
*** Compile solidity Crypto.sol*** 

**Environment (please complete the following information):**
 - macos
 - FISCO BCOS 3.0.1
 - java14

**Comment by kyonRay** [comment]
Hi @zhangtalent ,
这个应该是Solidity静态分析出现的错误。在3.1.0的控制台新增了 -n 的选项手动关闭静态分析，可以临时避免错误。:)

**Comment by bxq2011hust** [comment]
```bash
vim /Users/$USER/.fisco/evm_static_analysis_macOS.sh
# 修改第74行为下面的形式
echo ${base64_tar} | base64 -d > ${tools_tar}
```

**Comment by zhangtalent** [comment]
> Hi @zhangtalent , 这个应该是Solidity静态分析出现的错误。在3.1.0的控制台新增了 -n 的选项手动关闭静态分析，可以临时避免错误。:)

感谢回复

**Comment by zhangtalent** [comment]
> 感谢反馈，我验证了下，macOS 13上会有这个问题，macOS 12是ok的，会在下个版本更新下分析工具解决这个问题
> 
> ```shell
> vim ~/.fisco/evm_static_analysis_macOS.sh
> # 修改第74行为下面的形式
> echo ${base64_tar} | base64 -d > ${tools_tar}
> ```

感谢回复

**Comment by zhangtalent** [comment]
> > 感谢反馈，我验证了下，macOS 13上会有这个问题，macOS 12是ok的，会在下个版本更新下分析工具解决这个问题
> > ```shell
> > vim ~/.fisco/evm_static_analysis_macOS.sh
> > # 修改第74行为下面的形式
> > echo ${base64_tar} | base64 -d > ${tools_tar}
> > ```
> 
> 感谢回复

修改了74行，依然运行不了

**Comment by kyonRay** [comment]
初步确认是macOS 13.0版本改了base64的参数导致的报错，需要使用控制台3.1.0最新的包。链接：https://github.com/FISCO-BCOS/console/releases/download/v3.1.0/console.tar.gz

**Comment by JimmyShi22** [comment]
已修复
