### ISSUE TITLE
关于权限和隐私管理的问题

### ISSUE THREAD

**Issue by wzc2608** [FISCO-BCOS/FISCO-BCOS#317]
设想这样一种场景；某个角色A有权限查看和修改链上的数据但却不能利用该数据，另一个角色B可以使用该数据却无法查看和修改它；比如用户可以修改自己的电话号码，其他人看不到其电话号码的内容，却可以通过调用链上的函数来拨打电话。
这种场景下，如果角色B如果试图直接从区块数据去反推出链上数据，进而获知它没有权限得知的信息，这种情况是否有可能发生？如果可能，应该如何确保权限的生效？

**Comment by JimmyShi22** [comment]
这一类隐私的问题，都可以用零知识证明来解决。
可参考FISCO BCOS给出的[一对一匿名可监管转账场景](https://github.com/FISCO-BCOS/zkg-tx1to1)：
一笔匿名转账，转账的所有信息都是加密的，但可被链上的节点验证。匿名转账只对转账双方A和B和监管者G可见。一个人无法解密别人的资产，进而也不能花费别人的资产。自己的匿名资产只对自己可见，自己可支配。但所有的匿名转账都是对被监管者可见的。

零知识证明在区块链上使用，开发难度较大，设计相对复杂。

**Comment by wzc2608** [comment]
谢谢，我明白了，我大概看了一下，请问FISCO-BCOS的零知识证明库用的是zkSNARK算法嘛？这个算法应该只能保证交易双方的身份和金额的隐私，让攻击者无法对应任意俩笔交易，有什么办法能够对合约内容加密嘛？比如说用户的某些信息直接存在合约里。
