### ISSUE TITLE
3.0.1版本bcos尝试进行压力测试出现check failed

### ISSUE THREAD

**Issue by DiWangShePi** [FISCO-BCOS/FISCO-BCOS#3170]
**Describe the bug**
我在尝试对本地搭建的区块链网络进行压力测试，但结果出现大量的check failed
![Q1](https://user-images.githubusercontent.com/83491150/203927044-5d0d5d64-efc6-48e4-ac64-a9cf08c4196b.png)

**To Reproduce**
1. [搭建第一个区块链网络](https://fisco-bcos-doc.readthedocs.io/zh_CN/latest/docs/quick_start/air_installation.html)按照这个教程至第四步结束，如果都做完也会有一样的效果。
2. [压力测试指南](https://fisco-bcos-doc.readthedocs.io/zh_CN/latest/docs/develop/stress_testing.html)按照这一教程至第三步，在第三步配置文件之前，先进入dist目录，不然压力测试启动会失败。
3. 直接到最下方的压力测试，使用java -cp 'conf/:lib/*:apps/*' org.fisco.bcos.sdk.demo.perf.PerformanceDMC group 32 500000 20000命令启动一次测试。
4. 测试结束后便会出现上方图片中的结果。

**Expected behavior**
这样的问题是正常的吗？

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.04.1]
 - FISCO BCOS Version [3.0.1]
 - java sdk [openjdk 11.0.17]

**Comment by JimmyShi22** [comment]
可能交易池装不下了，有交易被丢弃，可以在配置文件里面把交易池改大再试试
