### ISSUE TITLE
3.0.1 一个服务binary 56M，3.1.0 一个服务binary 208M，哪不对？

### ISSUE THREAD

**Issue by toby1991** [FISCO-BCOS/FISCO-BCOS#3173]
怎么尺寸变化那么大，里面加了些啥？

**Comment by toby1991** [comment]
![image](https://user-images.githubusercontent.com/5897356/204071138-874f9350-2743-4cc3-b1d3-d2b7d40d4123.png)

**Comment by JimmyShi22** [comment]
3.2.0开始，release加上了debug info，会大一些
