### ISSUE TITLE
节点不能正常启动

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/FISCO-BCOS#319]
![1542275393](https://user-images.githubusercontent.com/6056769/48544643-02700380-e8ff-11e8-892e-c60e67d015ee.jpg)

**Comment by cristicmf** [comment]
1. 节点停了，再启动节点，节点无法启动
2. 节点停了，查看进程是否存在，确认进程不存在，节点仍然无法存在

**Comment by JimmyShi22** [comment]
一般情况下：DatabaseAlreadyOpen，一般是一个节点重复启动，或两个节点同时配置了一个相同的data目录。
极端情况下：经过检查，确认在启动前，另一个节点未占用data目录，而仍然报DatabaseAlreadyOpen异常（如上面的情况），则有很大的概率是leveldb损坏了，请重新搭链。
