### ISSUE TITLE
共识节点和观察者节点有什么区别？

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/FISCO-BCOS#323]
共识节点和观察者节点，分别是什么功能？有什么特点？两者是否可以转换

**Comment by HaoXuan40404** [comment]
共识节点sealer是参与共识的节点，节点的正常工作或是故障会影响区块链的健康度。
1.3的观察节点不参与共识，可以与其他节点正常通信，经过了证书准入。可以正常访问链上数据，但是故障与否不影响整条链。
2.0的观察节点除证书准入外还需要加入群组，功能和1.3节点相同。但是2.0中没有加入群组的节点无法访问群组内数据。
共识节点和观察者节点可以通过发交易的形式相互转换
