### ISSUE TITLE
fisco-bcos的节点有哪些类型

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/FISCO-BCOS#324]
fisco-bcos的节点有哪些类型呢？是否也有全节点和轻节点？

**Comment by lealLuo** [comment]
补充一点：
按照术语来分，可以分为创世节点和非创世节点。创世节点是链上的第一个节点，其他节点需要主动连接创世节点，其他后来生成的节点为非创世节点。

在合约代码中，有将节点分成：
1.核心节点
2.全节点
3.轻节点

但是没说具体该怎么使用。可以大概猜测对应关系，核心节点应该是权限比较高的，对应管理员节点，全节点对应运维节点，轻节点对应交易节点。

```js
// base.sol
    enum NodeType{
        None,
        Core,   // 核心 
        Full,   // 全节点 
        Light   //  轻节点 
    }

```

**Comment by bxq2011hust** [comment]
问

> 根据不同的分类方法，类型也不同。
> 按照是否参与共识，可以分为观察节点（没上链，不参与共识）和共识节点。
> 在共识节点中，可以细分为leader和follower，leader节点是PBFT和RAFT共识算法中为了保持一致性而产生的，leader节点负责记账，follower节点负责更新数据状态，保持分布式账本的一致性。
> 按照权限分，还有上帝节点（创世节点），管理员节点，运维节点，交易节点。
> 
> 至于是否有全节点和轻节点不是很清楚。
> 全节点和轻节点概念我觉得和钱包相关，但是fisco-bcos好像没有钱包这个概念。我像参与共识的节点需要进行验证，所以它们应该都是全节点。至于观察节点，我觉得可以勉强算是轻节点吧

是的fisco-bcos没有钱包的概念，观察节点也拥有全部数据，只是不参与共识，我认为不是轻节点

**Comment by bxq2011hust** [comment]
很长时间没有回复，我先关闭issue。如果问题没有解决，欢迎随时再次打开issue
