### ISSUE TITLE
如何搭建部署观察者节点？

### ISSUE THREAD

**Issue by pangxianhe** [FISCO-BCOS/FISCO-BCOS#333]
请问如何搭建部署观察者节点？部署好了后，如何对实时数据进行监管审计？

**Comment by JimmyShi22** [comment]
观察者节点，是不参与共识的节点。在节点第一次启动，但没入网（register）时，都是观察者节点，入网后，成为共识节点。
监管审计和链上的智能合约的实现有关，可以写一个智能合约，在实现功能的同时，包含监管审计的功能。

**Comment by cristicmf** [comment]
👍
