### ISSUE TITLE
fisco 3.0 中合约abi文件的kind是如何生成的？从而如何判断是否用dag？

### ISSUE THREAD

**Issue by ZDragonX** [FISCO-BCOS/FISCO-BCOS#3366]
想了解3版本有了dmc之后，dag如何判断是否可用的？
通过console代码发现dagAttribute是根据合约abi文件中的kind生成的，而kind的值是在evm_static_analysis_linux.sh脚本中生成。evm_static_analysis_linux.sh脚本没有具体代码逻辑描述如何生成kind的。
能麻烦提供一下代码链接或者讲述下什么情况下生成不同类型的kind值吗

**Comment by kyonRay** [comment]
https://github.com/FISCO-BCOS/evm-static-analysis
