### ISSUE TITLE
节点日志重复DownloadingBlock0ueue: clear0ueue and ReleaseFreeMemory

### ISSUE THREAD

**Issue by tjc6386675** [FISCO-BCOS/FISCO-BCOS#3418]
所有服务运行正常，未出现报错，启动后四个node的日志一直重复出现下面这段，每秒10条，直到把硬盘塞满
info 2023-02-16 14:38:37.037457 [g:l][SYNC)[d:382e2d81...]DownloadingBlockQueue: clearQueue and ReleaseFreeMemory
info 2023-02-16 14:38:37.237607 [g:1][SYNC][id:382e2d81...]DownloadingBlock0ueue: clear0ueue and ReleaseFreeMemory
info2023-02-16 14:38:37.437710[g:1][SYNC][id:382e2d8...JDownloadingBlockQueue: clearQueue and ReleaseFreeMemory

**Comment by ywy2090** [comment]
@tjc6386675  这个不是bug，日志打印的问题， 把你的节点的版本升级至2.9.1版本，可以解决这个问题。
