### ISSUE TITLE
UTXO模型再这个系统的必要性或者优势在哪里？

### ISSUE THREAD

**Issue by fendouhyz** [FISCO-BCOS/FISCO-BCOS#343]
以太坊的Account模型相比于BTC的UTXO模型，增加了空间消耗，换来了查询，计算上的时间效率，而且给智能合约的扩展方面带来了比较大提升空间，FISCO-BCOS基于以太坊的账户模型增加UTXO是否有必要，意义何在呢，理论上基于Account模型的扩展足够应付所有业务情况，UTXO是出于是什么考虑，以及有哪些优势

**Comment by chaychen2005** [comment]
一些业务场景（如供应链金融等），存在拆分、溯源等操作，适合使用UTXO资产模型做一对多的资产映射。这些需求在以太坊上是可通过智能合约实现的，但其性能及并发性有待提高，因此FISCO BCOS基于以太坊的账户模型增加了UTXO模型。对于交易如存在限制条件的场景，用户可在使用UTXO时通过部署并挂载智能合约来实现。

**Comment by bxq2011hust** [comment]
https://github.com/FISCO-BCOS/FISCO-BCOS/issues/106
