### ISSUE TITLE
求助！节点突然连接不上了

### ISSUE THREAD

**Issue by dujinye2113** [FISCO-BCOS/FISCO-BCOS#3453]
**Describe the bug**
tars页面500报错，控制台和java jdk在getClient的时候报错，但是webase显示节点运行中并且可以对已登记合约发送交易，就很奇怪，坏了，但没有完全坏。。。
报错界面如下：
![image](https://user-images.githubusercontent.com/71626258/223461014-602539d2-8475-4672-a1a5-2a6b607a159d.png)
![image](https://user-images.githubusercontent.com/71626258/223462915-facd8b56-619b-4d8c-8a8f-065fdba1abda.png)
控制台日志如下：
![image](https://user-images.githubusercontent.com/71626258/223465040-c33697a0-bc00-444d-bef1-f3294180c238.png)

**Environment (please complete the following information):**
ubuntu，fisco3.0.0-rc1，按照官方教程搭建的pro版本双节点，一直能连上，突然连不上了，服务器硬盘空间有些不足，不知道是不是这个原因？

**Comment by dujinye2113** [comment]
补充：tarsnode的日志如下：
![image](https://user-images.githubusercontent.com/71626258/223469695-eed55303-672e-45da-bfc4-7a1cecfc4bfb.png)

**Comment by ywy2090** [comment]
你的空间清理出来之后，有么有恢复？

**Comment by dujinye2113** [comment]
因为空间日志太多了，也不想以后经常清理，干脆重装fisco2.9了

**Comment by dujinye2113** [comment]
> 你的空间清理出来之后，有么有恢复？
因为空间日志太多了，也不想以后经常清理，干脆重装fisco2.9了

**Comment by ywy2090** [comment]
> > 你的空间清理出来之后，有么有恢复？
> > 因为空间日志太多了，也不想以后经常清理，干脆重装fisco2.9了

好的
