### ISSUE TITLE
java sdk 合约事件推送功能异常

### ISSUE THREAD

**Issue by KTWhite** [FISCO-BCOS/FISCO-BCOS#3465]
java sdk 没有收到合约事件推送EventLog
问题描述：
应用启动并刚运行的时候数据上链、合约事件推送正常，
运行一段时间后，节点发起的合约事件推送，其他的SDK应用没有收到合约事件推送日志。
节点数据以mysql数据库形式存储，数据都有保存在各个节点的数据库中，但是合约事件日志没有推送。

**Comment by ywy2090** [comment]
这个问题本周会处理，处理完成之后会在这里回复。

**Comment by ywy2090** [comment]
这个是v2.9版本之前的一个bug，已经在v2.9.0解决，可以将版本升级至v2.9.0+， #539

**Comment by 2exd** [comment]
> java sdk 没有收到合约事件推送EventLog 问题描述： 应用启动并刚运行的时候数据上链、合约事件推送正常， 运行一段时间后，节点发起的合约事件推送，其他的SDK应用没有收到合约事件推送日志。 节点数据以mysql数据库形式存储，数据都有保存在各个节点的数据库中，但是合约事件日志没有推送。

请问问题解决了吗？我也遇到类似的问题了。

**Comment by KTWhite** [comment]
> > java sdk 没有收到合并事件推送EventLog 问题描述：应用启动并刚运行的时间数据上链、合并事件推送正常， 运进行一段时间后，节点发起的合并事件推送，其他的SDK应用没有收到合并事件推送节点数据以mysql数据库形式存储，数据都有保存在各个节点的数据库中，但合并事件日志没有推送。
> 
> 请问题解决了吗？我也遇到了类似的问题了。

**Comment by KTWhite** [comment]
我之前碰到的问题，原先用的sdk版本为2.7的，升级sdk版本，并且排查保证各个节点合约事件监听的方法是进行异步处理。
