### ISSUE TITLE
请问是否有测试用例，如单元测试、集成测试等？

### ISSUE THREAD

**Issue by dengyi9** [FISCO-BCOS/FISCO-BCOS#35]
如有，希望补充文档说明如何运行？

**Comment by spartucus** [comment]
这个有后续消息了吗？

**Comment by bxq2011hust** [comment]
> 这个有后续消息了吗？

所有单元测试都在这里
https://github.com/FISCO-BCOS/FISCO-BCOS/tree/master/test/unittests
