### ISSUE TITLE
大佬帮帮，安装webase时，不能运行bash start.sh

### ISSUE THREAD

**Issue by henryhugyq** [FISCO-BCOS/FISCO-BCOS#3538]
操作地址是这个地址在这：https://webasedoc.readthedocs.io/zh_CN/latest/docs/WeBASE-Install/developer.html，
运行第三步bash start.sh时出错，
![屏幕截图 2023-03-29 214548](https://user-images.githubusercontent.com/89083615/228558442-342c9983-9ac4-426f-b700-9e2c7135a5b7.png)
检查log时报这个错，但我的JAVA_HOME已经设置好了啊
![Uploading 屏幕截图 2023-03-29 214621.png…]()

**Comment by henryhugyq** [comment]
![屏幕截图 2023-03-29 214621](https://user-images.githubusercontent.com/89083615/228558748-d151043b-44d0-4ddd-9aab-df93c40562a2.png)

**Comment by henryhugyq** [comment]
我的java路径是对的，不知道为什么它报错里的就多了一个/bin/java

**Comment by ywy2090** [comment]
@mingzhenliu

**Comment by ywy2090** [comment]
@CodingCattwo

**Comment by mingzhenliu** [comment]
@CodingCattwo

**Comment by wujiayuny** [comment]
java是用tar包配置还是直接apt install -y java-jre 安装啊？

**Comment by wujiayuny** [comment]
> 

root@wujiayun:~/fisco# java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
root@wujiayun:~/fisco# whereis java
java: /usr/bin/java /usr/share/java /usr/share/man/man1/java.1.gz

**Comment by henryhugyq** [comment]
包配置的
