### ISSUE TITLE
更换config.genesis后，重复部署node服务，无法启动，报出：“The Genesis Data is inconsistent with the initial Genesis Data”

### ISSUE THREAD

**Issue by Degfy** [FISCO-BCOS/FISCO-BCOS#3631]
**问题描述**
使用部署工具 `python3 build_chain.py chain -o undeploy -t node` 删除服务时，无法清理tars上的本地存储。再次部署，报错："The Genesis Data is inconsistent with the initial Genesis Data"

**复现步骤**
1. 使用部署工具，部署node服务
2. 使用部署工具，`python3 build_chain.py chain -o undeploy -t node` 删除node服务
3. 更换 config.genesis
4. 重新部署
5. 服务状态一直为 Inactive，查出日志，报错：
<img width="864" alt="image" src="https://github.com/FISCO-BCOS/FISCO-BCOS/assets/15191087/25510dc6-f854-45b3-b914-7b65ba29837f">

**期望**
部署工具 `undeploy` 能够清理服务所有数据，或者 提供 可以清理服务所有数据的命令

**环境信息:**
 - OS: Ubuntu 22.04.2 
 - FISCO BCOS Version: v3.2.1

**背景信息**
> 我收到 `config.genesis`，要求在节点上增加一个group。部署好后，又收到信息说该文件有误，需要更换，于是出现需要替换`config.genesis` 重新部署node服务的需求。

我在定位问题后，提出两个“治标” 解决方法：
- 更换 node 服务的名字，重新部署，这样可以不受原来的数据影响。
- 进入tars 节点，找到原服务的数据目录，删除后重新部署:
  > 找到 tars 的数据目录, 一般是 /usr/local/app/tars/tarsnode/data (如果是docker部署的tars，可以进入docker，如果是集群部署的tars，需要找到对应的节点服务器）
  > 删除 对应服务的目录，目录名一般是：`${chanName}.${serviceName}`，例如下图：
<img width="658" alt="image" src="https://github.com/FISCO-BCOS/FISCO-BCOS/assets/15191087/e66d335b-cda7-43a5-b799-5aa109b61051">

**要根本解决问题，需要官方部署工具中提供 完全 清理服务 的能力，所以在这里提个issue。**

**Comment by kyonRay** [comment]
Hi @Degfy ,
感谢提出issue，删除业务数据是一个比较危险的操作，这里的 `undeploy` 是指将服务下线，我们还是比较推荐运维手动命令行删除数据，比较容易管理，文档中我们会补充说明这一点。完全清理服务是个好idea，我们后续会针对这个点做出优化。
