### ISSUE TITLE
1.3版本节点无法删除和加入，但是命令提示成功

### ISSUE THREAD

**Issue by 788674** [FISCO-BCOS/FISCO-BCOS#364]
说明一共有nodedata-1/2/3 一共3个节点，nodedata-1为创世节点，2/3为普通节点，目前就nodedata-2加入成功，
如图加入节点nodedata-3 加入节点，提示加入成功
![image](https://user-images.githubusercontent.com/46233235/50532538-a6cba380-0b55-11e9-95c5-246c8c9efe74.png)
但是实际节点并没有data-3
![image](https://user-images.githubusercontent.com/46233235/50532555-d7abd880-0b55-11e9-8154-c5d731e947f0.png)

删除nodedata-2节点
![image](https://user-images.githubusercontent.com/46233235/50532590-64569680-0b56-11e9-8d79-51d2b457b2ae.png)
实际删除的nodedata-2还存在
![image](https://user-images.githubusercontent.com/46233235/50532555-d7abd880-0b55-11e9-8154-c5d731e947f0.png)

**Comment by whodoyouremember** [comment]
如果没猜错，你的链崩溃了。

**Comment by 788674** [comment]
> 如果没猜错，你的链崩溃了。

链崩了怎么修复？

**Comment by wheatli** [comment]
加入了第二个节点之后，需要保证第二个节点是能够正常运行的，因为这个时候第二个节点需要参与共识。。。我怀疑是你的第二个节点没有正常运行

**Comment by 788674** [comment]
> 加入了第二个节点之后，需要保证第二个节点是能够正常运行的，因为这个时候第二个节点需要参与共识。。。我怀疑是你的第二个节点没有正常运行

检查第二个节点是正常运行的啊，进程都可以看到，打包信息也正常显示，我想这种情况还有什么方法处理？

**Comment by JimmyShi22** [comment]
检查一下节点2有没有连上节点1

**Comment by 788674** [comment]
> 检查一下节点2有没有连上节点1

我想问下 普通节点的 配置文件genesis.json和创世节点对比  god和initMinerNodes两个字段是不同的，还是一样的？

**Comment by HaoXuan40404** [comment]
> > 检查一下节点2有没有连上节点1
> 
> 我想问下 普通节点的 配置文件genesis.json和创世节点对比 god和initMinerNodes两个字段是不同的，还是一样的？

应该是一样的
