### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by cpucorecore** [FISCO-BCOS/FISCO-BCOS#3699]
**plantform**
Apple M1

**OS**
Ventura 13.4

**clang version**
➜  build git:(v2.9.1) ✗ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**cmake version**
➜  build git:(v2.9.1) ✗ cmake --version
cmake version 3.23.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**compile steps**
```
git checkout v2.9.1
mkdir build
cd build
cmake -DARCH_NATIVE=on ..
make -j10
```

**err output**
[ 98%] Building CXX object librpc/CMakeFiles/rpc.dir/StatisticProtocolServer.cpp.o
[ 98%] Linking CXX static library librpc.a
[ 98%] Built target rpc
[ 98%] Building CXX object libchannelserver/CMakeFiles/channelserver.dir/ChannelRPCServer.cpp.o
[ 98%] Linking CXX static library libchannelserver.a
[ 99%] Built target channelserver
Consolidate compiler generated dependencies of target fisco-bcos
[ 99%] Building CXX object fisco-bcos/main/CMakeFiles/fisco-bcos.dir/main.cpp.o
[100%] Linking CXX executable ../../bin/fisco-bcos
Undefined symbols for architecture arm64:
  "Json::Value::operator=(Json::Value&&)", referenced from:
      void dev::eth::JsonConfigParser::convert_to_json_str<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>) in libgroup_sig.a(LinkableRingSig_Impl.cpp.o)
      void dev::eth::JsonConfigParser::convert_to_json_str<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>) in libgroup_sig.a(KeyLoaderDumper.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]:***[bin/fisco-bcos] Error 1
make[1]:***[fisco-bcos/main/CMakeFiles/fisco-bcos.dir/all] Error 2
make:***[all] Error 2

**Comment by bxq2011hust** [comment]
你这个机器是不是用过time machine同步过？

**Comment by cpucorecore** [comment]
没有 即使有估计也两年了 系统都自动升级过很多次了> 你这个机器是不是用过time machine同步过？

**Comment by cpucorecore** [comment]
```bash
➜  FISCO-BCOS git:(v2.9.1) ✗ history|tail -n 25
10273  du -h deps
10274  rm -rf deps
10275  ls
10276  rm -rf build
10277  mkdir build
10278  cd build
10279  cmake -DARCH_NATIVE=on ..
10280  export https_proxy=http://127.0.0.1:7001
10281  make -j8
10282* ps -ef|grep ssh
10283* bash reproxy.sh
10284  make -j8
10285* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/lib/loader/loader.c +184
10286* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc-stamp/evmc-build-err.log
10287* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/lib/loader/loader.c +184
10288* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/include/evmc/loader.h +164
10289  make -j8
```

删除了deps目录依然报同样的错误，排除第二种可能

对第一种可能，能具体点吗，工具链包括哪些部分，最好给个目录参考一下

谢谢回复
另外早上试了下在x86的mac上是能够编译通过的，就是这个m1芯片的不行

**Comment by cpucorecore** [comment]
另外我mac的系统是13.4的，所以这里也需要修改，否则报平台版本库不兼容

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d16fe60cc..67e1775c0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -22,7 +22,7 @@
 cmake_minimum_required(VERSION 3.12)
 set(FISCO_BCOS_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}/cmake" CACHE PATH "The path to the cmake directory")
 list(APPEND CMAKE_MODULE_PATH ${FISCO_BCOS_CMAKE_DIR})
-set(CMAKE_OSX_DEPLOYMENT_TARGET "12" CACHE STRING "Minimum OS X deployment version")
+set(CMAKE_OSX_DEPLOYMENT_TARGET "13" CACHE STRING "Minimum OS X deployment version")
 
 project(FISCO-BCOS VERSION "2.9.1")
 # Suffix like "-rc1" e.t.c. to append to versions wherever needed.
```

**Comment by bxq2011hust** [comment]
> ```shell
> ➜  FISCO-BCOS git:(v2.9.1) ✗ history|tail -n 25
> 10273  du -h deps
> 10274  rm -rf deps
> 10275  ls
> 10276  rm -rf build
> 10277  mkdir build
> 10278  cd build
> 10279  cmake -DARCH_NATIVE=on ..
> 10280  export https_proxy=http://127.0.0.1:7001
> 10281  make -j8
> 10282* ps -ef|grep ssh
> 10283* bash reproxy.sh
> 10284  make -j8
> 10285* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/lib/loader/loader.c +184
> 10286* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc-stamp/evmc-build-err.log
> 10287* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/lib/loader/loader.c +184
> 10288* vi /Users/liukunyu/CLionProjects/github.com/FISCO-BCOS/FISCO-BCOS/deps/src/evmc/include/evmc/loader.h +164
> 10289  make -j8
> ```
> 
> 删除了deps目录依然报同样的错误，排除第二种可能
> 
> 对第一种可能，能具体点吗，工具链包括哪些部分，最好给个目录参考一下
> 
> 谢谢回复 另外早上试了下在x86的mac上是能够编译通过的，就是这个m1芯片的不行

重新编译还是一样的报错吗？

**Comment by cpucorecore** [comment]
如果我没看错的话这个value类型我看代码就是没有移动赋值函数 找不到是正常的吧 关键是不知道哪个地方触发了需要调用它

**Comment by bxq2011hust** [comment]
我找了台干净的机器测试了下是ok的，很可能还是机器的环境问题，`fisco-bcos/main/CMakeFiles/fisco-bcos.dir/`这个目录下有个link.txt文件，你提交上来看下

**Comment by cpucorecore** [comment]
[link.txt](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11795036/link.txt)

**Comment by cpucorecore** [comment]
好的 辛苦了 这c++不是在编译的路上就是在解决编译不过> > [link.txt](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11795036/link.txt)
> 
> 
> 
> 看起来没有问题，参考这个链接查查 https://github.com/open-source-parsers/jsoncpp/issues/738
> 
> 
> 
>

**Comment by bxq2011hust** [comment]
> > [link.txt](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11795036/link.txt)
> 
> 看起来没有问题，参考这个链接查查 [open-source-parsers/jsoncpp#738](https://github.com/open-source-parsers/jsoncpp/issues/738)

除了这个链接的问题，还有个可能是你自己在系统里安装过更高版本的jsoncpp导致的，这个也要你自己去排查了
