### ISSUE TITLE
在 32 位 armhf 上搭建服务

### ISSUE THREAD

**Issue by boltyu** [FISCO-BCOS/FISCO-BCOS#3703]
hi 各位开发者，
   我这边需要在 armhf 上运行此服务。我看到了文档说明要求 64 位 cpu，请问一下是因为 在32位 cpu上未经验证，还是程序应用本身就是为 64 位设计？  
   谢谢~

**Comment by bxq2011hust** [comment]
2.0我们尝试在32位树莓派上编译，发现有依赖的密码相关的库不支持32位，3.0我们尚未尝试在32位的机器上编译，欢迎社区开发者尝试反馈，一起共建

**Comment by boltyu** [comment]
> 2.0我们尝试在32位树莓派上编译，发现有依赖的密码相关的库不支持32位，3.0我们尚未尝试在32位的机器上编译，欢迎社区开发者尝试反馈，一起共建

感谢解答，我会继续学习研究
