### ISSUE TITLE
部署落盘加密，并选择存储类型为mysql时启动节点报错

### ISSUE THREAD

**Issue by mystery-abby** [FISCO-BCOS/FISCO-BCOS#3713]
部署落盘加密，并选择存储类型为mysql时启动节点报错如下：

[INITIALIZER][Initializer]Init failed,EINFO=/home/runner/work/FISCO-BCOS/FISCO-BCOS/libinitializer/LedgerInitializer.cpp(136): Throw in function std::vector<short int> dev::initializer::LedgerInitializer::initLedgers()
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::exception> >
std::exception::what: std::exception

Init failed!!!
config file path : config.ini
[2023-06-21 09:57:53] Initializing...
[INITIALIZER][LedgerInitializer]initLedger failed,errorInfo=/home/runner/work/FISCO-BCOS/FISCO-BCOS/libledger/DBInitializer.cpp(436): Throw in function void dev:: ledger ::DBInitializer::unsupportedFeatures(const string&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::UnsupportedFeature>
std::exception::what: std::exception
[dev::tag_comment*] = ZdbStorage doesn't support disk encryption
[INITIALIZER][LedgerInitializer]initLedger failed,EINFO=/home/runner/work/FISCO-BCOS/FISCO-BCOS/libinitializer/LedgerInitializer.cpp(126): Throw in function dev::initializer::LedgerInitializer::initLedgers()::<lambda(const GROUP_ID&, const string&)>
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::exception> >
std::exception::what: std::exception

[INITIALIZER][Initializer]Init failed,EINFO=/home/runner/work/FISCO-BCOS/FISCO-BCOS/libinitializer/LedgerInitializer.cpp(136): Throw in function std::vector<short int> dev::initializer::LedgerInitializer::initLedgers()
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::exception> >
std::exception::what: std::exception

Init failed!!!

**Comment by JimmyShi22** [comment]
mysql 不支持使用落盘加密，可使用：
* mysql自身的访问控制策略

**Comment by mystery-abby** [comment]
> mysql 不支持使用落盘加密，可使用：
> 
> * mysql自身的访问控制策略
好的，感谢解答
