### ISSUE TITLE
get remote config 'config.ini' error:remote config file is empty:config.ini

### ISSUE THREAD

**Issue by sunhuiyuan99** [FISCO-BCOS/FISCO-BCOS#3730]
**Describe the bug**
3.3max版,centos7.5，部署rpc和gateway服务正常，但是NodeService和ExecutorService服务异常，状态一直是Activating，日志报[fail] get remote config 'config.ini' error，但是其实是 部分线程成功、部分线程失败，如下图.

通过日志发现总找127.0.0.1:2379，我配置的是pd_addrs="192.168.61.121:2379",我generated成功、deploy成功，没有报任何错，说明配置文件没生效，在tars页面发现config.ini为空

![fs1](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/925e04af-0235-4268-b5c4-1989e57b0382)
NodeService服务异常
![fs2](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/c42d99cf-a7ec-4265-a2b2-abeba700b691)
一个线程提示[succ] get remote config:config.ini
![fs3](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/40817476-2cc7-4d95-b9a3-3d108d299f55)
另一个线程提示get remote config 'config.ini' error:remote config file is empty:config.ini
![generated正常](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/a973ca32-5c54-4ae5-8c79-811db0bd0a24)
generated正常配置正常
![config ini服务提示能够获取](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/f7dd6d93-86e3-42a0-9a49-bacb88820f62)
发布没报错
![config ini文件为空](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/39a95524-b09e-4e8f-8ce3-3fdd31385a8f)
配置文件为空

![2379error](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/0f54235e-fd09-4708-9136-bff129971fdc)
日志错误提示 我配置的2379没生效，还是127，我明明是192呀

[config.toml.txt](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11944008/config.toml.txt)
[chain0.agencyAgroup0node0BcosMaxNodeService.log](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11944009/chain0.agencyAgroup0node0BcosMaxNodeService.log)
[chain0.agencyAgroup0node0BcosExecutorService.log](https://github.com/FISCO-BCOS/FISCO-BCOS/files/11944010/chain0.agencyAgroup0node0BcosExecutorService.log)

**Comment by JimmyShi22** [comment]
maxnode的日志里报pd没连上，检查一下tikv的机器和该两个进程所在机器是否能连通
```
init NodeService failed, error: Dynamic exception type: rust::cxxbridge1::Error
std::exception::what: [/home/ci/.cargo/git/checkouts/tikv-client-rust-7cde0b12148733a8/8b62848/tikv-client-pd/src/cluster.rs:264]: failed to connect to [Member { name: "pd-127.0.0.1-2379", member_id: 3474484975246189105, peer_urls: ["http://127.0.0.1:2380"], client_urls: ["http://127.0.0.1:2379"], leader_priority: 0, deploy_path: "", binary_version: "", git_hash: "", dc_location: "" }]
 
```

**Comment by sunhuiyuan99** [comment]
2379端口能被容器访问，我配置的是192.168.61.121:2379，日志却是127.0.0.1，明显是配置没生效呀？？？不知道为什么
![2379能被容器内访问](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/dcfaf60a-240d-432c-89cf-28ef32026ca6)
![配置没生效](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/de70d05a-46f2-4233-b6e3-81d71fb0bc18)

**Comment by sunhuiyuan99** [comment]
我是bridge模式，不是host模式

**Comment by sunhuiyuan99** [comment]
tikv单独部署在192.168.61.121:2379，能被tars  framework的容器访问

**Comment by JimmyShi22** [comment]
检查一下这里的配置，看看pd_address是否正确
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/12178678/172fc91f-d038-4a2d-a561-bce384816e29)

**Comment by JimmyShi22** [comment]
建议使用host模式，bridge模式配置起来相对复杂。

**Comment by sunhuiyuan99** [comment]
您看我的截图，配置都是正确的，是节点服务没有读取我的配置，默认127了，所以说是个bug。
客户这一台服务器，程序多端口冲突，所以用bridge模式映射了端口，host模式下tarsweb的3000端口无法修改，也是修改不生效，才用的bridge模式。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月05日 14:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [FISCO-BCOS/FISCO-BCOS] get remote config 'config.ini' error:remote config file is empty:config.ini (Issue #3730) |

建议使用host模式，bridge模式配置起来相对复杂。

**Comment by sunhuiyuan99** [comment]
![tikv配置正确](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/c191be70-f85e-4f52-842e-94d392a7ea69)
按您的方法查看tikv配置正确，就是没生效。
分析不是bridge的原因，我MySQL就能被tarsweb访问，不是127本地。现在tikv也部署在外面，配置正确的tikv地址后，在容器内用curl能访问tikv的2379端口

**Comment by sunhuiyuan99** [comment]
已经解决！！！不是bug
步骤如下：通过各条命令，检测容器的连通性
firewall-cmd --permanent --zone=trusted --change-interface=docker0
firewall-cmd --add-port=2379/tcp --permanent
firewall-cmd --add-port=2380/tcp --permanent
firewall-cmd --reload
docker exec -it d50708287405 curl -v 192.168.61.121:2379
本服务器其他程序能访问tikv，容器内能访问2379端口后，检查所有tars和NodeService配置文件都对后，想到tikv不能配置127，如图
![tikvip](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/52436843/a2a4a3d2-75c3-44f9-a8a3-bb343e68229d)

**Comment by sunhuiyuan99** [comment]
tiup cluster deploy tikvfb v6.5.0 topo.yaml --user root -p 这里的配置文件一定注意里面的IP配置
