### ISSUE TITLE
FISCOBCOS通过什么方式实现私有链？

### ISSUE THREAD

**Issue by wxj-cyber** [FISCO-BCOS/FISCO-BCOS#3742]
目标：实现一个茶叶溯源系统项目
希望能够从这个项目正确的认识区块链，能够熟悉fiscobcos网络搭建，以及solidity智能合约和java-sdk的使用，更希望能够收获到区块链应用开发的一些小tips.

下图是自己构思的一个项目基本架构图（不是很标准），恳请指点迷津！希望帮助我能够入了区块链的坑！hhh~~~
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/54149367/65bf9ca9-8e59-41c9-a961-158118666685)
自己油然而生出了一个问题，就是FISCO-BCOS是联盟链，我设计这个的架构里面引入了“私有链”，不知道通过FISCO-BCOS如何实现。
这个问题可以简单的理解为：假设机构A是联盟链上的成员，但这个机构A也有自己的一条私有链，这个私有链允许其他不属于机构A的成员读，但不允许写。请问该如何实现？恳请指点迷津。

**Comment by lcs100** [comment]
私有链的交易数据可以保存在A的数据库中，通过跨链的方式将数据传输到联盟链中。

**Comment by wxj-cyber** [comment]
就是意思是说，可以使用FISCOBCOS联盟链模拟出“私有链“，然后在构建一条联盟链？将其跨链吗？
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/54149367/0baa2383-c227-4ae5-bfa1-dcea548056e6)
恳请指导~~~

**Comment by lcs100** [comment]
使用FISCOBCOS搭建联盟链，同时A自己搭建一条私链，A既是私链节点，也是联盟链节点，使用跨链技术进行数据交互
