### ISSUE TITLE
在 3.3 平台中，如何启动 DAG 并行执行而不是采用 DMC 的策略？且是否有针对 DAG 执行效率的测试脚本？

### ISSUE THREAD

**Issue by JeffXiesk** [FISCO-BCOS/FISCO-BCOS#3912]
最近我在 BCOS 3.3平台上进行开发，我看见了官网文档中有提到采用了 [DAG 的并行策略](https://fisco-bcos-doc.readthedocs.io/zh_CN/latest/docs/design/parallel/dag.html?highlight=dag)
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/75991596/b983a1f1-95cc-4246-a679-3515b635a69b)

且我也在代码中找到了具体的相应实现 [TxDAG2.cpp](https://github.com/FISCO-BCOS/FISCO-BCOS/blob/master/bcos-executor/src/dag/TxDAG2.cpp)

![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/75991596/82979f51-efb9-4234-a33b-4c8c03aaa1ce)

但我在测试过程中始终无法开启 DAG 执行，请问有什么方法可以用到文档中提到的 DAG 执行策略呢？ 

非常感谢！

**Comment by JimmyShi22** [comment]
3.0里面用了静态分析的方法去自动判断能否DAG。压测程序在
https://github.com/FISCO-BCOS/java-sdk-demo/blob/main/src/main/java/org/fisco/bcos/sdk/demo/perf/ParallelOkPerf.java

对应的合约在：
https://github.com/FISCO-BCOS/java-sdk-demo/blob/main/src/main/java/org/fisco/bcos/sdk/demo/contract/sol/ParallelOk.sol

**Comment by JeffXiesk** [comment]
问题已解决，感谢开发者 jimmy
