### ISSUE TITLE
请教一下权限问题。

### ISSUE THREAD

**Issue by buaasunby** [FISCO-BCOS/FISCO-BCOS#3986]
我根据fisco3.0的文档，设计的权限大概是这样的。
1.牵头组织作为管理员，拥有治理角色和合约管理员角色。其他机构拥有用户角色。
2.牵头组织通过CRUD Service创建表比如t_order，并赋予其他机构读、写权限。
3.牵头组织动态赋予其他新加入的机构的读写权限，通过SDK的API调用的方式修改
4.其他机构通过CRUDService读写t_order表。

您看这样目前的fisco框架应该能实现吧，我的理解是不是有偏差？

**Comment by buaasunby** [comment]
还有个问题就是，查询区块链状态、查询历史数据，这些怎么赋予权限控制？自己创建的表可以进行查询历史记录，追溯某个订单表某个订单的历史数据修改吗？

**Comment by kyonRay** [comment]
> 我根据fisco3.0的文档，设计的权限大概是这样的。 1.牵头组织作为管理员，拥有治理角色和合约管理员角色。其他机构拥有用户角色。 2.牵头组织通过CRUD Service创建表比如t_order，并赋予其他机构读、写权限。 3.牵头组织动态赋予其他新加入的机构的读写权限，通过SDK的API调用的方式修改 4.其他机构通过CRUDService读写t_order表。
> 
> 您看这样目前的fisco框架应该能实现吧，我的理解是不是有偏差？

写权限可以控制，读权限因为call请求都不带签名所以链上没有做控制，需要业务上做控制。

**Comment by kyonRay** [comment]
> 还有个问题就是，查询区块链状态、查询历史数据，这些怎么赋予权限控制？自己创建的表可以进行查询历史记录，追溯某个订单表某个订单的历史数据修改吗？

查询区块链状态等的RPC接口目前没有做权限控制，需要业务上做控制。因为3.0默认使用的存储模型不是mpt，所以链上查询数据历史记录也比较难查询。

**Comment by buaasunby** [comment]
好的
