### ISSUE TITLE
求助:fisco2.X多群组  一个群组共识老是异常

### ISSUE THREAD

**Issue by sdlp9** [FISCO-BCOS/FISCO-BCOS#4018]
麻烦大佬帮忙分析 分析

CentOS - ubuntu
FISCO BCOS Version 2.9.1
机器列表
机构1节点1 ubuntu  群组2，3
机构2节点2 ubuntu  群组3
机构3节点3,节点4  centos  群组1，2，3

其中群组3 老是失去共识，重启节点3和节点4后才会正常

下面是节点2的日志：

info|2023-11-02 09:47:47.021138|[g:3][CONSENSUS][SEALER]++++++++++++++++ Generating seal on,blkNum=5229,tx=1,nodeIdx=1,hash=63563cfc...
info|2023-11-02 09:47:47.023159|[CONSENSUS]addRawPrepare,height=5229,reqIdx=1,hash=63563cfc...,time=0
info|2023-11-02 09:47:47.023257|[BLOCKVERIFIER][executeBlock]Executing block,txNum=1,num=5229,parentHash=3318a7baaa878b7761414ee3f4dbe0a41c763214457627382995f0a9f236fb50,parentNum=5228,parentStateRoot=5a3c4f14033e11143028f0435a64c8cd5272181158df3e8bd1fc68ec42274c67
info|2023-11-02 09:47:47.029826|[CONSENSUS][PBFT]execBlock,blkNum=5229,reqIdx=1,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...,decodeCost=0,checkCost=0,notifyCost=0,noteSealingCost=0,currentCycle=1,verifyAndSetSenderCost=0,execCost=6,execPerTx=6,totalCost=6
info|2023-11-02 09:47:47.031341|[CONSENSUS][PBFT]handlePrepareMsg Succ,timecost=2,INFO=handlePrepareMsg,reqIdx=1,view=41,reqNum=5229,curNum=5228,consNum=5229,curView=41,fromIp=self,hash=63563cfc...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=1
info|2023-11-02 09:47:47.031487|[CONSENSUS][PBFT]generateLocalPrepare,hash=63563cfc...,H=5229,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:47.078204|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=1,INFO=handleSignMsg,num=5229,curNum=5228,GenIdx=2,Sview=41,view=41,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:47.860167|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:47:48.033118|[g:3][CONSENSUS][PBFT]checkAndCommit: backup/updateCommittedPrepare,reqNum=5229,hash=63563cfc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:48.033961|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=1,INFO=handleSignMsg,num=5229,curNum=5228,GenIdx=3,Sview=41,view=41,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:48.036212|[g:3][CONSENSUS][PBFT]handleCommitMsg Succ,INFO=handleCommitMsg,reqNum=5229,curNum=5228,GenIdx=2,Cview=41,view=41,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...,Timecost=1
info|2023-11-02 09:47:48.056333|[g:3][CONSENSUS][PBFT]checkAndSave: CommitReq enough,prepareHeight=5229,commitSize=3,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:48.057104|[g:3][g:3][STORAGE][CachedStorage]commit: 7 num: 5229
info|2023-11-02 09:47:48.057258|[g:3][g:3][STORAGE][CachedStorage]Start commit block: 5229 to backend storage
info|2023-11-02 09:47:48.059316|[g:3][g:3][STORAGE][CachedStorage]Submited block task: 5229, current syncd block: 5228
info|2023-11-02 09:47:48.059389|[g:3]Push block notify: 3-5229
info|2023-11-02 09:47:48.059420|[g:3][CHANNEL]Push message success,topic=_block_notify_3,seq=00000000,session=127.0.0.1:59688,127.0.0.1:59692,
info|2023-11-02 09:47:48.061864|[g:3][g:3][STORAGE][CachedStorage]
---------------------------------------------------------------------
Commit block: 5229 to backend storage finished, current cached block: 5229
Flush elapsed time: 0.0046s
---------------------------------------------------------------------

info|2023-11-02 09:47:48.062226|[g:3][CONSENSUS][PBFT]CommitBlock Succ,prepareHeight=5229,reqIdx=1,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...,genSigTimeCost=0,commitBlockTimeCost=3,dropTxsTimeCost=3,noteSealingTimeCost=0,totalTimeCost=6
info|2023-11-02 09:47:48.062259|[g:3][CONSENSUS][PBFT]handleCommitMsg Succ,INFO=handleCommitMsg,reqNum=5229,curNum=5228,GenIdx=3,Cview=41,view=41,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...,Timecost=7
info|2023-11-02 09:47:48.062376|[g:3][CONSENSUS][PBFT]^^^^^^^^Report,num=5229,sealerIdx=1,hash=5757d6cc...,next=5230,tx=1,nodeIdx=1
info|2023-11-02 09:47:48.126622|[RPC][getBlockByNumber]request,groupID=3,blockNumber=5229,includeAllData=false
info|2023-11-02 09:47:48.639946|[g:3][STORAGE][CachedStorage]Clear finished, total: 6 entries, through: 6 entries, 1.9202 MB, Current total entries: 315, Current total mru entries: 315, total capacaity: 31.1076 MB
info|2023-11-02 09:47:49.005425|[RPC][getGroupList]request
info|2023-11-02 09:47:49.062403|[g:3][CONSENSUS][SEALER]++++++++++++++++ Generating seal on,blkNum=5230,tx=0,nodeIdx=1,hash=53f3412c...
info|2023-11-02 09:47:49.064339|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=0,toView=1,nodeIdx=1,changeCycle=1,myNode=695d09d6...,timecost=1
info|2023-11-02 09:47:49.067034|[RPC][getGroupList]request
info|2023-11-02 09:47:49.081871|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=0,cur_changeCycle=1,curView=0,view=1
info|2023-11-02 09:47:49.224997|[RPC][getGroupList]request
info|2023-11-02 09:47:49.396915|[RPC][getGroupList]request
info|2023-11-02 09:47:49.397004|[RPC][getGroupList]request
info|2023-11-02 09:47:49.397114|[RPC][getGroupList]request
info|2023-11-02 09:47:49.397148|[RPC][getGroupList]request
info|2023-11-02 09:47:49.397180|[RPC][getGroupList]request
info|2023-11-02 09:47:49.496881|[RPC][getGroupList]request
info|2023-11-02 09:47:49.540051|[RPC][getGroupList]request
info|2023-11-02 09:47:49.592871|[g:3][CONSENSUS][PartiallyPBFTReqCache]addPartiallyRawPrepare,height=5230,reqIdx=2,hash=34f052c9...
info|2023-11-02 09:47:49.606053|[g:3][BLOCKVERIFIER][executeBlock]Executing block,txNum=2,num=5230,parentHash=5757d6cc3984659b2155811b84c6631e93b99a507a190c59df1c249eb9af6673,parentNum=5229,parentStateRoot=6bff40affe5e1722705e714b60bbc7133eb087d489e88b79d73c15aceba31c16
info|2023-11-02 09:47:49.678736|[g:3][CONSENSUS][PBFT]execBlock,blkNum=5230,reqIdx=2,hash=dddad8a5...,nodeIdx=1,myNode=695d09d6...,decodeCost=0,checkCost=0,notifyCost=0,noteSealingCost=0,currentCycle=1,verifyAndSetSenderCost=1,execCost=72,execPerTx=36,totalCost=74
info|2023-11-02 09:47:49.693547|[g:3][CONSENSUS][PBFT]handlePrepareMsg Succ,timecost=14,INFO=handlePartiallyPrepare,reqIdx=2,view=1,reqNum=5230,curNum=5229,consNum=5230,hash=34f052c9...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=1
info|2023-11-02 09:47:49.694411|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=1,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=2,Sview=1,view=1,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=dddad8a5...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:50.451404|[RPC][getGroupList]request
info|2023-11-02 09:47:50.451420|[RPC][getGroupList]request
info|2023-11-02 09:47:50.590328|[RPC][getBatchReceiptsByBlockNumberAndRange]request,groupID=3,blockNumber=0x146d,from=0,receiptSize=-1
info|2023-11-02 09:47:50.590407|[RPC]getBatchReceipts,blockHash=5757d6cc...,startIndex=0,endIndex=1,receiptsSize=1
info|2023-11-02 09:47:50.595895|[RPC][getTransactionByHash]request,groupID=3,transactionHash=0x2c2bfde81e9926d85586f6f255827fbdaccbbbb97282c96e5d6610496f570754
info|2023-11-02 09:47:50.690533|[RPC][getGroupList]request
info|2023-11-02 09:47:51.164906|[RPC][getGroupList]request
info|2023-11-02 09:47:51.361320|[RPC][getGroupList]request
info|2023-11-02 09:47:51.377791|[RPC][getGroupList]request
info|2023-11-02 09:47:51.468436|[RPC][getGroupList]request
info|2023-11-02 09:47:51.565442|[RPC][getGroupList]request
info|2023-11-02 09:47:52.301212|[RPC][getGroupList]request
info|2023-11-02 09:47:52.528029|[RPC][getGroupList]request
info|2023-11-02 09:47:52.620518|[RPC][getGroupList]request
info|2023-11-02 09:47:52.620657|[RPC][getGroupList]request
info|2023-11-02 09:47:52.620683|[RPC][getGroupList]request
info|2023-11-02 09:47:52.624221|[RPC][getGroupList]request
info|2023-11-02 09:47:52.628868|[RPC][getGroupList]request
info|2023-11-02 09:47:53.801840|[g:3][CONSENSUS][PBFT]Trigger fast-viewchange,view=1,toView=1,minView=2,INFO=,reqNum=5229,curNum=5229,GenIdx=3,Cview=2,view=1,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:47:53.802644|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=1,cur_changeCycle=2,curView=1,view=2
info|2023-11-02 09:47:53.802662|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=2,toView=2,nodeIdx=1,changeCycle=2,myNode=695d09d6...,timecost=8
info|2023-11-02 09:47:57.860292|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:00.004359|[RPC][getGroupList]request
info|2023-11-02 09:48:00.035009|[g:3][CONSENSUS][PartiallyPBFTReqCache]addPartiallyRawPrepare,height=5230,reqIdx=3,hash=4b2fe821...
info|2023-11-02 09:48:00.072735|[g:3][BLOCKVERIFIER][executeBlock]Executing block,txNum=18,num=5230,parentHash=5757d6cc3984659b2155811b84c6631e93b99a507a190c59df1c249eb9af6673,parentNum=5229,parentStateRoot=6bff40affe5e1722705e714b60bbc7133eb087d489e88b79d73c15aceba31c16
info|2023-11-02 09:48:00.212525|[g:3][CONSENSUS][PBFT]execBlock,blkNum=5230,reqIdx=3,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...,decodeCost=0,checkCost=0,notifyCost=0,noteSealingCost=0,currentCycle=2,verifyAndSetSenderCost=0,execCost=140,execPerTx=7.77778,totalCost=140
info|2023-11-02 09:48:00.214402|[g:3][CONSENSUS][PBFT]handlePrepareMsg Succ,timecost=2,INFO=handlePartiallyPrepare,reqIdx=3,view=2,reqNum=5230,curNum=5229,consNum=5230,hash=4b2fe821...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=2
info|2023-11-02 09:48:00.349862|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=1,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=3,Sview=2,view=2,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:00.530644|[g:3][CONSENSUS][PBFT]checkAndCommit: backup/updateCommittedPrepare,reqNum=5230,hash=4b2fe821...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:00.541746|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=12,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=2,Sview=2,view=2,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:00.699422|[g:3][CONSENSUS][PBFT]handleCommitMsg Succ,INFO=handleCommitMsg,reqNum=5230,curNum=5229,GenIdx=2,Cview=2,view=2,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...,Timecost=1
info|2023-11-02 09:48:07.097975|[g:3][CONSENSUS][PBFT]Trigger fast-viewchange,view=2,toView=2,minView=3,INFO=,reqNum=5229,curNum=5229,GenIdx=3,Cview=3,view=2,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:07.099179|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=2,cur_changeCycle=3,curView=2,view=3
info|2023-11-02 09:48:07.099322|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=3,toView=3,nodeIdx=1,changeCycle=3,myNode=695d09d6...,timecost=1
info|2023-11-02 09:48:07.860414|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:07.970946|[RPC][getGroupList]request
info|2023-11-02 09:48:08.349283|[RPC][getGroupList]request
info|2023-11-02 09:48:08.360617|[RPC][getGroupList]request
info|2023-11-02 09:48:09.544747|[RPC][getGroupList]request
info|2023-11-02 09:48:10.006961|[RPC][getGroupList]request
info|2023-11-02 09:48:11.940358|[g:3][CONSENSUS][PBFT]InvalidPrepare: not saved after commit,EINFO=handlePartiallyPrepare,reqIdx=0,view=3,reqNum=5230,curNum=5229,consNum=5230,hash=0e2167e0...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=3
info|2023-11-02 09:48:12.187286|[g:3][CONSENSUS][PBFT]checkReq: Recv future request,prepHash=00000000...,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=0,Sview=3,view=3,fromIdx=0,fromNode=2f65e6b6...,fromIp=192.168.207.147:30301,hash=2f905ee3...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:12.187320|[g:3][CONSENSUS][PBFT]FutureBlock,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=0,Sview=3,view=3,fromIdx=0,fromNode=2f65e6b6...,fromIp=192.168.207.147:30301,hash=2f905ee3...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:12.264713|[g:3][CONSENSUS][PBFT]checkReq: Recv future request,prepHash=00000000...,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=3,Sview=3,view=3,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=2f905ee3...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:12.264740|[g:3][CONSENSUS][PBFT]FutureBlock,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=3,Sview=3,view=3,fromIdx=3,fromNode=ae49b71a...,fromIp=192.168.207.138:38441,hash=2f905ee3...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:14.765511|[RPC][getGroupList]request
warning|2023-11-02 09:48:17.225626|[g:3][CONSENSUS][PBFT]ViewChangeWarning: not caused by omit empty block ,v=3,toV=4,curNum=5229,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:17.225812|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=3,toView=4,nodeIdx=1,changeCycle=4,myNode=695d09d6...,timecost=1
info|2023-11-02 09:48:17.229739|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=3,cur_changeCycle=4,curView=3,view=4
info|2023-11-02 09:48:17.236022|[g:3][CONSENSUS][PBFT]rehandleCommittedPrepare,nodeIdx=1,nodeId=695d09d6...,view=4,hash=4b2fe821...,H=5230
info|2023-11-02 09:48:17.249766|[g:3][CONSENSUS]addRawPrepare,height=5230,reqIdx=1,hash=4b2fe821...,time=0
info|2023-11-02 09:48:17.249910|[g:3][BLOCKVERIFIER][executeBlock]Executing block,txNum=18,num=5230,parentHash=5757d6cc3984659b2155811b84c6631e93b99a507a190c59df1c249eb9af6673,parentNum=5229,parentStateRoot=6bff40affe5e1722705e714b60bbc7133eb087d489e88b79d73c15aceba31c16
info|2023-11-02 09:48:17.507954|[g:3][CONSENSUS][PBFT]execBlock,blkNum=5230,reqIdx=1,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...,decodeCost=0,checkCost=0,notifyCost=0,noteSealingCost=0,currentCycle=4,verifyAndSetSenderCost=0,execCost=258,execPerTx=14.3333,totalCost=258
info|2023-11-02 09:48:17.510306|[g:3][CONSENSUS][PBFT]handlePrepareMsg Succ,timecost=2,INFO=handlePrepareMsg,reqIdx=1,view=4,reqNum=5230,curNum=5229,consNum=5230,curView=4,fromIp=self,hash=4b2fe821...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=4
info|2023-11-02 09:48:17.860488|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:17.869860|[g:3][CONSENSUS][PBFT]handleSignMsg Succ,Timecost=1,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=2,Sview=4,view=4,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:20.003346|[RPC][getGroupList]request
info|2023-11-02 09:48:22.573284|[RPC][getGroupList]request
info|2023-11-02 09:48:27.860556|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:30.003065|[RPC][getGroupList]request
info|2023-11-02 09:48:32.696117|[g:3][CONSENSUS][SEALER]decrease maxBlockCanSeal to half for PBFT timeout,org_maxBlockCanSeal=36,halfed_maxBlockCanSeal=18,timeoutCount=1,lastTimeoutTx=37
warning|2023-11-02 09:48:32.697086|[g:3][CONSENSUS][PBFT]ViewChangeWarning: not caused by omit empty block ,v=4,toV=5,curNum=5229,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:32.697195|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=4,toView=5,nodeIdx=1,changeCycle=5,myNode=695d09d6...,timecost=1
info|2023-11-02 09:48:32.701540|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=4,cur_changeCycle=5,curView=4,view=5
info|2023-11-02 09:48:33.511536|[g:3][CONSENSUS][PBFT]checkReq: Recv future request,prepHash=00000000...,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=2,Sview=5,view=5,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:33.511562|[g:3][CONSENSUS][PBFT]FutureBlock,INFO=handleSignMsg,num=5230,curNum=5229,GenIdx=2,Sview=5,view=5,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:33.513964|[g:3][CONSENSUS]addRawPrepare,height=5230,reqIdx=2,hash=4b2fe821...,time=0
info|2023-11-02 09:48:33.552217|[g:3][BLOCKVERIFIER][executeBlock]Executing block,txNum=18,num=5230,parentHash=5757d6cc3984659b2155811b84c6631e93b99a507a190c59df1c249eb9af6673,parentNum=5229,parentStateRoot=6bff40affe5e1722705e714b60bbc7133eb087d489e88b79d73c15aceba31c16
info|2023-11-02 09:48:33.645262|[g:3][CONSENSUS][PBFT]execBlock,blkNum=5230,reqIdx=2,hash=f52b29bb...,nodeIdx=1,myNode=695d09d6...,decodeCost=39,checkCost=0,notifyCost=0,noteSealingCost=0,currentCycle=5,verifyAndSetSenderCost=0,execCost=93,execPerTx=5.16667,totalCost=132
info|2023-11-02 09:48:33.646852|[g:3][CONSENSUS][PBFT]handlePrepareMsg Succ,timecost=1,INFO=handlePrepareMsg,reqIdx=2,view=5,reqNum=5230,curNum=5229,consNum=5230,curView=5,fromIp=192.168.206.66:44042,hash=4b2fe821...,nodeIdx=1,myNode=695d09d6...,curChangeCycle=5
info|2023-11-02 09:48:37.860671|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:40.004337|[RPC][getGroupList]request
info|2023-11-02 09:48:47.860762|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:50.003916|[RPC][getGroupList]request
error|2023-11-02 09:48:53.705087|[NETWORK][Session]Idle connection, disconnect ,endpoint=192.168.207.147:30301
info|2023-11-02 09:48:53.705127|[NETWORK][Session]drop, call and erase all callbackFunc in this session!,endpoint=192.168.207.147:30301
warning|2023-11-02 09:48:53.705144|[NETWORK][Session][drop] closing remote 192.168.207.147:30301,reason=(Idle connection for no network io happens during 5s time intervals.),endpoint=192.168.207.147:30301
error|2023-11-02 09:48:53.705233|[NETWORK][Session]Session inactived
warning|2023-11-02 09:48:53.705242|[NETWORK][Session]doRead error,endpoint=192.168.207.147:30301,message=Operation canceled
warning|2023-11-02 09:48:53.705264|[NETWORK][Session][drop] shutdown failed ,errorValue=9,message=Bad file descriptor
warning|2023-11-02 09:48:53.705351|[P2P][Service] disconnect error P2PSession,nodeID=2f65e6b6...,endpoint=192.168.207.147:30301,errorCode=3,what=Disconnect
warning|2023-11-02 09:48:53.705376|[P2P][Service] onDisconnect,errorCode=3,what=Dynamic exception type: dev::network::NetworkException
std::exception::what: Disconnect

info|2023-11-02 09:48:54.193771|[NETWORK][Host]P2P Recv Connect, From=192.168.207.138:53961
info|2023-11-02 09:48:54.193872|[NETWORK][Host]P2P StartAccept,Host=0.0.0.0:30300
info|2023-11-02 09:48:54.214856|[NETWORK][Host]handshakeServer succ,remote endpoint=192.168.207.138:53961
info|2023-11-02 09:48:54.214973|[P2P][Service] Connection established,nodeID=2f65e6b6...,endpoint=192.168.207.138:53961
info|2023-11-02 09:48:54.214999|[NETWORK][Host]startPeerSession, Remote=192.168.207.138:53961,local endpoint=192.168.215.199:30300,nodeID=2f65e6b6...
info|2023-11-02 09:48:54.225622|[NETWORK][Session]Received topic: [24	_block_notify_1	_block_notify_2	_block_notify_3] from 2f65e6b639acd9bc378738a658fb529f10c43734ce05417defe32affe1af95d237b572d79452e386c8d9eb278af79ad9f72f1c6c180a78128c39acbb22ee1539
info|2023-11-02 09:48:55.673216|[g:3][CONSENSUS][PBFT]Trigger fast-viewchange,view=5,toView=5,minView=6,INFO=,reqNum=5229,curNum=5229,GenIdx=2,Cview=6,view=5,fromIdx=2,fromNode=a0418ccd...,fromIp=192.168.206.66:44042,hash=5757d6cc...,nodeIdx=1,myNode=695d09d6...
info|2023-11-02 09:48:55.674171|[g:3][CONSENSUS][PBFT]checkAndChangeView: Reach consensus,org_view=5,cur_changeCycle=6,curView=5,view=6
info|2023-11-02 09:48:55.674274|[g:3][CONSENSUS][PBFT]checkTimeout Succ,view=6,toView=6,nodeIdx=1,changeCycle=6,myNode=695d09d6...,timecost=1
info|2023-11-02 09:48:57.860952|[NETWORK][Host]Connecting to node,endpoint=192.168.207.147:30301
info|2023-11-02 09:48:57.861250|[P2P][Service] heartBeat,connected count=3
info|2023-11-02 09:48:57.861462|[NETWORK][ASIO]asyncResolveConnect,endpoint=192.168.207.147:30301
info|2023-11-02 09:48:57.891697|[NETWORK][Host]handshakeClient succ,local endpoint=192.168.215.199:39220
info|2023-11-02 09:48:57.891862|[NETWORK][Host]startPeerSession, Remote=192.168.207.147:30301,local endpoint=192.168.215.199:39220,nodeID=2f65e6b6...
info|2023-11-02 09:49:00.004699|[RPC][getGroupList]request
warning|2023-11-02 09:49:05.995397|[NETWORK][Session]onWrite error sending,message=Connection reset by peer,endpoint=192.168.207.138:38441
info|2023-11-02 09:49:05.995472|[NETWORK][Session]drop, call and erase all callbackFunc in this session!,endpoint=192.168.207.138:38441
warning|2023-11-02 09:49:05.995515|[P2P][Service] disconnect error P2PSession,nodeID=ae49b71a...,endpoint=192.168.207.138:38441,errorCode=3,what=Disconnect
warning|2023-11-02 09:49:05.995532|[P2P][Service] onDisconnect,errorCode=3,what=Dynamic exception type: dev::network::NetworkException
std::exception::what: Disconnect

**Comment by JimmyShi22** [comment]
检查一下这些节点的p2p连接是不是都相互配置了对方

**Comment by sdlp9** [comment]
> 检查一下这些节点的p2p连接是不是都相互配置了对方

4个节点  p2p都有配置对方的p2p地址。网络有跨了区域，不同区域config.ini 上p2p 列表不一样的，这应该没影响吧

**Comment by sdlp9** [comment]
经排查是上链数据太大 通信异常导致
