### ISSUE TITLE
【问题】用户发起交易的时候，产生的疑问？

### ISSUE THREAD

**Issue by Lands-1203** [FISCO-BCOS/FISCO-BCOS#4073]
## 区块链环境：
pro版本：2个RPC、2个网关、节点ABCD
## 发生交易
**当账户x发生交易的时候，是不是下述流程？**
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/61341868/ac6dacc0-2bd2-4b8b-adc0-a4e85d7f6e9e)
## 待确认的问题
这是我理解的流程，如果是按上述流程执行的话？我有四个问题需要确认：
1.  账户x发起合约调用的时候是需要指定RPC服务的吗？还是随机连接的？
2. RPC向区块链节点发送交易的时候，是发给leader节点吗？区块打包也是由leader打包的？
3. 账户与节点是一一关联关系的，账户发送的任何交易都可能会被RPC转发到当前的leader节点。
4. 共识节点在交换共识结果的时候是选择当前链上的所有网关中的任意一个链接的。
所以与RPC的链接是指定链接，节点与网关的通信是随机或者说负载均衡选择

**Comment by Lands-1203** [comment]
所以节点是没有“主人”的概念的，只能说某一个节点部署在了某个公司的服务器下，所有的节点是一个整体，账户对数据的操作都是通过RPC转发到链上的
只有账户是有主人的概念的。
比如说：公司有一个账户A和共识节点A，账户A向区块链提交交易的时候，是直接通过RPC提交给从当前共识节点选举的leader节点进行打包区块操作的，而不是直接提交给公司下的节点A服务

**Comment by ywy2090** [comment]
> ## 区块链环境：
> pro版本：2个RPC、2个网关、节点ABCD
> 
> ## 发生交易
> **当账户x发生交易的时候，是不是下述流程？** ![image](https://user-images.githubusercontent.com/61341868/284884994-ac6dacc0-2bd2-4b8b-adc0-a4e85d7f6e9e.png)
> 
> ## 待确认的问题
> 这是我理解的流程，如果是按上述流程执行的话？我有四个问题需要确认：
> 
> 1. 账户x发起合约调用的时候是需要指定RPC服务的吗？还是随机连接的？
> 2. RPC向区块链节点发送交易的时候，是发给leader节点吗？区块打包也是由leader打包的？
> 3. 账户与节点是一一关联关系的，账户发送的任何交易都可能会被RPC转发到当前的leader节点。
> 4. 共识节点在交换共识结果的时候是选择当前链上的所有网关中的任意一个链接的。
>    所以与RPC的链接是指定链接，节点与网关的通信是随机或者说负载均衡选择

1. 不需要指定rpc服务，随机选择
2. 不用发送给leader, 发送给其中一个节点就可以，出块的节点是轮训的，而且交易也会广播给其他节点，不会出现交易无法打包的情况
3. 没有一一关联的关系，账户在客户端对交易进行签名，节点端只关心签名是否有效，以及涉及到权限管理的地方会校验签名的账户的地址
4. 共识节点不关心与网关的连接情况，共识模块与网关之间还有个前置，前置为各个模块（共识、交易、区块同步等）提供发送接口，然后将消息转发给网关

**Comment by ywy2090** [comment]
> 所以节点是没有“主人”的概念的，只能说某一个节点部署在了某个公司的服务器下，所有的节点是一个整体，账户对数据的操作都是通过RPC转发到链上的 只有账户是有主人的概念的。 比如说：公司有一个账户A和共识节点A，账户A向区块链提交交易的时候，是直接通过RPC提交给从当前共识节点选举的leader节点进行打包区块操作的，而不是直接提交给公司下的节点A服务

没懂“主人”是什么意思，master\slave架构里面的master概念？ 区块链是个p2p网络，每个节点地位对等，没有master、slave的概念。
账户是私钥的概念，每笔交易都需要签名，通常每个人拥有的账户是不一样的，都是自己生成就可以

**Comment by Lands-1203** [comment]
> 1. 不需要指定rpc服务，随机选择
> 2. 不用发送给leader, 发送给其中一个节点就可以，出块的节点是轮训的，而且交易也会广播给其他节点，不会出现交易无法打包的情况
> 3. 没有一一关联的关系，账户在客户端对交易进行签名，节点端只关心签名是否有效，以及涉及到权限管理的地方会校验签名的账户的地址
> 4. 共识节点不关心与网关的连接情况，共识模块与网关之间还有个前置，前置为各个模块（共识、交易、区块同步等）提供发送接口，然后将消息转发给网关

针对以上回答，进一步推论：
1. 所有的RPC服务的ca证书是需要保持一致的
2. 官方文档提到leader节点是选举的，leader节点负责打包和广播
  (1).  您提到：“交易会先随机发送给一个RPC，然后转发到其中的一个节点”。那么在用户进行交易的时候，发送给其中一个节点是随机的、不可指定的？如果是的话，是按照“最快最优”的机制选择吗？
  (2). 是由接收到这些交易信息的节点，将信息发送给leader？
3. 共识节点与网关之间的前置服务，是一个内置于node服务的？
4. 群组的扩展，是必须要添加node服务的吗？添加一个群组，至少要保证有一个新的节点服务？（我看官方文档提供的扩展新群组一章，让我产生了这个问题）

**Comment by Lands-1203** [comment]
用户使用sdk向RPC发送消息，是随机选择RPC，如果没有设置默认节点，会随机选择节点获取数据或作为执行交易发起发起节点？

**Comment by twinsant** [comment]
应用只要关心RPC Endpoint是什么即可，区块链节点本身是 P2P +共识系统的一部分，不用关心，除非你要改区块链源代码
