### ISSUE TITLE
【提问】 我在初次搭建好了一个pro版本的链后，无法开启权限检查等操作

### ISSUE THREAD

**Issue by Lands-1203** [FISCO-BCOS/FISCO-BCOS#4077]
```
[group0]: /apps> checkDeployAuth
Deploy : ACCESS
Account: 0x76b72d379b8f640d061e152784026923e266bcb4

[group0]: /apps> setSystemConfigByKey compatibility_version 3.5.0
{
    "code":-50000,
    "msg":"Permission denied"
}

[group0]: /apps> getCommitteeInfo
---------------------------------------------------------------------------------------------
Committee address   : 0x9a295cd61f15a545959d7dd644b7b9d18cae9daf
ProposalMgr address : 0xb96523e1a351f50c6e78302e7a64d9033efc5829
---------------------------------------------------------------------------------------------
ParticipatesRate: 0% , WinRate: 0%
---------------------------------------------------------------------------------------------
Governor Address                                        | Weight
index0 : 0x76b72d379b8f640d061e152784026923e266bcb4     | 1

[group0]: /apps> getCurrentAccount
0x76b72d379b8f640d061e152784026923e266bcb4

[group0]: /apps>
[group0]: /apps> initAuth 0x76b72d379b8f640d061e152784026923e266bcb4
{
    "code":15,
    "msg":"Committee contract already exist."
}

[group0]: /apps> setSystemConfigByKey auth_check_status 1
{
    "code":-50000,
    "msg":"Permission denied"
}

[group0]: /apps>
```
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/61341868/7ec6a9a4-a64f-48fe-8255-556cccf5a6db)
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/61341868/9951c67a-0801-4d13-bc2c-0a0c059f6172)
控制台的账户文件是从第一张图片copy过去的

**Comment by Lands-1203** [comment]
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/61341868/68d0f985-ec46-4e27-a8bd-04216d3fed06)
我查看是否已经开启了权限检查，但是无法关闭？

**Comment by Lands-1203** [comment]
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/61341868/077aa30b-eca8-4e8d-9461-2cb82a0b49bd)
也无法将扩展的新节点加入到观察节点

**Comment by kyonRay** [comment]
当开启权限治理模式时，该命令将只允许治理委员会使用，不允许用户直接调用，请参考命令 addSealerProposal 、addObserverProposal、

https://fisco-bcos-doc.readthedocs.io/zh-cn/latest/docs/operation_and_maintenance/console/console_commands.html#addsealerproposal
https://fisco-bcos-doc.readthedocs.io/zh-cn/latest/docs/operation_and_maintenance/console/console_commands.html#addobserverproposal

**Comment by Lands-1203** [comment]
问题已解决
