### ISSUE TITLE
在K8S集群中部署时，如果使用容器名称创建Node时，不能部署FIsco联盟链服务

### ISSUE THREAD

**Issue by jashonw** [FISCO-BCOS/FISCO-BCOS#4096]
在K8S集群中部署时，如果使用容器名称创建Node时，不能部署FIsco联盟链服务。一旦使用容器名称：如：tarsnode-0.tarsnode-svc，部署完Node节点后，再部署RPC，不能部署。进入容器后，按照SHell里面的脚本，直接运行RPC服务，RPC程序会报Coredump，直接异常退出。

**Comment by jashonw** [comment]
使用最新的3.5.0的代码，也是这样。

**Comment by jashonw** [comment]
在创建Node的Yaml中，Node的启动脚本：export DOMAIN="`hostname`.tarsnode-svc"

**Comment by jashonw** [comment]
使用IP地址，创建Node容器，再部署，同样的RPC服务程序，可以成功部署。

**Comment by JimmyShi22** [comment]
初步判断是域名使用有问题，请提供更详细的配置过程和报错日志

**Comment by jashonw** [comment]
域名使用的是K8S能够识别的名称，也就是登录容器后，可以Ping通的域名。登录到容器后，直接运行服务，服务程序，直接Coredump了。

**Comment by jashonw** [comment]
在创建节点时，使用的是Tar节点名称，去Tar框架注册，然后Tar框架显示
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/2645834/4485fe95-eb54-465e-8044-4998fc8bd28e)
在通过脚本向tarsnode-0.tarsnode-svc部署服务时，报错。
