### ISSUE TITLE
关于委员会的概念

### ISSUE THREAD

**Issue by shangwu102** [FISCO-BCOS/FISCO-BCOS#4302]
<img width="399" alt="5fbbbf581c1a93394c96e56ed02694f" src="https://github.com/FISCO-BCOS/FISCO-BCOS/assets/162989366/a7d45b28-869f-458d-a7b8-249cd25d86ca">
这个enable_num代表着什么意思

**Comment by bxq2011hust** [comment]
enable_num代表的是这个设置的生效块高

**Comment by shangwu102** [comment]
> enable_num代表的是这个设置的生效块高

在哪里可以设置enable_num的数量呀？

**Comment by kyonRay** [comment]
> > enable_num代表的是这个设置的生效块高
> 
> 在哪里可以设置enable_num的数量呀？

这是链上在执行时额外写入的数据，比如在第3块时执行委员A加入委员会的交易，那么enable_num就会是4，代表着下个块开始生效。

**Comment by shangwu102** [comment]
> > > enable_num代表的是这个设置的生效块高
> > 
> > 
> > 在哪里可以设置enable_num的数量呀？
> 
> 这是链上在执行时额外读取的数据，比如在第3块时执行委员A加入委员会的交易，那么enable_num就会是4，代表着下个块开始生效。

**Comment by shangwu102** [comment]
> > > enable_num代表的是这个设置的生效块高
> > 
> > 
> > 在哪里可以设置enable_num的数量呀？
> 
> 这是链上在执行时额外读取的数据，比如在第3块时执行委员A加入委员会的交易，那么enable_num就会是4，代表着下个块开始生效。

谢谢您的回答 我理解了
