### ISSUE TITLE
关于节点日志占用磁盘问题？

### ISSUE THREAD

**Issue by 788674** [FISCO-BCOS/FISCO-BCOS#443]
搭建了3个测试节点 ，3个节点同时开启产生大量的日志，1天大概10到20G的样子，这个有无办法优化，属于正常现象吗？ 目前节点日志级别已配置为2

**Comment by JimmyShi22** [comment]
看看那个日志等级打了大量日志，把大量打印的日志的等级设置为false
可参考：https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/usage/nodes_operation.html#log-conf
