### ISSUE TITLE
Air版的v3.6.0的build_train.sh启动出现错误，在调用SSL生成CA的密钥时显示错误。但是之前使用v2.9.1启动没有问题

### ISSUE THREAD

**Issue by Zhengxuru** [FISCO-BCOS/FISCO-BCOS#4459]
使用Air版的v3.6.0的build_train.sh启动出现错误，具体出现在调用SSL生成CA的密钥。但是之前用v2.9.1时候没有出现类似问题，而且单独把openssl命令拿出来执行也没有问题。

[root@192 fisco_3]# bash build_chain.sh -l 127.0.0.1:4 -p 30300,20200
[INFO] Downloading fisco-bcos binary from https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/FISCO-BCOS/FISCO-BCOS/releases/v3.6.0/fisco-bcos-linux-x86_64.tar.gz ...
######################################################################## 100.0%
build_chain.sh: 行 324:  3421 段错误               ${OPENSSL_CMD} genrsa -out "${chaindir}"/ca.key "${rsa_key_length}" 2> /dev/null
[root@192 fisco_3]# openssl genrsa -out nodes/ca.key 32 2>/dev/null 
[root@192 fisco_3]# 

这是哪里报错了呢

**Comment by bxq2011hust** [comment]
可能是下载的tassl在你的系统上不支持，请您提供下你的系统和版本信息

另外，如果不是搭建国密版本，可以修改下面的这个变量赋值为openssl先饶过问题

https://github.com/FISCO-BCOS/FISCO-BCOS/blob/73e385f823629a07c90f0031b692c8b638168fa1/tools/BcosAirBuilder/build_chain.sh#L32

**Comment by Zhengxuru** [comment]
CentOS Linux release 7.9.2009 (Core)系统是这个版本

**Comment by bxq2011hust** [comment]
问题解决了吗？
可以验证下下面的命令能否正常执行 @Zhengxuru 
```bash
${HOME}/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
```

**Comment by Zhengxuru** [comment]
> 问题解决了吗？ 可以验证下下面的命令能否正常执行 @Zhengxuru
> 
> ```shell
> ${HOME}/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
> ```

我在docker里运行没啥问题，但是放在之前那个环境，还是出现段错误
```
[root@192 fisco]# echo $HOME
/root
[root@192 fisco]# /root/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
段错误
[root@192 fisco]# 
```

**Comment by Zhengxuru** [comment]
> > 问题解决了吗？ 可以验证下下面的命令能否正常执行 @Zhengxuru
> > ```shell
> > ${HOME}/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
> > ```
> 
> 我在docker里运行没啥问题，但是放在之前那个环境，还是出现段错误
> 
> ```
> [root@192 fisco]# echo $HOME
> /root
> [root@192 fisco]# /root/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
> 段错误
> [root@192 fisco]# 
> ```

我把/root/.fisco/删了，build_chain.sh重新生成又可以了

**Comment by Zhengxuru** [comment]
> > > 问题解决了吗？ 可以验证下下面的命令能否正常执行 @Zhengxuru
> > > ```shell
> > > ${HOME}/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
> > > ```
> > 
> > 
> > 我在docker里运行没啥问题，但是放在之前那个环境，还是出现段错误
> > ```
> > [root@192 fisco]# echo $HOME
> > /root
> > [root@192 fisco]# /root/.fisco/tassl-1.1.1b genrsa -out nodes/ca.key 32
> > 段错误
> > [root@192 fisco]# 
> > ```
> 
> 后面我把/root/.fisco/删了，build_chain.sh重新生成就可以了
