### ISSUE TITLE
想求教下使用Java-SDK连接节点报错

### ISSUE THREAD

**Issue by 2519kongbai** [FISCO-BCOS/FISCO-BCOS#4503]
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/66538663/c6d80bcc-c08b-4cfb-8dbf-99cbfbb17d5b)
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/66538663/118b252b-9131-486f-83a2-bf0d1e057143)

我在本地机器上安装了Air版的区块链网络，并成功部署运行了4个节点， 具体搭建文档参考：https://fisco-bcos-documentation.readthedocs.io/zh-cn/latest/docs/installation.html
然后使用了默认的springboot整合的项目，项目地址为：https://github.com/FISCO-BCOS/spring-boot-crud
并按照项目的步骤添加了相关启动配置（图2）

然后，运行该项目时出现了上述截图的问题，我查找了一些现有的解决方案，包括Java版本，证书路径等都没有解决我的问题，麻烦哪位大佬帮忙看下是什么问题？感谢

**Comment by JimmyShi22** [comment]
证书问题，请检查证书，或添加小助手咨询

**Comment by 2519kongbai** [comment]
感谢回答，确实是证书的问题，spring-boot-crud 使用的是3.0版本的JavaSDK，但是我部署的区块链网络是2.X的版本，可能是因为这个原因导致的项目启动失败
