### ISSUE TITLE
请教一下合约升级数据共享的问题

### ISSUE THREAD

**Issue by lengmianshi** [FISCO-BCOS/FISCO-BCOS#4530]
我table里建了一张表，后来需要增加一列，我看3.0版本已支持增加列：
![image](https://github.com/FISCO-BCOS/FISCO-BCOS/assets/18379086/88127d8d-dab0-42cd-b0c6-636c1bfa8043)
假如新增列后，部署合约，用新的合约地址能查到旧合约的数据吗？

**Comment by kyonRay** [comment]
table表在存储层就是实际存储的，只要在合约里用同一个table表名，所有合约都能共享。也就是说，在A合约内新增了列，在B合约内也能感知到。
