### ISSUE TITLE
关于现有系统数据上链的疑惑

### ISSUE THREAD

**Issue by clean2016** [FISCO-BCOS/FISCO-BCOS#4553]
有一个问题，现有业务系统数据都是存储mysql的，现在想将部分数据上链，这里数据存储就存在一个分布式的情况（先存区块链再存mysql或者反过来），比如链上写成功但MySQL写入失败（或者反过来）的情况。请问这种情况如何处理，有没有比较好的解决方案？

**Comment by chesunliu** [comment]
1、如果这个数据没有状态变更，且一定要上链（存证），可以先DB再上链。
2、如果这个数据有多个状态，例如某种资产的余额，建议先上链再缓存db，一切以链为准，db主要是历史数据查询和索引的作用。
