### ISSUE TITLE
无法设置日志级别

### ISSUE THREAD

**Issue by lengmianshi** [FISCO-BCOS/FISCO-BCOS#4569]
3.6pro版本，在这个弹窗里选择一个日志级别，保存提示成功；再次进来，它选择的还是None

**Comment by lengmianshi** [comment]
![image](https://github.com/user-attachments/assets/1fae2871-70be-45c3-86f2-bd4ab30a7f4f)

**Comment by JimmyShi22** [comment]
这里设置的是tars（微服务框架）的日志等级。设置FISCO BCOS的日志等级在这里，修改config.ini：
![image](https://github.com/user-attachments/assets/f74f86dd-9957-4974-8086-b6192d8ca45a)

**Comment by lengmianshi** [comment]
谢谢
