### ISSUE TITLE
SSL Medium Strength Cipher Suites Supported (SWEET32) 漏洞

### ISSUE THREAD

**Issue by Anixceed** [FISCO-BCOS/FISCO-BCOS#4571]
**Describe the bug**
fisco-bicos的4个端口报 ssl sweet32 漏洞

**To Reproduce**
1.使用漏洞扫描工具扫描 20200 20201 30300 30301 四个端口

**Expected behavior**
有没有可以修复的办法

**Screenshots**
![image](https://github.com/user-attachments/assets/f561ed9f-876f-4c71-bf3e-7b6d712a3c1f)

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu 20.04]
 - FISCO BCOS Version [2.8.0]

**Comment by lyhr00ly** [comment]
最新版2.11的bcos节点有一样的问题

**Comment by wenlinlee** [comment]
此问题在3.7已经修复，可以参考4485 [https://github.com/FISCO-BCOS/FISCO-BCOS/pull/4485]。2.0会考虑加版本修复，如果对代码熟悉，鼓励也欢迎社区用户提代码修复

**Comment by wenlinlee** [comment]
此问题在2.11.2小版本中修复，具体可参考[4608](https://github.com/FISCO-BCOS/FISCO-BCOS/pull/4608)，可以尝试用新的代码编译节点二进制试试

**Comment by Anixceed** [comment]
谢谢
