### ISSUE TITLE
请问 FISCO BCOS 3.0+ 的版本是否有网络流量和Gas统计的功能？

### ISSUE THREAD

**Issue by Vateer** [FISCO-BCOS/FISCO-BCOS#4586]
2.0的版本是有的：https://fisco-bcos-documentation.readthedocs.io/zh-cn/latest/docs/design/features/stat.html，我使用3.0的Air版本时，在log里面找不到网络流量统计的内容。

**Comment by JimmyShi22** [comment]
3.0目前未实现该功能，欢迎贡献 🎉
