### ISSUE TITLE
FISCO BCOS 3.9使用remix链接Metamask钱包部署合约报错 gas费不足

### ISSUE THREAD

**Issue by 22640** [FISCO-BCOS/FISCO-BCOS#4725]
我使用remix连接metamask钱包，部署合约，一直出错是什么原因，偶尔可以部署成功一次，但大多数情况都说是gas不够
钱包连接的是fiscobcos 链
我设置gas试试按照官方的 210000
![Uploading 122.jpg…]()

**Comment by 22640** [comment]
![Uploading 122.jpg…]()

**Comment by henryhugyq** [comment]
你的图片无法查看，报错的话可以检查下编译器版本是不是太高，gas再多给一个0，检查代码是否有逻辑错误（比如换到测试网sepolia部署下试试）。

**Comment by henryhugyq** [comment]
你的图片无法查看，报错的话可以检查下编译器版本是不是太高，gas再多给一个0，检查代码是否有逻辑错误（比如换到测试网sepolia部署下试试）。

**Comment by JimmyShi22** [comment]
图片好像看不到

**Comment by henryhugyq** [comment]
如果你的图是这个问题中的 #4721 的图，部署合约提示RPC内部错误，那大概率是你在remix中编译时选择的版本过高，例如当前v3的合约支持到0.8.11，,你在remix中的合约的pragma solidity也是^0.8.11，那么编译时将remix的compile选项勾选0.8.11+（默认应该是0.8.26+）。同时，我也遇到了修改编译器版本后仍然报rpc错误得现象，于是在metamsk签名部署交易时自定义nonce为1,2,3....可以正常部署，但nonce填的过大也报错。你可以在给足够gas仍报错的情况下尝试着两种办法（修改编译器版本和自定义一个较小的nonce），欢迎补充更多的错误信息和你的合约文件代码。

**Comment by 22640** [comment]
> 图片好像看不到

creation of ProductRegistry pending...
creation of ProductRegistry errored: Error occurred:  [TIMEOUT] Timeout for call sendAsync from udapp.

 [TIMEOUT] Timeout for call sendAsync from udapp

If the transaction failed for not having enough gas, try increasing the gas limit gently.

这是报错内容

**Comment by 22640** [comment]
> 你的图片无法查看，报错的话可以检查下编译器版本是不是太高，gas再多给一个0，检查代码是否有逻辑错误（比如换到测试网sepolia部署下试试）。

sepolia是可以正常部署的

**Comment by 22640** [comment]
> 图片好像看不到

![Snipaste_2024-11-18_13-47-00](https://github.com/user-attachments/assets/30fe6743-54bc-4190-ba1d-8b13af1b4bfa)

**Comment by 22640** [comment]
![Snipaste_2024-11-18_13-56-31](https://github.com/user-attachments/assets/e5b353fd-721b-4570-9e01-f93a96f8e611)

**Comment by 22640** [comment]
> 如果你的图是这个问题中的 #4724 的图，部署合约提示RPC内部错误，那大概率是你在remix中编译时选择的版本过高，例如当前v3的合约支持到0.8.11，,你在remix中的合约的pragma solidity也是^0.8.11，那么编译时将remix的compile选项勾选0.8.11+（默认应该是0.8.26+）。同时，我也遇到了修改编译器版本后仍然报rpc错误得现象，于是在metamsk签名部署交易时自定义nonce为1,2,3....可以正常部署，但nonce填的过大也报错。你可以在给足够gas仍报错的情况下尝试着两种办法（修改编译器版本和自定义一个较小的nonce），欢迎补充更多的错误信息和你的合约文件代码

我知道nonce了，现在成功了，感谢大哥指点

**Comment by 22640** [comment]
要解决这个问题，第一步先把版本设置到0.8.11以下，第二步metamask钱包nonce自定义开关打开，交易时nonce设置一个比较小的数字，每次交易nonce值递加

**Comment by henryhugyq** [comment]
> 要解决这个问题，第一步先把版本设置到0.8.11以下，第二步metamask钱包nonce自定义开关打开，交易时nonce设置一个比较小的数字，每次交易nonce值递加

是这样的，nonce就是每次部署合约Metamask弹窗最低下可以设置的交易次序，现在你可以关闭这个issues。

**Comment by kyonRay** [comment]
这个问题是因为历史适配原因，web3交易的nonce还是一个随机数，3.12的版本之后会解决这个问题。
