### ISSUE TITLE
[文档问题]FISCO BCOS区块链操作手册中配置有问题

### ISSUE THREAD

**Issue by alexwishes** [FISCO-BCOS/FISCO-BCOS#57]
nodedata-1和nodedata-2中peerip不能设置为0.0.0.0，必须设置为对应的主机IP地址
还有config.json中的listenip也是，对于初学者可能不太友好

**Comment by sanguohot** [comment]
兄弟  还有这种说法？碰上坑了吗？下周一我要改了试一下，碰上合约部署不了的问题

**Comment by alexwishes** [comment]
我已经放弃BCOS了，更新跟不上时代了

**Comment by alexwishes** [comment]
看实际应用场景，公司内我用的Hyperledger Fabric，公链开始研究EOS看看

**Comment by JimmyShi22** [comment]
现在FISCO-BCOS已经做了连接管理升级，有了更友好的配置文件形式，可以体验下
