### ISSUE TITLE
[RPC]使用RPC方式访问HelloWorld的set方法出现问题

### ISSUE THREAD

**Issue by alexwishes** [FISCO-BCOS/FISCO-BCOS#58]
Request：
curl -X POST --data  '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":{"contract":"HelloWorld","version":"","func":"set","params":["call defaut version"]},"randomid":"3"}],"id":1}'  "http://127.0.0.1:8546"

Response：
{"error":{"code":0,"data":null,"message":"Account unknown."},"id":1,"jsonrpc":"2.0"}

提示账户的错误，不是已经去掉了Account，使用CA了吗？请问如何处理？

**Comment by fisco-dev** [comment]
这个是提供了一个参考的示例，这种方式目前也并不推荐。
解决的方法可以如下：
进入fisco-bcos的config.json配置的datadir目录， 有个geth.ipc的文件。
使用命令  ： ethconsole geth.ipc
输入下面命令：

> web3.eth.personal.newAccount("123456",console.log)
null '0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce'
'0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce'
其中 
> web3.eth.personal.newAccount("123456",console.log)
null '0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce'
'0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce' 为新生成的账户， 123456是加密的密码。
然后解锁  然后解锁账号：
 web3.eth.personal.unlockAccount("0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce","123456",120,console.log)

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":{"contract":"HelloWorld","version":"","func":"set","params":["call defaut version"]},"randomid":"9","from":"0xEebF0c8B3C5abB70A9FDAd8c4307c33eBd53Ffce"}],"id":1}' "http://127.0.0.1:8546"
将上面解锁的账号添加为from字段，然后就可以正常使用。
上述是以太坊里面的一些流程，在fisco-bcos中已经不推荐使用。
