### ISSUE TITLE
关于图片丢失的问题

### ISSUE THREAD

**Issue by Anapodoton** [FISCO-BCOS/FISCO-BCOS#585]
中文版的readme下的微信图片二维码404

**Comment by chaychen2005** [comment]
感谢您发现的这个链接问题。
从可以打开的英文版readme中可发现这个微信图片存储在与中文版readme同一级的images目录下。
欢迎您直接提RP修复这个readme问题，也欢迎您继续踊跃提出反馈，大家携手建设FISCO-BCOS社区。
再次表示感谢！
