### ISSUE TITLE
Can't start a node in  v2.0

### ISSUE THREAD

**Issue by YoungWilliamZ** [FISCO-BCOS/FISCO-BCOS#592]
I follow the instruction from [here](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/enterprise_quick_start_agency.html) to set up.

After I use `bash ./data/start_all.sh` to start node, there is no error like below:

``` bash
[root@data]# ./start_all.sh 
start node_47.107.XXX_30303
 start node_47.107.XXX_30303 ...
nohup: appending output to ‘nohup.out’
 node_47.107.XXX_30303 start successfully
start node_47.107.XXX_30304
 start node_47.107.XXX_30304 ...
nohup: appending output to ‘nohup.out’
 node_47.107.XXX_30304 start successfully
```

But when I use `ps -ef | grep fisco`, there is no fisco running

Then I check the `nohup.out`, which show that:

```
[INITIALIZER][RPCInitializer]init RPC/channelserver failed,check channel_listen_port=20202,check jsonrpc_listen_port=8545,EINFO=Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Cannot assign requested address
```

I have open all the ports that need to use and I succeed in running v1.5 currently and I have shut the v1.5 nodes down.

My `mchain.ini` is

```
[group]
group_id=1

[node0]
p2p_ip=47.107.XXX
rpc_ip=47.107.XXX
p2p_listen_port=30303
channel_listen_port=20202
jsonrpc_listen_port=8545

[node1]
p2p_ip=47.107.XXX
rpc_ip=47.107.XXX
p2p_listen_port=30304
channel_listen_port=20203
jsonrpc_listen_port=8546
```

Where `47.107.XXX` is the public ip of the host.

So, how to solve this?

**Comment by YoungWilliamZ** [comment]
I find the problem, the file `config.ini` generated in node_xxxx_30303 is not good.

config.ini:

```
[rpc]
listen_ip = 47.107.XXX
channel_listen_port = 20202
jsonrpc_listen_port = 8545

[p2p]
listen_ip = 0.0.0.0
listen_port = 30303
....
```

The problem is that the listen ip of rpc is the public ip which should be 0.0.0.0.

**Comment by HaoXuan40404** [comment]
thks, yes, we had fixed this problem at commit commit88384aa27626e575c8bae763bbb90923ef61879f, now the default is value of p2p_ listen_ip is 0.0.0.0. 
How this problem happened?

**Comment by YoungWilliamZ** [comment]
I think the problem is about rpc ,not p2p. 

Maybe the reason is that the instruction is not detailed enough.

**Comment by HaoXuan40404** [comment]
I think your cloud server NIC address is not 47.107.XXX. It's a common problem of 
Virtual address. For security, rpc_ip can't be 0.0.0.0 in practice,
unrestricted rpc access should be prohibited

**Comment by HaoXuan40404** [comment]
Since the public IP address is very rare, enterprises are beginning to use multi-level NAT translation. IP address obtained by dialing in your router is not the public IP address, but the intranet IP of the operator. The NAT conversion is sent out from the carrier's external network IP. You should set the rpc_ip at some specific accessible addresses like 127.0.0.1

**Comment by YoungWilliamZ** [comment]
Thanks, I check the ip, and found that it is just the same as you said.
