### ISSUE TITLE
v2.0 Log 显示 `handshakeServer Handshake failed,errorValue=336105671,message=peer did not return a certificate,endpoint=47.107.XXXX:40972`

### ISSUE THREAD

**Issue by YoungWilliamZ** [FISCO-BCOS/FISCO-BCOS#593]
After using `tail -f data/node*/log/log*  | grep warning`, then:

```
warning|2019-03-25 04:09:00.428048| [NETWORK][Host]handshakeServer Handshake failed,errorValue=336105671,message=peer did not return a certificate,endpoint=47.107.XXXX:40972
warning|2019-03-25 04:09:00.429135| [NETWORK][Host]handshakeClient failed,endpoint=47.107.XXXX:30303,errorValue=335544539,message=short read
warning|2019-03-25 04:09:00.511880| [NETWORK][Host]handshakeClient failed,endpoint=106.14.XXXX:30304,errorValue=335544539,message=short read
warning|2019-03-25 04:09:00.522241| [NETWORK][Host]handshakeClient failed,endpoint=106.14.XXXX:30303,errorValue=335544539,message=short read
warning|2019-03-25 04:09:01.569903| [g:1][p:264][CONSENSUS][PBFT]ViewChangeWarning: not caused by omit empty block ,v=277,toV=278,highNum=0,hash=438b82ff...,nodeIdx=0,myNode=459042e1...
```

请问下这是配置不对吗？
虽然已经开始共识了, 刚刚搭建起来，还没开始部署合约。

**Comment by bxq2011hust** [comment]
```bash
tail -f node0/log/log*  | grep +++
```
如果能够通过日志看到`++++++++++++++++`输出，表示链是在正常共识就是正常。
节点启动时尝试连接其他节点，此时其他节点没有启动，则可能输出警告。

**Comment by bxq2011hust** [comment]
> After using `tail -f data/node*/log/log* | grep warning`, then:
> 
> ```
> warning|2019-03-25 04:09:00.428048| [NETWORK][Host]handshakeServer Handshake failed,errorValue=336105671,message=peer did not return a certificate,endpoint=47.107.XXXX:40972
> warning|2019-03-25 04:09:00.429135| [NETWORK][Host]handshakeClient failed,endpoint=47.107.XXXX:30303,errorValue=335544539,message=short read
> warning|2019-03-25 04:09:00.511880| [NETWORK][Host]handshakeClient failed,endpoint=106.14.XXXX:30304,errorValue=335544539,message=short read
> warning|2019-03-25 04:09:00.522241| [NETWORK][Host]handshakeClient failed,endpoint=106.14.XXXX:30303,errorValue=335544539,message=short read
> warning|2019-03-25 04:09:01.569903| [g:1][p:264][CONSENSUS][PBFT]ViewChangeWarning: not caused by omit empty block ,v=277,toV=278,highNum=0,hash=438b82ff...,nodeIdx=0,myNode=459042e1...
> ```
> 请问下这是配置不对吗？
> 虽然已经开始共识了, 刚刚搭建起来，还没开始部署合约。

问题解决了吗？我将会关闭这个issue，如果问题还没有解决，欢迎随时再次打开
