### ISSUE TITLE
如何在java代码中获取智能合约普通方法的返回值

### ISSUE THREAD

**Issue by bailiyi** [FISCO-BCOS/FISCO-BCOS#60]
在合约中有以下方法,在数组中添加元素,然后返回元素的下标:
function AddFrozenStrategy(string title_, string desc_) onlyOwner public returns (uint256) {
        StrategyRecord memory new_record = StrategyRecord({
            title: title_,
            desc: desc_,
            });
        strategy_records.push(new_record);
        return strategy_records.length -1;
    }
java的自动生成的包装方法是:
public Future<TransactionReceipt> AddFrozenStrategy(Utf8String title_, Utf8String desc_) {
        Function function = new Function("AddFrozenStrategy", Arrays.<Type>asList( title_, desc_), Collections.<TypeReference<?>>emptyList());
        return executeTransactionAsync(function);
    }
返回的泛型是TransactionReceipt.这个貌似无法获取到合约的返回值。
请问这种情况应该怎样获取返回值？

**Comment by pengbs** [comment]
这个问题可以通过事件获取返回值
