### ISSUE TITLE
FISCO BCOS 2.0有压测工具吗？

### ISSUE THREAD

**Issue by jiangxianliang007** [FISCO-BCOS/FISCO-BCOS#711]
我部署了4个节点的链，想做下性能测试。请问下有对应的压测工具吗？

**Comment by HaoXuan40404** [comment]
2.0的压测工具正在整理，之后会发布

**Comment by jiangxianliang007** [comment]
有大致的时间节点吗？

**Comment by HaoXuan40404** [comment]
> 有大致的时间节点吗？

rc2发布后会有一个初级版本，后续会提供完整版本的
rc2预计节后发布

**Comment by bxq2011hust** [comment]
> 有大致的时间节点吗？

请查看这里
https://mp.weixin.qq.com/s/XO3aBR5GkJaZLymasroCAg
