### ISSUE TITLE
节点log出现handshake failed

### ISSUE THREAD

**Issue by HaoXuan40404** [FISCO-BCOS/FISCO-BCOS#722]
![image](https://user-images.githubusercontent.com/34049754/56948696-7e839e00-6b63-11e9-800a-2fa409f3da33.png)
2.0节点异常，log中出现handshake failed

**Comment by bxq2011hust** [comment]
FISCO-BCOS节点建立连接时需要双向SSL验证，当证书错误时会出现握手失败。请按照下面的链接，检查证书是否正确
https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/enterprise_tools/operation.html#handshake-failed

**Comment by zhengcookie** [comment]
> FISCO-BCOS节点建立连接时需要双向SSL验证，当证书错误时会出现握手失败。请按照下面的链接，检查证书是否正确 https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/enterprise_tools/operation.html#handshake-failed



> FISCO-BCOS节点建立连接时需要双向SSL验证，当证书错误时会出现握手失败。请按照下面的链接，检查证书是否正确 https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/enterprise_tools/operation.html#handshake-failed

链接挂了
