### ISSUE TITLE
请教下，用户地址是怎么生成的？

### ISSUE THREAD

**Issue by liu578101804** [FISCO-BCOS/FISCO-BCOS#736]
用户地址怎么来的？我没看到有相关文档，谢谢

**Comment by liu578101804** [comment]
这个privateKey和CA证书的私钥有什么关系？你们有时怎么管控这些用户的？

**Comment by bxq2011hust** [comment]
> 用户地址怎么来的？我没看到有相关文档，谢谢

https://github.com/FISCO-BCOS/LargeFiles/blob/master/tools/gen_account.sh
