### ISSUE TITLE
./scripts/install_deps.sh error in Linux Mint 

### ISSUE THREAD

**Issue by flowhub-dev** [FISCO-BCOS/FISCO-BCOS#79]
line 188 :  Ubuntu|Linux Mint) in Linux Mint OS can't catched, Maybe it can be changed to this :
Ubuntu|Linux*Mint)

**Comment by fisco-dev** [comment]
fisco-bcos目前只支持centos 7.2+ 64位的版本以及ubuntu 16.04 64版本
