### ISSUE TITLE
使用FISCO-BCOS搭建国密版联盟链(BCOS版本2.0.0-rc2 gm)

### ISSUE THREAD

**Issue by HandsomeTea** [FISCO-BCOS/FISCO-BCOS#825]
### 场景描述

1. 假设多家机构组成联盟，每家机构都派出代表进驻**联盟委员会**(在本次测试组网部署中，假设有ABCD四家机构)。
2. 联盟决定使用国密版BCOS组建**联盟链**。
3. **联盟委员会**确定联盟链组网模式(主要确认节点数量、节点分布、群组构成情况和信息交换方式等)。
      - 本次搭建联盟链，使用同一服务器的不同端口模拟不同节点，使用不同文件夹模拟不同机构，使用拷贝指令模拟机构间组网时的信息交换方式(实际部署可通过U盘、邮件、网络消息传输等方式传递)。组网模式假设如下：

        > - **机构A**
              [节点0]: 127.0.0.1:30300
              [节点1]:  127.0.0.1:30301
              [节点2]:  127.0.0.1:30302

        > - **机构B**
            [节点3]:  127.0.0.1:30303

        > - **机构C** 
           [节点4]: 127.0.0.1:30304
      
        > - **机构D**
           暂时不参与联盟链的组建，没有节点

        > **机构A**所有节点与**机构B**所有节点组成**群组1**，使用pbft共识机制
        > **机构B**所有节点与**机构C**所有节点组成**群组2**，使用raft共识机制
        > 联盟链所有节点都参与共识

4. **联盟委员会**生成联盟链的**链证书**(自建或向CA公司申请，本次搭建联盟链使用BCOS提供的企业级部署工具自建，另外CA公司也无法提供国密版的证书)。
5. 联盟的每家机构(机构A、B、C、D)向联盟委员会申请自己机构的**机构证书**。
6. 联盟每个机构，根据**联盟委员会**确定的联盟链组网模式，使用BCOS提供的企业级部署工具，生成机构下属的**节点部署程序**，并按组网模式修改对应**节点部署程序的配置文件**。
7. 联盟所有机构**部署并启动**下属节点程序，组成联盟链。
8. 组网变动。
      - 机构A

         > - **机构A**认为自己下属节点太多，消耗资源，准备从**群组1**移除**节点2**。
         > - **机构A**为了提高业务处理效率，将**节点1**设置为**观察节点**，不再参与共识。

      - 机构D

         > - **机构D**想加入**群组2**，并添加机构D下属节点：
         >      [**节点5**]: 127.0.0.1:30305
         > - **机构D**和**机构B**想用**节点3**和**节点5**组成新群组：**群组3**
9. **机构A**和**机构D**向**联盟委员会**提出组网变动**申请**。
10. **联盟委员会**同意机构A和机构D的组网变动申请。
11. 机构A开始组网变动操作。
      - **群组1**的**机构A或机构B**根据联盟委员会同意的**机构A**组网变动申请，使用**控制台**或**SDK**发送节点2退出和节点1转换为观察节点的指令，完成机构A的组网变动请求。
12. 机构D开始组网变动操作。
      - 第5步中，**机构D**已向联盟委员会申请机构D的机构证书。现在，机构D使用BCOS提供的企业级部署工具，生成机构D下属的节点部署程序，根据新的组网模式，修改**节点5部署程序的配置文件**，将节点5部署程序部署到节点5对应的服务器上，启动节点5，**准备**加入联盟链。
      - **机构D**向**群组2**的**机构B或C**发送节点5入网请求，等待机构B或C使用**控制台**或**SDK**发送节点入网指令。
      - 机构B或C根据联盟委员会同意的机构D组网变动申请，发送节点5入网指令，**注册**节点5加入群组共识。
13. 结束。

### _[1] 准备工作_

   企业级部署工具服务器目录 `/usr/local/test-BCOS/` 。
   测试链的节点部署模拟目录 `/usr/local/test-BCOS/test-chain/` ，以下简称 `test-chain` 。

  

-  准备BCOS企业级部署工具。

         环境要求
         python 2.7+/3.6+
         openssl1.0.2k+

 

-  首先在服务器上放置企业级部署工具程序：

   `cd /usr/local/test-BCOS/`

   `git clone https://github.com/FISCO-BCOS/generator.git` ，没有安装git的服务器，可以使用ftp工具上传已经下载的企业级部署工具程序。

   得到企业级部署工具根目录 `/usr/local/test-BCOS/generator` ，以下简称 `generator` 。

   

- 确保BCOS企业级部署工具程序的服务器权限：

   `chmod -R 777 generator/`。

   

- 安装企业级部署工具：

   `cd generator`

   `./scripts/install.sh`

 

- 查看企业级部署工具版本：

  `cd generator`

  `./generator -v` ，如果安装成功，结果如：

     >  INFO | v1.0.0-rc2

     所以本次测试部署使用的是 `v1.0.0-rc2` 版本的企业级部署工具。
   

 

- 为企业级部署工具下载国密版BCOS：

   `cd generator`

   `./generator --download_fisco ./meta -g`

  执行完成，国密版的 `fisco-bcos` 二进制文件下载到了 `generator/meta/` 文件夹下。BCOS企业级部署工具的使用，必须保证 `fisco-bcos` 二进制文件存放在 `generator/meta/` 文件夹下。

   

- 查看BCOS国密版本：

   `cd generator`

   `./meta/fisco-bcos -v` ，结果如：

         FISCO-BCOS Version : 2.0.0-rc2 gm
         Build Time         : 20190506 10:55:31
         Build Type         : Linux/clang/RelWithDebInfo
         Git Branch         : master
         Git Commit Hash    : 1bded79259c2b98a5e713dbbceeda53056acc6d7

   所以本次测试部署使用的是 `2.0.0-rc2 gm` 国密版本的BCOS。

### _[2] 联盟委员会生成联盟链证书_

本次搭建联盟链，假设**联盟委员会**采用BCOS提供的企业级部署工具**自建**证书命令生成了链证书，操作如下：

- 创建 `generator/key_crt_dir` 目录，将生成的所有证书都存放在该目录下：

    `cd generator`

    `mkdir key_crt_dir`

- 创建链证书，搭建**国密版**联盟链需要两套证书(国密版和普通版，猜测普通版用于生成**证书链**中的sdk证书环节):

    `cd generator`

    `./generator --generate_chain_certificate ./key_crt_dir/chain`

    `./generator --generate_chain_certificate ./key_crt_dir/chain-g -g`

     在 `generator/key_crt_dir/chain` 下生成的是普通版链证书，在 `generator/key_crt_dir/chain-g` 下生成的是国密版链证书。

- 企业级部署工具所有需要证书的操作，都需要将**证书**(证书其实是公钥信息，私钥[.key文件]由**联盟委员会**妥善保管)放置于 `generator/meta/` 目录下：

     `cd generator`

    `cp ./key_crt_dir/chain-g/gmca.crt ./meta/gmca.crt`

     `cp ./key_crt_dir/chain/ca.crt ./meta/ca.crt`

### [3] _机构向联盟委员会申请机构证书_

本次搭建联盟链，使用BCOS企业级部署工具提供的证书生成指令生成机构证书。

   

-  将第2步的 `generator` 文件夹(里面**已经包含了链证书**)复制为同级目录 `generator-A`、 `generator-B` 、 `generator-C` 、 `generator-D` ，分别用于模拟联盟委员会为ABCD四家机构颁发证书的操作：

    `cd /usr/local/test-BCOS/`

    `cp -r generator generator-A && cp -r generator generator-B && cp -r generator generator-C && cp -r generator generator-D`

    以下简称为`generator-A`、`generator-B`、`generator-C`、`generator-D`。

     - 模拟联盟委员会为机构A颁发证书
        `cd generator-A`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyA_key_crt_dir ./key_crt_dir/chain test-agencyA`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyA-g_key_crt_dir ./key_crt_dir/chain-g test-agencyA -g`

        `generator-A/key_crt_dir/agencyA-g_key_crt_dir` 里面生成的是机构A的国密版机构证书，`generator-A/key_crt_dir/agencyA_key_crt_dir` 里面生成的是机构A的普通版机构证书。
        同样的，把证书放置于 `generator-A/meta` 文件夹下：
        `cd generator-A`

        `cp ./key_crt_dir/agencyA_key_crt_dir/test-agencyA/agency.crt  ./key_crt_dir/agencyA_key_crt_dir/test-agencyA/agency.key ./meta/`

        `cp ./key_crt_dir/agencyA-g_key_crt_dir/test-agencyA/gmagency.crt  ./key_crt_dir/agencyA-g_key_crt_dir/test-agencyA/gmagency.key ./meta/`

    - 模拟联盟委员会为机构B颁发证书
        `cd generator-B`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyB_key_crt_dir ./key_crt_dir/chain test-agencyB`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyB-g_key_crt_dir ./key_crt_dir/chain-g test-agencyB -g`

        `cp ./key_crt_dir/agencyB_key_crt_dir/test-agencyB/agency.crt  ./key_crt_dir/agencyB_key_crt_dir/test-agencyB/agency.key ./meta/`

        `cp ./key_crt_dir/agencyB-g_key_crt_dir/test-agencyB/gmagency.crt  ./key_crt_dir/agencyB-g_key_crt_dir/test-agencyB/gmagency.key ./meta/`

    - 模拟联盟委员会为机构C颁发证书
        `cd generator-C`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyC_key_crt_dir ./key_crt_dir/chain test-agencyC`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyC-g_key_crt_dir ./key_crt_dir/chain-g test-agencyC -g`

        `cp ./key_crt_dir/agencyC_key_crt_dir/test-agencyC/agency.crt  ./key_crt_dir/agencyC_key_crt_dir/test-agencyC/agency.key ./meta/`

        `cp ./key_crt_dir/agencyC-g_key_crt_dir/test-agencyC/gmagency.crt  ./key_crt_dir/agencyC-g_key_crt_dir/test-agencyC/gmagency.key ./meta/`

    - 模拟联盟委员会为机构D颁发证书
        `cd generator-D`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyD_key_crt_dir ./key_crt_dir/chain test-agencyD`

        `./generator --generate_agency_certificate ./key_crt_dir/agencyD-g_key_crt_dir ./key_crt_dir/chain-g test-agencyD -g`

        `cp ./key_crt_dir/agencyD_key_crt_dir/test-agencyD/agency.crt  ./key_crt_dir/agencyD_key_crt_dir/test-agencyD/agency.key ./meta/`

        `cp ./key_crt_dir/agencyD-g_key_crt_dir/test-agencyD/gmagency.crt  ./key_crt_dir/agencyD-g_key_crt_dir/test-agencyD/gmagency.key ./meta/`

        **联盟委员会**为ABCD四家机构**颁发机构证书**结束。

### [4] _机构ABCD根据联盟委员会确认的组网模式，使用BCOS提供的企业级部署工具，生成机构下属的节点部署程序_

为了操作方便，使用第3步的 `generator-A` 、 `generator-B` 、 `generator-C` 、 `generator-D` 分别模拟ABCD四家机构使用企业级部署工具的操作(里面已经包含了每家机构的机构证书)。

- **机构A**的操作
        修改 `generator-A/conf/node_deployment.ini` 文件如下：

        

   > [group]
   > group_id=1
   > 
   > [node0]
   > p2p_ip=127.0.0.1
   > rpc_ip=127.0.0.1
   > p2p_listen_port=30300
   > channel_listen_port=20200
   > jsonrpc_listen_port=8545
   >         
   > [node1]
   > p2p_ip=127.0.0.1
   > rpc_ip=127.0.0.1
   > p2p_listen_port=30301
   > channel_listen_port=20201
   > jsonrpc_listen_port=8546
   >         
   > [node2]
   > p2p_ip=127.0.0.1
   > rpc_ip=127.0.0.1
   > p2p_listen_port=30302
   > channel_listen_port=20202
   > jsonrpc_listen_port=8547
        
       

    -  生成机构A下属节点的证书和p2p连接信息文件：

        `cd generator-A`

        `./generator --generate_all_certificates ./node_info -g`

        其中 `generator-A/node_info/gmcert*.crt` 为机构A下属的节点的证书文件， `generator-A/node_info/peers.txt` 为机构A下属的节点的p2p连接信息。

- **机构B**的操作
        修改 `generator-B/conf/node_deployment.ini` 文件如下：

      

   > [group]
   > group_id=1
   >
   > [node0]
   > p2p_ip=127.0.0.1
   > rpc_ip=127.0.0.1
   > p2p_listen_port=30303
   > channel_listen_port=20203
   > jsonrpc_listen_port=8548

        

    - 生成机构B下属节点的证书和p2p连接信息文件：

        `cd generator-B`

        `./generator --generate_all_certificates ./node_info -g`

- **机构C**的操作
        修改 `generator-C/conf/node_deployment.ini` 文件如下：

    >[group]
    >group_id=2
    >
    >[node0]
    >p2p_ip=127.0.0.1
    >rpc_ip=127.0.0.1
    >p2p_listen_port=30304
    >channel_listen_port=20204
    >jsonrpc_listen_port=8549

        

    - 生成机构C下属节点的证书和p2p连接信息文件：

        `cd generator-C`

        `./generator --generate_all_certificates ./node_info -g`

假设**群组1**成员机构确认由**机构A**生成**群组1创世区块**，创世区块的生成需要群组所有节点的证书和p2p连接信息。**机构A**收集群组1**其它所有**机构的节点证书(gmcert*.crt)和p2p连接信息文件(peers.txt，如果有多个其它机构，则**机构A**需要将收集到的这些机构的peers.txt**合并**为一个)并放置于 `generator-A/meta/` 下，本次搭建，群组1的“其它机构”**只有机构B**。

- **机构A**收集**群组1**其它机构下属节点的证书和节点连接信息，此过程使用拷贝指令模拟：
    
    `cd /usr/local/test-BCOS/`

    `cp ./generator-B/node_info/peers.txt ./generator-A/meta/group1-peers-all-without-A.txt`

    `cp ./generator-B/node_info/gmcert*.crt ./generator-A/meta/`

 - **机构A**根据收集到的peers信息，修改 `generator-A/conf/group_genesis.ini` 文件如下：
    
    >[group]
    >group_id=1
    >
    >[nodes]
    >node0=127.0.0.1:30300
    >node1=127.0.0.1:30301
    >node2=127.0.0.1:30302
    >node3=127.0.0.1:30303

        **注意**
        [nodes]的配置信息同peers一样，需要合并配置当前群组所有机构下属节点的连接信息(包括创世区块的生成机构)，本次测试**群组1**只有机构A和机构B。

- **机构A**根据 `generator-A/conf/group_genesis.ini` 内容生成**群组1创世区块**：
    
    `cd generator-A`

    `./generator --create_group_genesis ./group1_genesis -g`

    在 `generator-A/group1_genesis` 文件夹下生成了群组1的创世区块文件。

- **机构A**将**群组1的创世区块**和**机构A收集的群组1成员的节点p2p连接信息**分发给群组1其它机构(本次搭建，群组1只有机构B)，对应机构将机构A分发的文件放置于`meta`文件夹下。
    
    `cd /usr/local/test-BCOS/`

    `cp ./generator-A/group1_genesis/group.1.genesis ./generator-B/meta/`

    `cp ./generator-A/node_info/peers.txt ./generator-B/meta/group1-peers-all-without-B.txt`

- **机构A**生成下属节点部署程序：
    
    `cd generator-A`

    `./generator --build_install_package ./meta/group1-peers-all-without-A.txt ./agencyA_node -g`

    `generator-A/agencyA_node`文件夹下的`node*` 文件夹里便是机构A下属的节点初始部署程序。

-  **机构B**生成下属节点部署程序：

     `cd generator-B`

     `./generator --build_install_package ./meta/group1-peers-all-without-B.txt ./agencyB_node -g`

    `generator-B/agencyB_node` 文件夹下的 `node*` 文件夹里便是机构B下属的节点初始部署程序。

假设**群组2**成员确认由**机构C生成创世区块**，**机构C**收集群组2**其它所有**机构的节点证书(gmcert*.crt)和p2p连接信息文件(peers.txt，如果有多个其它机构，则**机构C**需要将收集到的这些机构的peers.txt**合并**为一个)并放置于 `generator-C/meta/` ，本次搭建联盟链，群组2的“其它机构”**只有机构B**。

- **机构C**收集**群组2**其它机构下属节点的证书和节点连接信息，此过程使用拷贝指令模拟：

    `cd /usr/local/test-BCOS/`

    `cp ./generator-B/node_info/peers.txt ./generator-C/meta/group2-peers-all-without-C.txt`

    `cp ./generator-B/node_info/gmcert*.crt ./generator-C/meta/`

- **机构C**根据收集到的peers信息，修改 `generator-C/conf/group_genesis.ini` 文件如下：

    >[group]
    >group_id=2
    >
    >[nodes]
    >node3=127.0.0.1:30303
    >node2=127.0.0.1:30304

         **注意**
        [nodes]的配置信息同peers一样，需要合并配置当前群组所有机构下属节点的连接信息(包括创世区块的生成机构)，本次测试**群组2**只有机构C和机构B。

- **机构C**根据 `generator-C/conf/group_genesis.ini` 内容生成**群组2创世区块**：

    `cd generator-C`

    `./generator --create_group_genesis ./group2_genesis -g`

    在 `generator-C/group2_genesis` 文件夹下生成了群组2的创世区块文件。

- **机构C**将**群组2的创世区块**和**机构C收集的群组2成员的节点p2p连接信息**分发给群组2其它机构(本次搭建，群组2只有机构C)，对应机构将机构C分发的文件放置于 `meta` 文件夹下。

    `cd /usr/local/test-BCOS/`

    `cp ./generator-C/group2_genesis/group.2.genesis ./generator-B/meta/`

    `cp ./generator-C/node_info/peers.txt ./generator-B/meta/group2-peers-all-without-B.txt`

- **机构C**生成下属节点部署程序：
    
    `cd generator-C`

    `./generator --build_install_package ./meta/group2-peers-all-without-C.txt ./agencyC_node -g`

    `generator-C/agencyC_node` 文件夹下的 `node*` 文件夹里便是机构C下属的节点初始部署程序。

-  **机构B**使用企业级部署工具提供的指令，给定参数，执行加入群组2

     `cd generator-B`

    `./generator --add_group ./meta/group.2.genesis ./agencyB_node`

    `./generator --add_peers ./meta/group2-peers-all-without-B.txt ./agencyB_node`

-  修改**群组2**默认的共识算法为raft：

    机构B和机构C分别修改 `generator-B/agencyB_node/node_127.0.0.1_30303/conf/group.2.genesis` 、 `generator-C/agencyC_node/node_127.0.0.1_30304/conf/group.2.genesis` 文件的[group][consensus]配置项如下(只修改以下列出的项)：

    >[group]
    >id = 2

    >[consensus]
    >consensus_type = raft

    至此，
    机构A下属的节点部署程序位于 `generator-A/agencyA_node/node*` 文件夹下。
    机构B下属的节点部署程序位于 `generator-B/agencyB_node/node*` 文件夹下。
    机构C下属的节点部署程序位于 `generator-C/agencyC_node/node*` 文件夹下。

### _[5] 联盟所有机构**部署并启动**下属节点程序，启动联盟链_

-  **机构A**部署将下属节点程序(使用拷贝指令模拟)：

    `cd /usr/local/test-BCOS/`
    
    `cp -r ./generator-A/agencyA_node/node* ./test-chain/ `

-  **机构B**部署将下属节点程序(使用拷贝指令模拟)：

    `cd /usr/local/test-BCOS/`

    `cp -r ./generator-B/agencyB_node/node* ./test-chain/ `

-  **机构C**部署将下属节点程序(使用拷贝指令模拟)：

    `cd /usr/local/test-BCOS/`

    `cp -r ./generator-C/agencyC_node/node* ./test-chain/`

    

- 各机构节点分别启动，如：节点0启动如下：

    
    `cd test-chain/node_127.0.0.1_30300`

    `./start.sh`

    

- 查看启动状态：

    `ps -ef | grep -v grep | grep fisco-bcos`

    至少会看到一条fisco-bcos的进程数据。

### _[6] 为**节点**配置控制台_

    

- 控制台下载：

    `cd /usr/local/test-BCOS/`

    `bash <(curl -s https://raw.githubusercontent.com/FISCO-BCOS/console/master/tools/download_console.sh)`

    执行完成，下载了控制台程序的压缩包，并解压到了 `/usr/local/test-BCOS/console` 下。

    

- 下载国密版合约编译jar包(版本根据合约脚本的版本而定)：

    `cd /usr/local/test-BCOS/console`

    `curl -LO https://github.com/FISCO-BCOS/LargeFiles/raw/master/tools/solcj/solcJ-all-0.4.25-gm.jar`

    执行完成，国密版合约编译jar包下载到了 `/usr/local/test-BCOS/console` 下。

   

- 将默认的合约编译包替换为(不要手动替换，使用控制台提供的替换脚本)国密版编译包：

    `cd /usr/local/test-BCOS/console`

    `./replace_solc_jar.sh solcJ-all-0.4.25-gm.jar`

    

- 使用默认的控制台配置文件(控制台提供了**控制台配置文件**的样板 `console/conf/applicationContext-sample.xml` )：

    `cd /usr/local/test-BCOS/console`

    `cp conf/applicationContext-sample.xml conf/applicationContext.xml`

本次搭建联盟链，为**机构A-节点0:127.0.0.1:30300**、**机构B-节点3:127.0.0.1:30303**、**机构C-节点4:127.0.0.1:30304**三个节点配置控制台，使用拷贝命令模拟，实际部署时，第[6]的以上几步需要在每个需要配置控制台的节点上操作，操作目录可自行选择。

   

- 将控制台程序分发到需要配置控制台的节点服务器上，此过程使用拷贝指令模拟：

    `cd /usr/local/test-BCOS/`

    `cp -r console/ test-chain/node_127.0.0.1_30300/console && cp -r console/ test-chain/node_127.0.0.1_30303/console && cp -r console/ test-chain/node_127.0.0.1_30304/console`

    

- 修改**机构A-节点0:127.0.0.1:30300**、**机构B-节点3:127.0.0.1:30303**、**机构C-节点4:127.0.0.1:30304**三个节点配置的控制台的配置文件`console/conf/applicationContext.xml`(国密开关、群组信息、channel连接地址等)，参考[这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/manual/console.html#id7)和[这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/sdk/sdk.html#spring)。

    

- 机构为控制台生成控制台sdk证书：

    -  **机构A**为下属**节点0**控制台生成sdk证书：

        `cd generator-A`

        `./generator --generate_sdk_certificate ./key_crt_dir/dir_sdk_ca ./key_crt_dir/agencyA_key_crt_dir/test-agencyA`

        注意，生成sdk的指令并没有指定具体的节点信息，只指定了机构的信息(机构证书)，所以，访问同一个机构所属的不同节点(如控制台访问、web3sdk访问等)，可以使用同样的sdk证书。

        在 `generator-A/key_crt_dir/dir_sdk_ca` 文件夹下生成的便是sdk证书信息。将sdk证书配置到控制台上，此过程使用拷贝指令模拟：
        
        `cd /usr/local/test-BCOS/`

        `cp generator-A/key_crt_dir/dir_sdk_ca/sdk/* test-chain/node_127.0.0.1_30300/console/conf/`

        **节点0**控制台配置完成。

    -  **机构B**为下属**节点3**控制台生成sdk证书：

        `cd generator-B`

        `./generator --generate_sdk_certificate ./key_crt_dir/dir_sdk_ca ./key_crt_dir/agencyB_key_crt_dir/test-agencyB`

        在 `generator-B/key_crt_dir/dir_sdk_ca` 文件夹下生成的便是sdk证书信息。将sdk证书配置到控制台上，此过程使用拷贝指令模拟：
        
        `cd /usr/local/test-BCOS/`

        `cp generator-B/key_crt_dir/dir_sdk_ca/sdk/* test-chain/node_127.0.0.1_30303/console/conf/`

        **节点3**控制台配置完成。

    -  **机构C**为下属**节点4**控制台生成sdk证书：

        `cd generator-C`

        `./generator --generate_sdk_certificate ./key_crt_dir/dir_sdk_ca ./key_crt_dir/agencyC_key_crt_dir/test-agencyC`

        在 `generator-C/key_crt_dir/dir_sdk_ca` 文件夹下生成的便是sdk证书信息。将sdk证书配置到控制台上，此过程使用拷贝指令模拟：
        
        `cd /usr/local/test-BCOS/`

        `cp generator-C/key_crt_dir/dir_sdk_ca/sdk/* test-chain/node_127.0.0.1_30304/console/conf/`

        **节点4**控制台配置完成。

    

- 启动控制台(如节点4)：

    `cd test-chain/node_127.0.0.1_30304/console`

    `./start.sh`

    

- **控制台常用命令**：

    查看控制台版本： `getNodeVersion`，结果如下：

        {                                                                                                                                                     
            "Build Time":"20190506 10:55:31",                                                                                                                 
            "Build Type":"Linux/clang/RelWithDebInfo",                                                                                                        
            "Chain Id":"1",                                                                                                                                   
            "FISCO-BCOS Version":"2.0.0-rc2 gm",                                                                                                              
            "Git Branch":"master",                                                                                                                            
            "Git Commit Hash":"1bded79259c2b98a5e713dbbceeda53056acc6d7",                                                                                     
            "Supported Version":"2.0.0-rc2"                                                                                                                   
        }      
    所以，本次搭建部署的控制台匹配的是 `2.0.0-rc2 gm` 版本的BCOS。
    获取当前节点所有p2p连接信息： `getPeers`。
    获取当前群组下属的节点id列表： `getGroupPeers`。
    获取当前群组的区块的高度： `getBlockNumber`。
    查看当前节点所在群组的共识节点列表： `getSealerList`。
    获取当前节点从属的所有群组的群组id列表： `getGroupList`。
    切换当前节点从属的群组： `switch [groupId]`。
    获取当前群组共识信息： `getConsensusStatus`，结果[参考这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/api.html#getconsensusstatus)。
    获取当前节点控制台当前群组部署的合约信息： `getDeployLog`。
    退出控制台： `q` 或 `quit` 或 `exit`。

### _[7] 组网变动_

    
    

- **机构A**组网变动：

    机构A根据**联盟委员会**同意的机构A组网变动申请，通过**控制台**或**sdk**操作完成机构A下属的节点1和节点2的组网变动。假设机构A通过下属的节点0的控制台进行操作。

    

    - 机构A进入**群组1**的**节点0:127.0.0.1:30300**控制台：

       `cd test-chain/node_127.0.0.1_30300/console`

       `./start.sh`

       `getPeers`

   

    -  机构A根据以上执行结果，得知机构A下属**节点2**的**节点id(NodeID)**和**节点1**的**节点id(NodeID)**，假设如：

       [节点2]： `29b142d5391037e29cbe0c13619bfc481c684faf9171a07f78b245bf0b6bb347a17caec5abf310bb7652714e2f8ae3b4b69508c529deab7e75859e2f410787ca`

       [节点1]： `4d429e3ac565b5318ea17fa04b79e7b30821cf494de9ed36a87e82d67d475ec3115906802b2c42d2ed2ef4ce570b319098f6e887be2fa894bc57f7a542b1229a`

    

    - **机构A**从**群组1**移除**节点2**(控制台执行)：

       `removeNode 29b142d5391037e29cbe0c13619bfc481c684faf9171a07f78b245bf0b6bb347a17caec5abf310bb7652714e2f8ae3b4b69508c529deab7e75859e2f410787ca`

    

    - **机构A**从**群组1**将**节点1**设置为观察节点(控制台执行)：

       `addObserver 4d429e3ac565b5318ea17fa04b79e7b30821cf494de9ed36a87e82d67d475ec3115906802b2c42d2ed2ef4ce570b319098f6e887be2fa894bc57f7a542b1229a`

    以上操作如果无误，都会提示如下，表示操作成功：

        {                                                                                                                                                     
            "code":0,                                                                                                                                         
            "msg":"success"                                                                                                                                   
        }    

    节点角色变换参考[这里](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/manual/node_management.html#id2)。至此，机构A的组网变动操作结束。

    

- **机构D**组网变动操作：

    

    - **机构D**获取**群组2**的**创世区块**文件，假设由**机构C**根据**联盟委员会**同意的机构D组网变动申请，将群组2的创世区块交给机构D(放置于机构D的 `generator-D/meta/` 文件夹下)，此过程使用拷贝指令模拟。

       `cd /usr/local/test-BCOS/`

       `cp ./generator-C/group2_genesis/group.2.genesis ./generator-D/meta/`
   
    

    - 机构D根据自己申请的组网变动的节点信息，修改 `generator-D/conf/node_deployment.ini` 文件如下:

       >[group]
       >group_id=2
       >
       >[node0]
       >p2p_ip=127.0.0.1
       >rpc_ip=127.0.0.1
       >p2p_listen_port=30305
       >channel_listen_port=20205
       >jsonrpc_listen_port=8550

    

   - 机构D生成自己下属的节点5证书和p2p连接信息：

      `cd generator-D`

      `./generator --generate_all_certificates ./node_info -g`

       其中 `generator-D/node_info/gmcert*.crt` 为机构D下属的节点的证书文件， `generator-D/node_info/peers.txt` 为机构D下属的节点的p2p连接信息。

    

    - **机构D**获取**群组2**其他节点p2p连接信息，群组2现有机构成员**机构B**和**机构C**根据**联盟委员会**同意的机构D组网变动申请，将自己下属节点的p2p连接信息发送给机构D，此过程使用拷贝指令模拟：

       `cd /usr/local/test-BCOS/`

       `cp ./generator-B/node_info/peers.txt ./generator-D/meta/peersB.txt`

       `cp ./generator-C/node_info/peers.txt ./generator-D/meta/peersC.txt`

       并手动将 `generator-D/meta/peersB.txt` 、 `generator-D/meta/peersC.txt` 合并为 `generator-D/meta/group2-peers-all-without-D.txt` 。

    

    - 此时，**机构D**可生成下属节点部署程序：

        `cd /usr/local/test-BCOS/`

        `./generator --build_install_package ./meta/group2-peers-all-without-D.txt ./agencyD_node -g`

        在 `generator-D/agencyD_node/node_127.0.0.1_30305/` 下生成的便是节点5的服务器部署程序。

   

    - 修改 `generator-D/agencyD_node/node_127.0.0.1_30305/conf/group.2.genesis` 里面[group][consensus]配置项如下(只修改以下列出的项)：

        >[group]
        >id = 2

        >[consensus]
        >consensus_type = raft

       至此，机构D下属的节点部署程序位于 `generator-D/agencyD_node/node*` 文件夹下。

   

    -  机构D将节点5部署到对应服务器上，此过程依然使用拷贝指令模拟：

       `cd /usr/local/test-BCOS/`

       `cp -r ./generator-D/agencyD_node/node* ./test-chain/`
    
   

    - 启动节点5：

       `cd /usr/local/test-BCOS/node_127.0.0.1_30305`

       `./start.sh`

    

    - 机构C进入下属**节点4**的控制台：

        `cd test-chain/node_127.0.0.1_30304/console`

       `./start.sh`

    

    - 在控制台执行：

       `getPeers`

        便可看到**节点5**信息，其中，节点5的 `NodeId` 假设如下：
 `29ac02dc07f77ff654cd58195aca04649dbbc20bb138fe32965c1663b8259d9cfceab4fb0550a3dd53db57cb83d19992d60ff9970b42c1b83eaa56a1dde6442c`

        说明机构D下属节点5已经加入到群组2。

    

    - 再执行：  `getConsensusStatus`

        可以看到**群组2**共识信息中 `nodeNum` 为2(此时群组2有三个成员节点)，说明节点5此时并没有参与群组2的raft共识，是一个观察节点。

    

    - 再执行： 

         `addSealer 29ac02dc07f77ff654cd58195aca04649dbbc20bb138fe32965c1663b8259d9cfceab4fb0550a3dd53db57cb83d19992d60ff9970b42c1b83eaa56a1dde6442c`

    结果如下则操作成功：

        {                                                                                                                                                     
            "code":0,                                                                                                                                         
            "msg":"success"                                                                                                                                   
        }  

    

    - 再次执行：  `getConsensusStatus`

        可以看到**群组2**共识信息中 `nodeNum` 为3，说明节点5此时已经参与群组2的raft共识。

    

- **机构B**的**节点3**和**机构D**的**节点5**组建**群组3**组网变动操作。

    

    假设由**机构B**生成**群组3**的创世区块文件，**机构B**收集**群组3**下属节点3和节点5的证书和p2p连接信息，**收集证书**的过程使用拷贝指令模拟：

    `cd /usr/local/test-BCOS/`

    `cp ./generator-D/node_info/gmcert_127.0.0.1_30305.crt ./generator-B/meta/`

    
    因为组网变动申请已经指定了**群组3的成员节点**，所以不需要机构D将下属所有节点的p2p连接信息发给机构B(虽然所有的就是只有节点5)，只需要告诉机构B节点5的p2p连接信息，假设机构D告知机构B节点5的p2p连接信息为： `127.0.0.1:30305` 。

    

    - **机构B**修改 `generator-B/conf/group_genesis.ini` 文件如下：

       >[group]
       >group_id=3
       >
       >[nodes]
       >node0=127.0.0.1:30303
       >node1=127.0.0.1:30305

   

    -  **机构B**生成**群组3**创世区块：

       `cd generator-B`

       `./generator --create_group_genesis ./group3_genesis -g`

    在 `generator-B/group3_genesis/` 下生成的便是**群组3**的创世区块文件。由此步操作可知，生成创世区块的机构收集群组所有节点的p2p连接信息只是为了**方便修改** `group_genesis.ini` 文件的 [nodes] 配置项，以生成群组创世区块，并不是一定需要按照文件交付的方式采集，该收集过程，群组每家机构都可自行收集，无需等待生成创世区块的机构分发，生成创世区块的机构与其它机构**不同**的是，生成创世区块的机构**必须**有群组所有节点的**节点证书**，才能生成群组的创世区块。

    

    - 机构B需将群组3的创世区块文件交给机构D，此过程使用拷贝指令模拟：

       `cd /usr/local/test-BCOS/`

       `cp -r generator-B/group3_genesis generator-D/`

    

    - 机构B和机构D将群组3创世区块文件( `group.3.genesis` 和 `group.3.ini` )部署到已经部署的**节点3**和**节点5**服务器程序中，此过程使用拷贝指令模拟：

       `cd /usr/local/test-BCOS/`

       `cp generator-B/group3_genesis/group.3* test-chain/node_127.0.0.1_30303/conf/`

       `cp generator-D/group3_genesis/group.3* test-chain/node_127.0.0.1_30305/conf/`

    

    - **重启**节点3和节点5，群组3组建成功，组网变动操作结束。

       此时再次进入节点3de控制台：

       `cd /usr/local/test-BCOS/test-chain/node_127.0.0.1_30303/console/`

       `./start.sh`

    

    - 执行切换群组的操作：

 
       `switch 3`

       发现无法切换到群组3，因为节点3的控制台配置文件中还没有添加群组3的配置，重新修改节点3的控制台的配置文件，重启控制台，就可以切换到群组3。

**Comment by HaoXuan40404** [comment]
👍

**Comment by JimmyShi22** [comment]
👍
