### ISSUE TITLE
区块链浏览器 无法正常搭建的解决方法

### ISSUE THREAD

**Issue by linbin524** [FISCO-BCOS/FISCO-BCOS#866]
1、环境准备

1.1 环境 | 版本

Java | jdk1.8.0_121或以上版本 需要配置要指定/bin/java 
python | 2.7
MySQL-python | 1.2.5
数据库 | mysql-5.6或以上版本

1.2 python 虽然有，但是可能还会失败，需要进行如下安装

 MySQL-python部署

CentOS

sudo yum install -y MySQL-python
Ubuntu

sudo apt-get install -y python-pip
sudo pip install MySQL-python

3、官方文档和github 上的文档命令不一致

正确的命令应该是这样的

部署所有服务：

python deploy.py startAll

错误的是：python deploy.py run

4、配置问题

官方给出的处理方式，

服务端口不能小于1024

数据库IP：sed -i "s/127.0.0.1/${your_db_ip}/g" common.properties
数据库端口：sed -i "s/3306/${your_db_port}/g" common.properties
数据库用户名：sed -i "s/dbUsername/${your_db_account}/g" common.properties
数据库密码：sed -i "s/dbPassword/${your_db_password}/g" common.properties
数据库名称：sed -i "s/db_browser/${your_db_name}/g" common.properties

后端服务端口：sed -i "s/8088/${your_server_port}/g" common.properties
前端服务端口：sed -i "s/8081/${your_web_port}/g" common.properties

例子（将数据库IP由127.0.0.1改为0.0.0.0）：sed -i "s/127.0.0.1/0.0.0.0/g" application.yml

application.yml 但是这个文件不存在，建议直接修改这个文件common.properties配置

启动部署完成，还要到node节点下把 四个节点的rpc、p2p 端口 都放上去，才可以获取数据。

群组也要配置好。可以查看sdk 中的配置信息

其他问题找答案：https://github.com/FISCO-BCOS/fisco-bcos-browser/tree/master/deploy#8%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by HaoXuan40404** [comment]
👍

**Comment by mingzhenliu** [comment]
文档已经更新
