### ISSUE TITLE
如何使用docker自定义搭建bcos网络？

### ISSUE THREAD

**Issue by Jalins** [FISCO-BCOS/FISCO-BCOS#881]
如题

**Comment by HandsomeTea** [comment]
docker搭建BCOS联盟链没有意义，既然是联盟链，那节点肯定需要放在联盟成员的服务器上，联盟要控制准入的。如果是要使用docker统一部署环境，那也只能是一个节点一个docker镜像，目前BCOS的实际部署流程还没法docker化，因为部署流程有点复杂，必须按照实际使用情况而定。如果是要搭建测试环境，BCOS官方提供了体验BCOS的建链教程：[搭建单群祖4节点联盟链](https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/installation.html#id3)，或许这个可以放到docker里，但也仅仅是测试和体验，没有实际意义。

**Comment by Jalins** [comment]
好的，谢谢

**Comment by bxq2011hust** [comment]
https://cloud.docker.com/u/fiscoorg/repository/docker/fiscoorg/fiscobcos

可以参考build_chain.sh脚本的`-d`选项，https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/build_chain.html#id4

但docker模式只给了demo，如果要实际生产使用，需要对docker有一定基础，然后修改网络相关配置
