### ISSUE TITLE
可以直接使用标准的web3.js+node.js开发吗？

### ISSUE THREAD

**Issue by greatGregLiu** [FISCO-BCOS/FISCO-BCOS#9]
与您们FISCO-BCOS提供java库的web3j有什么差异啊？对我们开发出来的应用有什么影响？谢谢

**Comment by greatGregLiu** [comment]
另外发现bcosorg里好像是可以支持web3.js+node.js的。不知道我们这个FISCO-BCOS有多大的变化

**Comment by cristicmf** [comment]
基于web3.js做了修改

**Comment by morebtcg** [comment]
fisco-bcos无法用标准的web3.js，可以使用fisco-bcos代码目录下web3lib内提供的web3js
