### ISSUE TITLE
TransactionReceipt 交易结果logs为空

### ISSUE THREAD

**Issue by zhige2003** [FISCO-BCOS/FISCO-BCOS#90]
交易之后，想通过TransactionReceipt的结果，分析event事件来确认是否成功。但是logs中的为空，判断失败。烦请大神分析一下原因。
00:01:31.482 DEBUG org.bcos.web3j.protocol.channel.ChannelEthereumService 54 send - 收到ethereum响应:53812fd571b943bc93b0def3c38e3328 0 {"id":1,"jsonrpc":"2.0","result":{"blockHash":"0xe7f3779f6c04b066cfe34c6f0d397cd79a728bf9f45279d0aa3359ee8db3e117","blockNumber":35,"contractAddress":"0xe9ed8526260796ee667e7217b239fdb357fcdfc5","cumulativeGasUsed":"0x115ad7","gasUsed":"0x115ad7","logs":[],"transactionHash":"0x66640d3e55957b8291087078b8205f94fd004d03ea344a9a3a8951b4cc20f45e","transactionIndex":0}}

**Comment by fisco-dev** [comment]
根据交易hash已经获取到了transactionReceipt， 但是如果event log为空， 说明逻辑并没有走到相关流程， 方便的话可以将代码段贴出来看下

**Comment by bxq2011hust** [comment]
长时间没有回复，关闭issue，如果问题没有解决，欢迎重新打开。
