### ISSUE TITLE
 运行区块链命令时./gradlew build，一直显示downloading

### ISSUE THREAD

**Issue by phillipyuan** [FISCO-BCOS/FISCO-BCOS#907]
在官方教程./gradlew build 有编译的功能， 但是使用了这个命令之后就一直在显示downloading gradle 5.0 的包。不知道有没有办法解决这个问题或者用其他方法进行编译?

![QQ图片20190718084919](https://user-images.githubusercontent.com/26888403/61466951-6296d800-a9ad-11e9-9af6-075897146d73.png)

![QQ图片20190718223854](https://user-images.githubusercontent.com/26888403/61466957-6591c880-a9ad-11e9-8fee-b3d93181dd45.png)

官方教程地址：
https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/tutorial/sdk_application.html#id10

**Comment by phillipyuan** [comment]
Download 成功了，但是似乎有一下错误，感觉好像是压缩包有问题？

Unzipping /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip to /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by ywy2090** [comment]
/home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip 可以检查下这个文件是不是有问题，看异常是打开文件的问题 ： 1. 有么有下载完全，手动执行unzip解压成功说明文件是全的  2. 有无操作权限   
也可以自己安装gradle , 然后用gradle build来编译。

**Comment by ywy2090** [comment]
> Download 成功了，但是似乎有一下错误，感觉好像是压缩包有问题？
> 
> Unzipping /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip to /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7
> Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> at java.util.zip.ZipFile.open(Native Method)
> at java.util.zip.ZipFile.(ZipFile.java:225)
> at java.util.zip.ZipFile.(ZipFile.java:155)
> at java.util.zip.ZipFile.(ZipFile.java:169)
> at org.gradle.wrapper.Install.unzip(Install.java:215)
> at org.gradle.wrapper.Install.access$600(Install.java:27)
> at org.gradle.wrapper.Install$1.call(Install.java:75)
> at org.gradle.wrapper.Install$1.call(Install.java:48)
> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
> at org.gradle.wrapper.Install.createDist(Install.java:48)
> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
> at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

/home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip 可以检查下这个文件是不是有问题，看异常是打开文件的问题 ： 1. 有么有下载完全，手动执行unzip解压成功说明文件是全的 2. 有无操作权限
也可以自己安装gradle , 然后用gradle build来编译。

**Comment by phillipyuan** [comment]
> > Download 成功了，但是似乎有一下错误，感觉好像是压缩包有问题？
> > Unzipping /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip to /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7
> > Exception in thread "main" java.util.zip.ZipException: error in opening zip file
> > at java.util.zip.ZipFile.open(Native Method)
> > at java.util.zip.ZipFile.(ZipFile.java:225)
> > at java.util.zip.ZipFile.(ZipFile.java:155)
> > at java.util.zip.ZipFile.(ZipFile.java:169)
> > at org.gradle.wrapper.Install.unzip(Install.java:215)
> > at org.gradle.wrapper.Install.access$600(Install.java:27)
> > at org.gradle.wrapper.Install$1.call(Install.java:75)
> > at org.gradle.wrapper.Install$1.call(Install.java:48)
> > at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
> > at org.gradle.wrapper.Install.createDist(Install.java:48)
> > at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
> > at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
> /home/phillip/.gradle/wrapper/dists/gradle-5.0-all/4mxuau4c77thx8zlvtz4xiez7/gradle-5.0-all.zip 可以检查下这个文件是不是有问题，看异常是打开文件的问题 ： 1. 有么有下载完全，手动执行unzip解压成功说明文件是全的 2. 有无操作权限
> 也可以自己安装gradle , 然后用gradle build来编译。

非常感谢，最终确认是权限问题！
