### ISSUE TITLE
非JAVA语言开发疑问

### ISSUE THREAD

**Issue by LogicJake** [FISCO-BCOS/FISCO-BCOS#910]
官方貌似没有提供除JAVA外的JDK，所以想用RPC的方式进行交互发起交易，对sendRawTransaction的参数rlp: string - 签名的交易数据有疑问，请问：
* 这一步是如何对数据进行签名的?
* 交易数据格式是啥?

希望不吝赐教。

**Comment by muchaonan** [comment]
可以用web3。

对于sendRawTransaction。我看到官方的部署例子中，有一个.transTest.sh文件。文件的第39行有sendRawTransaction的内容。

`txBytes="f8eca003eb675ec791c2d19858c91d0046821c27d815e2e9c15${random_id}0a8402faf08082${limit}948c17cf316c1063ab6c89df875e96c9f0f5b2f74480b8644ed3885e0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a464953434f2042434f53000000000000000000000000000000000000000000000101801ba09edf7c0cb63645442aff11323916d51ec5440de979950747c0189f338afdcefda02f3473184513c6a3516e066ea98b7cfb55a79481c9db98e658dd016c37f03dcf"`

在第42行有执行的脚本：
`curl -s -X POST --data '{"jsonrpc":"2.0","method":"sendRawTransaction","params":['${target_group}', "'$txBytes'"],"id":83}' ${ip_port}`

但这个格式我也没看明白，不明白${random_id}参数前的字符代表什么，不明白${limit}参数前后的字符代表什么（猜测${limit}参数后面是主要的数据）。
我在测试中，数据可以发送到以太坊，但不能发送的fisco。
