### ISSUE TITLE
源码编译出错

### ISSUE THREAD

**Issue by kyonRay** [FISCO-BCOS/FISCO-BCOS#912]
## 环境
- OS：Ubuntu 16.04 WSL
- g++：7.4.0
- cmake：3.10.2
- make：4.1
- FISCO-BCOS：branch master，应该是2.0.0
## 报错
![image](https://user-images.githubusercontent.com/32325790/61694785-c8e07980-ad64-11e9-96d6-090dc51847ee.png)

**Comment by bxq2011hust** [comment]
这是因为我们启用了比较严格的检查，而高版本g++的检查没有忽略对boost库的检查导致的。
注释下面这行
https://github.com/FISCO-BCOS/FISCO-BCOS/blob/c8b15313976cb5815ec817cda093d1ac55e496f9/cmake/EthCompilerSettings.cmake#L41
