### ISSUE TITLE
CRUD合约查询所有记录问题

### ISSUE THREAD

**Issue by pengbs** [FISCO-BCOS/FISCO-BCOS#940]
fisco-bcos版本:2.0
请问CRUD合约如果我想获取所有记录，不根据主键过滤该如何实现呢？我看Table.sol合约里面select方法需要传入过滤条件

**Comment by fqliao** [comment]
目前对于记录的操作，包括查询，插入，更新和删除操作均需要该记录对应的主键值。如果节点采用的数据库是[mysql](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/manual/distributed_storage.html#mysql)，则可以通过mysql sql查询记录，不需要主键值(节点默认数据存储采用rocksdb，只能通过crud合约、[crud service接口](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#crudservice)或者[控制台](https://fisco-bcos-documentation.readthedocs.io/zh_CN/latest/docs/sdk/java_sdk.html#crudservice)，依据传入的主键值查询记录)。
