### ISSUE TITLE
说明文档部分有疑义

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/FISCO-BCOS#97]
wiki系统参数说明中对系统参数的说明和fisco bcos说明书中对全网配置参数的说明有不一致的地方，还请校验确定统一，目前从源码来看是wiki中所写和代码一致

**Comment by cyjseagull** [comment]
系统参数的默认值和推荐值有问题，我们会尽快修正这个问题，保持和代码一致

**Comment by fisco-dev** [comment]
已经修改，安排在v1.3.1版本更新
